;;; autograd-test.el --- numerical gradient checks for modern-block autograd  -*- lexical-binding: t; -*-
;; Run: emacs -Q --batch -L lisp -L ../nelisp-photon/lisp -l test/autograd-test.el
(add-to-list 'load-path (expand-file-name "lisp"))
(add-to-list 'load-path (expand-file-name "../nelisp-photon/lisp"))
(require 'photon-tensor)
(require 'photon-autograd)
(require 'nl-llm-autograd)

(defvar ag--fail 0)
(defun ag--ck (name ok &optional extra)
  (princ (format "%-46s %s  %s\n" name (if ok "PASS"
                                         (progn (setq ag--fail (1+ ag--fail)) "FAIL"))
                 (or extra ""))))
(defun ag--mk (rows cols seed)
  (let ((v (make-vector (* rows cols) 0.0)) (i 0))
    (while (< i (* rows cols))
      (aset v i (* 0.2 (- (mod (+ (* (1+ i) 7) seed) 11) 5))) (setq i (1+ i)))
    (photon-autograd-const (photon-tensor (if (= cols 0) (list rows) (list rows cols)) v))))
(defun ag--vec (n seed)
  (let ((v (make-vector n 0.0)) (i 0))
    (while (< i n) (aset v i (+ 0.5 (* 0.1 (mod (+ (* (1+ i) 5) seed) 7)))) (setq i (1+ i)))
    (photon-autograd-const (photon-tensor (list n) v))))
(defun ag--mask (n)
  (let ((v (make-vector n 0.0)) (i 0))
    (while (< i n) (aset v i (- (mod (* (1+ i) 13) 7) 3.0)) (setq i (1+ i))) v))
(defun ag--loss (out w)
  (let* ((d (photon-tensor-data (pav-value out))) (n (length d)) (s 0.0) (i 0))
    (while (< i n) (setq s (+ s (* (aref d i) (aref w i)))) (setq i (1+ i))) s))

(defun ag--gradcheck (name inputs forward idx)
  (let ((eps 1.0e-5) (tol 1.0e-3))
    (photon-autograd-zero-grad inputs)
    (photon-autograd-reset-tape)
    (let* ((out (funcall forward)) (od (photon-tensor-data (pav-value out))) (w (ag--mask (length od))))
      (let ((og (photon-tensor-data (pav-grad out))) (i 0) (n (length od)))
        (while (< i n) (aset og i (aref w i)) (setq i (1+ i))))
      (dolist (v photon-autograd--tape) (when (pav-backward v) (funcall (pav-backward v) (pav-grad v))))
      (let* ((target (nth idx inputs))
             (ana (copy-sequence (photon-tensor-data (pav-grad target))))
             (xd (photon-tensor-data (pav-value target))) (nx (length xd))
             (maxrel 0.0) (k 0))
        (while (< k nx)
          (let ((orig (aref xd k)))
            (aset xd k (+ orig eps)) (photon-autograd-reset-tape)
            (let ((lp (ag--loss (funcall forward) w)))
              (aset xd k (- orig eps)) (photon-autograd-reset-tape)
              (let* ((lm (ag--loss (funcall forward) w))
                     (num (/ (- lp lm) (* 2.0 eps)))
                     (den (max 1.0e-4 (abs num) (abs (aref ana k))))
                     (rel (/ (abs (- num (aref ana k))) den)))
                (when (> rel maxrel) (setq maxrel rel)))
              (aset xd k orig)))
          (setq k (1+ k)))
        (ag--ck name (< maxrel tol) (format "maxrel=%.2e" maxrel))))))

;; silu
(let ((x (ag--mk 3 4 1)))
  (ag--gradcheck "ag-silu d/dx" (list x) (lambda () (nl-llm-ag-silu x)) 0))
;; elementwise mul
(let ((a (ag--mk 3 4 1)) (b (ag--mk 3 4 2)))
  (ag--gradcheck "ag-mul d/da" (list a b) (lambda () (nl-llm-ag-mul a b)) 0)
  (ag--gradcheck "ag-mul d/db" (list a b) (lambda () (nl-llm-ag-mul a b)) 1))
;; rmsnorm (x and gamma)
(let ((x (ag--mk 3 4 1)) (g (ag--vec 4 3)))
  (ag--gradcheck "ag-rmsnorm d/dx" (list x g) (lambda () (nl-llm-ag-rmsnorm x g 1.0e-6)) 0)
  (ag--gradcheck "ag-rmsnorm d/dgamma" (list x g) (lambda () (nl-llm-ag-rmsnorm x g 1.0e-6)) 1))
;; rope (heads=2, dim=4 -> hd=2)
(let ((x (ag--mk 3 4 1)))
  (ag--gradcheck "ag-rope d/dx" (list x) (lambda () (nl-llm-ag-rope x 2)) 0))
;; swiglu end-to-end (x and one weight)
(let ((x (ag--mk 2 4 1)) (wg (ag--mk 6 4 2)) (bg (ag--vec 6 1))
      (wu (ag--mk 6 4 3)) (bu (ag--vec 6 2)) (wd (ag--mk 4 6 4)) (bd (ag--vec 4 3)))
  (ag--gradcheck "ag-swiglu d/dx" (list x wg bg wu bu wd bd)
                 (lambda () (nl-llm-ag-swiglu x wg bg wu bu wd bd)) 0)
  (ag--gradcheck "ag-swiglu d/dWg" (list x wg bg wu bu wd bd)
                 (lambda () (nl-llm-ag-swiglu x wg bg wu bu wd bd)) 1))

(princ (format "NL-LLM-AUTOGRAD %s (%d failures)\n"
               (if (= ag--fail 0) "ALL-PASS" "HAS-FAILURES") ag--fail))
(kill-emacs (if (= ag--fail 0) 0 1))
;;; autograd-test.el ends here
