;;; copy-architecture-test.el --- tests for COPY architecture comparison -*- lexical-binding: t; -*-

(require 'cl-lib)
(require 'ert)

(let ((here (file-name-directory (or load-file-name buffer-file-name))))
  (add-to-list 'load-path (expand-file-name "../lisp" here))
  (load (expand-file-name "../lisp/nl-llm-stack-paths.el"
                          (file-name-directory (or load-file-name buffer-file-name
                                                   default-directory))) nil t)
  (load (expand-file-name "../examples/compare-copy-architecture.el" here)
        nil nil t))

(declare-function nl-llm-compare-copy-architecture--geometry
                  "compare-copy-architecture" (dim ff blocks heads))
(declare-function nl-llm-compare-copy-architecture--model
                  "compare-copy-architecture" (geometry))
(declare-function nl-llm-compare-copy-architecture--parameter-count
                  "compare-copy-architecture" (model))
(declare-function nl-llm-compare-copy-architecture-run
                  "compare-copy-architecture" (&optional mode))
(declare-function nl-llm-compare-copy-diversity-dataset
                  "compare-copy-diversity" ())
(defvar nl-llm-compare-copy-architecture-auto-run)
(defvar nl-llm-learn-copy-curriculum-auto-run)
(defvar nl-llm-compare-copy-diversity-auto-run)

(ert-deftest nl-llm-copy-architecture-geometries-have-expected-parameter-counts ()
  (let* ((baseline-geometry
          (nl-llm-compare-copy-architecture--geometry 32 64 1 1))
         (candidate-geometry
          (nl-llm-compare-copy-architecture--geometry 24 48 2 1))
         (baseline (nl-llm-compare-copy-architecture--model baseline-geometry))
         (candidate (nl-llm-compare-copy-architecture--model candidate-geometry)))
    (should (= (nl-llm-compare-copy-architecture--parameter-count baseline)
               27264))
    (should (= (nl-llm-compare-copy-architecture--parameter-count candidate)
               24616))
    (should (= (plist-get baseline :dim) 32))
    (should (= (plist-get candidate :dim) 24))
    (should (= (plist-get baseline :nblocks) 1))
    (should (= (plist-get candidate :nblocks) 2))))

(ert-deftest nl-llm-copy-architecture-dataset-reuses-diversity-exposures ()
  (let ((dataset (nl-llm-compare-copy-diversity-dataset)))
    (should (= (length (plist-get dataset :candidate)) 4096))
    (should (= (plist-get dataset :final-state) 3512444440))
    (should (equal (plist-get dataset :literal-sha256)
                   "62a0043f734326cda3ec1afc9aad3f8ccefe33447384352325b5eb9e03412036"))
    (should (= (plist-get dataset :rejected-dev-count) 69))))

(ert-deftest nl-llm-copy-architecture-paired-run-trains-both-geometry-arms ()
  (let* ((real-dataset (nl-llm-compare-copy-diversity-dataset))
         (models nil) (scores 0) (trainings nil)
         (greedy-calls 0) (teacher-calls 0) (teacher-example-counts nil)
         (teacher-call-kinds nil))
    (cl-letf (((symbol-function 'nl-llm-gpu-available-p) (lambda () nil))
              ((symbol-function 'nl-llm-compare-copy-diversity-dataset)
               (lambda () real-dataset))
              ((symbol-function 'nl-llm-compare-copy-architecture--model)
               (lambda (_geometry)
                 (let ((model (if models 'candidate 'baseline)))
                   (push model models)
                   model)))
              ((symbol-function 'nl-llm-compare-copy-architecture--parameter-count)
               (lambda (_model) 123))
              ((symbol-function 'nl-llm-learn-literal-copy--model-hash)
               (lambda (_model) "same"))
              ((symbol-function 'nl-llm-learn-copy-curriculum--scores)
               (lambda (_model _dataset)
                 (setq greedy-calls (1+ greedy-calls))
                 (setq scores (1+ scores))
                 '(:train (:ok 0) :dev (:ok 0))))
              ((symbol-function 'nl-llm-copy-teacher-forcing-score)
               (lambda (model examples)
                 (setq teacher-calls (1+ teacher-calls))
                 (push (length examples) teacher-example-counts)
                 (push (list model (length examples)) teacher-call-kinds)
                 '(:mode teacher-forced :total (:tokens 1))))
              ((symbol-function 'nl-llm-compare-copy-diversity-train-arm)
               (lambda (model examples)
                 (push (list model examples) trainings)
                 '(:steps 4096 :exposures 4096))))
      (let ((report (nl-llm-compare-copy-architecture-run 'paired)))
        (should (= scores 4))
        (should (= greedy-calls 4))
        (should (= teacher-calls 8))
        (should (equal (sort teacher-example-counts #'<)
                       '(32 32 32 32 128 128 128 128)))
        (should (equal (nreverse teacher-call-kinds)
                       '((baseline 128) (baseline 32)
                         (candidate 128) (candidate 32)
                         (baseline 128) (baseline 32)
                         (candidate 128) (candidate 32))))
        (should (= (length models) 2))
        (should (= (length trainings) 2))
        (should (equal (mapcar (lambda (item) (length (cadr item))) trainings)
                       '(4096 4096)))
        (should (eq (cadr (car trainings)) (plist-get real-dataset :candidate)))
        (should (eq (cadr (cadr trainings)) (plist-get real-dataset :candidate)))
        (should (= (plist-get (plist-get report :baseline) :parameter-count)
                   123))
        (should (= (plist-get (plist-get report :candidate) :parameter-count)
                   123))
        (should-not (plist-get (plist-get report :baseline) :weights-changed))
        (should-not (plist-get (plist-get report :candidate) :weights-changed))))))

(ert-deftest nl-llm-copy-architecture-run-rejects-evaluation-mutation ()
  (let ((train-calls 0))
    (cl-letf (((symbol-function 'nl-llm-gpu-available-p) (lambda () nil))
              ((symbol-function 'nl-llm-compare-copy-diversity-dataset)
               (lambda () '(:candidate [candidate] :train [train] :dev [dev])))
              ((symbol-function 'nl-llm-compare-copy-architecture--model)
               (lambda (_geometry) (list :weight 0)))
              ((symbol-function 'nl-llm-learn-literal-copy--model-hash)
               (lambda (model) (format "weight-%d" (plist-get model :weight))))
              ((symbol-function 'nl-llm-learn-copy-curriculum--scores)
               (lambda (model _dataset)
                 (setf (plist-get model :weight) 1)
                 '(:train (:ok 0) :dev (:ok 0))))
              ((symbol-function 'nl-llm-copy-teacher-forcing-score)
               (lambda (&rest _args) '(:mode teacher-forced)))
              ((symbol-function 'nl-llm-compare-copy-diversity-train-arm)
               (lambda (&rest _args) (setq train-calls (1+ train-calls)))) )
      (let ((condition
             (should-error (nl-llm-compare-copy-architecture-run 'paired))))
        (should (string-match-p "evaluation mutated model weights"
                                (error-message-string condition))))
      (should (= train-calls 0)))))

(ert-deftest nl-llm-copy-architecture-run-rejects-after-evaluation-mutation ()
  (let ((train-calls 0) (score-calls 0))
    (cl-letf (((symbol-function 'nl-llm-gpu-available-p) (lambda () nil))
              ((symbol-function 'nl-llm-compare-copy-diversity-dataset)
               (lambda () '(:candidate [candidate] :train [train] :dev [dev])))
              ((symbol-function 'nl-llm-compare-copy-architecture--model)
               (lambda (_geometry) (list :weight 0)))
              ((symbol-function 'nl-llm-learn-literal-copy--model-hash)
               (lambda (model) (format "weight-%d" (plist-get model :weight))))
              ((symbol-function 'nl-llm-learn-copy-curriculum--scores)
               (lambda (model _dataset)
                 (setq score-calls (1+ score-calls))
                 (when (= score-calls 3)
                   (setf (plist-get model :weight) 1))
                 '(:train (:ok 0) :dev (:ok 0))))
              ((symbol-function 'nl-llm-copy-teacher-forcing-score)
               (lambda (&rest _args) '(:mode teacher-forced)))
              ((symbol-function 'nl-llm-compare-copy-diversity-train-arm)
               (lambda (&rest _args) (setq train-calls (1+ train-calls)))) )
      (let ((condition
             (should-error (nl-llm-compare-copy-architecture-run 'paired))))
        (should (string-match-p "evaluation mutated model weights"
                                (error-message-string condition))))
      (should (= train-calls 2)))))

(ert-deftest nl-llm-copy-architecture-is-explicit-and-validates-mode ()
  (should-not nl-llm-compare-copy-architecture-auto-run)
  (cl-letf (((symbol-function 'nl-llm-gpu-available-p) (lambda () t)))
    (should-error (nl-llm-compare-copy-architecture-run 'paired)))
  (should-error (nl-llm-compare-copy-architecture-run 'unknown)))

(ert-deftest nl-llm-copy-architecture-load-guards-ambient-dependency-runners ()
  (let ((gpu-calls 0)
        (nl-llm-learn-copy-curriculum-auto-run t)
        (nl-llm-compare-copy-diversity-auto-run t)
        (here (file-name-directory (or load-file-name buffer-file-name))))
    (cl-letf (((symbol-function 'nl-llm-gpu-available-p)
               (lambda () (setq gpu-calls (1+ gpu-calls)) t))
              ((symbol-function 'nl-llm-gpu-enable)
               (lambda () (error "ambient load must not enable GPU")))
              ((symbol-function 'nl-llm-gpu-disable)
               (lambda () (error "ambient load must not disable GPU")))
              ((symbol-function 'nl-llm-compare-copy-diversity-run)
               (lambda (&rest _args) (error "ambient load ran diversity")))
              ((symbol-function 'nl-llm-learn-copy-curriculum-run)
               (lambda (&rest _args) (error "ambient load ran curriculum"))))
      (load (expand-file-name "../examples/compare-copy-architecture.el" here)
            nil nil t))
    (should (= gpu-calls 0))
    (should nl-llm-learn-copy-curriculum-auto-run)
    (should nl-llm-compare-copy-diversity-auto-run)))

(ert-run-tests-batch-and-exit)

;;; copy-architecture-test.el ends here
