;;; copy-diversity-test.el --- tests for COPY diversity ablation -*- lexical-binding: t; -*-

(require 'cl-lib)
(require 'ert)

(let ((here (file-name-directory (or load-file-name buffer-file-name))))
  (add-to-list 'load-path (expand-file-name "../lisp" here))
  (load (expand-file-name "../lisp/nl-llm-stack-paths.el"
                          (file-name-directory (or load-file-name buffer-file-name
                                                   default-directory))) nil t)
  (load (expand-file-name "../examples/compare-copy-diversity.el" here)
        nil nil t))

(declare-function nl-llm-compare-copy-diversity-dataset
                  "compare-copy-diversity" ())
(declare-function nl-llm-compare-copy-diversity-train-arm
                  "compare-copy-diversity" (model examples &optional epochs))
(declare-function nl-llm-compare-copy-diversity-run
                  "compare-copy-diversity" (&optional mode))
(defvar nl-llm-compare-copy-diversity-auto-run)

(ert-deftest nl-llm-copy-diversity-data-is-deterministic-and-disjoint ()
  (let* ((left (nl-llm-compare-copy-diversity-dataset))
         (right (nl-llm-compare-copy-diversity-dataset))
         (candidate (plist-get left :candidate))
         (dev (plist-get left :dev))
         (dev-literals (mapcar (lambda (example) (plist-get example :literal))
                               (append dev nil)))
         (lengths (mapcar (lambda (example) (plist-get example :length))
                          (append candidate nil))))
    (should (equal left right))
    (should (= (length candidate) 4096))
    (should (= (length dev) 32))
    (dolist (length '(1 2 3 4 8 12 16 24))
      (should (= (cl-count length lengths) 512)))
    (should (= (length (plist-get left :unique-counts)) 8))
    (should (equal (plist-get left :unique-counts)
                   '[ (1 . 38) (2 . 447) (3 . 510) (4 . 512)
                      (8 . 512) (12 . 512) (16 . 512) (24 . 512)]))
    (dolist (example (append candidate nil))
      (should-not (member (plist-get example :literal) dev-literals))
      (should (= (length (plist-get example :completion))
                 (1+ (plist-get example :length)))))
    (should (= (length (plist-get left :exposures-by-length)) 8))
    (should (= (plist-get left :seed) 2654435769))
    (should (= (plist-get left :final-state) 3512444440))
    (should (= (plist-get left :rejected-dev-count) 69))
    (should (equal (plist-get left :literal-sha256)
                   "62a0043f734326cda3ec1afc9aad3f8ccefe33447384352325b5eb9e03412036"))
    (let ((literals (mapcar (lambda (example) (plist-get example :literal))
                            (append candidate nil))))
      (should (equal (cl-subseq literals 0 3) '("l" "s" "_")))
      (should (equal (last literals 1)
                     '("yfb0m8poioe/0m90ybw/ethw"))))))

(ert-deftest nl-llm-copy-diversity-training-uses-one-context-and-32-batches ()
  (let ((examples (make-vector 4096 '(:literal "x")))
        (encoded-calls 0) (train-calls 0) (enable-calls 0)
        (disable-calls 0) (free-calls 0) (sync-calls 0) train-args
        (context (list :step 0)))
    (cl-letf (((symbol-function 'nl-llm-gpu-available-p) (lambda () nil))
              ((symbol-function 'nl-llm-gpu-enable)
               (lambda () (setq enable-calls (1+ enable-calls)) t))
              ((symbol-function 'nl-llm-gpu-disable)
               (lambda () (setq disable-calls (1+ disable-calls))))
              ((symbol-function 'nl-llm-agent-ondevice-from-model)
               (lambda (&rest args) (should (eq (car args) 'model)) context))
              ((symbol-function 'nl-llm-agent-ondevice-free)
               (lambda (_ctx) (setq free-calls (1+ free-calls))))
              ((symbol-function 'nl-llm-agent-ondevice-sync)
               (lambda (_ctx) (setq sync-calls (1+ sync-calls))))
              ((symbol-function 'nl-llm-compare-copy-diversity--encoded)
               (lambda (batch)
                 (setq encoded-calls (1+ encoded-calls))
                 (should (= (length batch) 128))
                 '(:trajectories [[1 2]] :loss-starts [1]
                   :dataset-sha256 "batch")))
              ((symbol-function 'nl-llm-agent-ondevice-train)
               (lambda (&rest args)
                 (setq train-calls (1+ train-calls)
                       train-args args)
                 (setf (plist-get (car args) :step)
                       (* train-calls 128))
                 128)))
      (let ((result (nl-llm-compare-copy-diversity-train-arm
                     'model examples)))
        (should (= (plist-get result :exposures) 4096))
        (should (= (plist-get result :batch-count) 32))
        (should (= (plist-get result :steps) 4096))
        (should (= (length (plist-get result :batch-sha256)) 32))
        (should (= (length (plist-get result :dataset-sha256)) 32)))
    (should (= encoded-calls 32))
    (should (= train-calls 32))
    (should (= enable-calls 1))
    (should (= disable-calls 1))
    (should (= free-calls 1))
    (should (= sync-calls 1))
    (should (eq (car train-args) context))
    (should (= (nth 2 train-args) 1))
    (should (= (plist-get context :step) 4096)))))

(ert-deftest nl-llm-copy-diversity-training-rejects-active-gpu ()
  (cl-letf (((symbol-function 'nl-llm-gpu-available-p) (lambda () t))
            ((symbol-function 'nl-llm-gpu-enable)
             (lambda () (error "must not enable"))))
    (should-error
     (nl-llm-compare-copy-diversity-train-arm
      'model (make-vector 128 nil)))))

(ert-deftest nl-llm-copy-diversity-run-is-explicit-and-validates-mode ()
  (should-not nl-llm-compare-copy-diversity-auto-run)
  (cl-letf (((symbol-function 'nl-llm-gpu-available-p) (lambda () t)))
    (should-error (nl-llm-compare-copy-diversity-run 'paired)))
  (should-error (nl-llm-compare-copy-diversity-run 'unknown)))

(ert-deftest nl-llm-copy-diversity-paired-run-calls-both-arms ()
  (let ((models nil) (scores 0) arms)
    (cl-letf (((symbol-function 'nl-llm-gpu-available-p) (lambda () nil))
              ((symbol-function 'nl-llm-compare-copy-diversity-dataset)
               (lambda () '(:train [train] :dev [dev] :candidate [candidate])))
              ((symbol-function 'nl-llm-compare-copy-diversity--model)
               (lambda ()
                 (let ((model (list :id (length models) :weight 0)))
                   (push model models)
                   model)))
              ((symbol-function 'nl-llm-learn-literal-copy--model-hash)
               (lambda (model) (format "weight-%d" (plist-get model :weight))))
              ((symbol-function 'nl-llm-learn-copy-curriculum--scores)
               (lambda (_model _dataset)
                 (setq scores (1+ scores))
                 '(:score 0)))
              ((symbol-function 'nl-llm-compare-copy-diversity-train-arm)
               (lambda (model examples)
                 (push (list model (length examples)) arms)
                 (setf (plist-get model :weight)
                       (1+ (plist-get model :weight)))
                 '(:steps 4096 :exposures 4096))))
      (let ((report (nl-llm-compare-copy-diversity-run 'paired)))
        (should (= scores 4))
        (should (= (length models) 2))
        (should (= (length arms) 2))
        (should (equal (sort (mapcar #'cadr arms) #'<) '(1 1)))
        (should (equal (sort (mapcar (lambda (item) (plist-get (car item) :id))
                                    arms) #'<)
                       '(0 1)))
        (should (plist-get (plist-get report :baseline) :weights-changed))
        (should (plist-get (plist-get report :candidate) :weights-changed))))))

(ert-deftest nl-llm-copy-diversity-run-rejects-evaluation-mutation ()
  (let ((train-calls 0))
    (cl-letf (((symbol-function 'nl-llm-gpu-available-p) (lambda () nil))
              ((symbol-function 'nl-llm-compare-copy-diversity-dataset)
               (lambda () '(:train [train] :dev [dev] :candidate [candidate])))
              ((symbol-function 'nl-llm-compare-copy-diversity--model)
               (lambda () (list :weight 0)))
              ((symbol-function 'nl-llm-learn-literal-copy--model-hash)
               (lambda (model) (format "weight-%d" (plist-get model :weight))))
              ((symbol-function 'nl-llm-learn-copy-curriculum--scores)
               (lambda (model _dataset)
                 (setf (plist-get model :weight) 1)
                 '(:score 0)))
              ((symbol-function 'nl-llm-compare-copy-diversity-train-arm)
               (lambda (&rest _args) (setq train-calls (1+ train-calls)))) )
      (should-error (nl-llm-compare-copy-diversity-run 'paired))
      (should (= train-calls 0)))))

(ert-run-tests-batch-and-exit)

;;; copy-diversity-test.el ends here
