;;; gpu-moe-test.el --- on-device training of the full GQA + MoE block  -*- lexical-binding: t; -*-
;; Trains the full modern block with a top-k sparse MoE FFN (RMSNorm + GQA/RoPE
;; + MoE) + LM head, fully on-device via the resident-autograd builder, and
;; checks the loss trajectory matches the CPU autograd reference (nl-llm-ag-block
;; with a :router FFN).  Skips (exit 0) without a Vulkan device.
;;   emacs -Q --batch -L lisp -L ../nelisp-photon/lisp -l test/gpu-moe-test.el
(add-to-list 'load-path (expand-file-name "lisp"))
(add-to-list 'load-path (expand-file-name "../nelisp-photon/lisp"))
(require 'cl-lib)
(require 'photon-tensor)
(require 'photon-autograd)
(require 'nl-llm-autograd)
(require 'nl-llm-gpu)
(require 'nl-llm-gpu-ag)

(defvar gm--fail 0)
(defun gm--ck (name ok &optional extra)
  (princ (format "%-46s %s  %s\n" name
                 (if ok "PASS" (progn (setq gm--fail (1+ gm--fail)) "FAIL")) (or extra ""))))
(defun gm--vec (n seed sc)
  (let ((v (make-vector n 0.0)) (i 0))
    (while (< i n)
      (aset v i (* sc 2.0 (- (/ (float (mod (+ (* (1+ i) 2654435761) (* (1+ seed) 40503)) 65536))
                                65536.0) 0.5))) (setq i (1+ i))) v))
(defun gm--t (shape seed sc) (let ((n 1)) (dolist (d shape) (setq n (* n d)))
                               (photon-tensor shape (gm--vec n seed sc))))
(defun gm--ones (n) (photon-tensor (list n) (make-vector n 1.0)))
(defun gm--cp (tn) (photon-tensor (photon-tensor-shape tn) (copy-sequence (photon-tensor-data tn))))
(defun gm--ce (ld seq vocab targets)
  (let ((loss 0.0) (i 0))
    (while (< i seq)
      (let ((base (* i vocab)) (mx -1.0e30) (j 0))
        (while (< j vocab) (when (> (aref ld (+ base j)) mx) (setq mx (aref ld (+ base j)))) (setq j (1+ j)))
        (let ((s 0.0) (j2 0))
          (while (< j2 vocab) (setq s (+ s (exp (- (aref ld (+ base j2)) mx)))) (setq j2 (1+ j2)))
          (setq loss (- loss (- (- (aref ld (+ base (aref targets i))) mx) (log s))))))
      (setq i (1+ i)))
    (/ loss (float seq))))

(unless (nl-llm-gpu-enable)
  (princ "NL-LLM-GPU-MOE SKIP (no GPU server / Vulkan device)\n") (kill-emacs 0))

(let* ((seq 6) (dim 16) (heads 4) (kvh 2) (ff 24) (vocab 12) (ne 3) (topk 2)
       (hd (/ dim heads)) (kvdim (* kvh hd)) (lr 0.05) (steps 6) (sc 0.4)
       (scl (/ 1.0 (sqrt (float hd)))) (targets (vector 1 2 3 4 5 6))
       (x (gm--t (list seq dim) 1 sc))
       (ln1g (gm--ones dim)) (Wq (gm--t (list dim dim) 2 sc)) (bq (gm--t (list dim) 12 0.0))
       (Wk (gm--t (list kvdim dim) 3 sc)) (bk (gm--t (list kvdim) 13 0.0))
       (Wv (gm--t (list kvdim dim) 4 sc)) (bv (gm--t (list kvdim) 14 0.0))
       (Wo (gm--t (list dim dim) 5 sc)) (bo (gm--t (list dim) 15 0.0)) (ln2g (gm--ones dim))
       (router (gm--t (list ne dim) 20 sc)) (brouter (gm--t (list ne) 21 0.0))
       ;; expert weight bases
       (exb (let ((l nil) (e 0)) (while (< e ne)
              (push (list :wg (gm--t (list ff dim) (+ 30 (* e 6)) sc) :bg (gm--t (list ff) (+ 31 (* e 6)) 0.0)
                          :wu (gm--t (list ff dim) (+ 32 (* e 6)) sc) :bu (gm--t (list ff) (+ 33 (* e 6)) 0.0)
                          :wd (gm--t (list dim ff) (+ 34 (* e 6)) sc) :bd (gm--t (list dim) (+ 35 (* e 6)) 0.0)) l)
              (setq e (1+ e))) (nreverse l)))
       (lnfg (gm--ones dim)) (Wh (gm--t (list vocab dim) 9 sc)) (bh (gm--t (list vocab) 19 0.0))
       (tables (nl-llm-gpu-rope-tables seq hd))
       (onehot (let ((v (make-vector (* seq vocab) 0.0)) (i 0))
                 (while (< i seq) (aset v (+ (* i vocab) (aref targets i)) 1.0) (setq i (1+ i)))
                 (photon-tensor (list seq vocab) v)))
       (mask (let ((md (make-vector (* seq seq) 0.0)) (i 0))
               (while (< i seq) (let ((j (1+ i))) (while (< j seq) (aset md (+ (* i seq) j) -1.0e30) (setq j (1+ j)))) (setq i (1+ i)))
               (photon-tensor (list seq seq) md)))
       (gpu-losses nil) (cpu-losses nil))
  ;; ---- GPU via builder (MoE block) ----
  (let* ((b (nlga-new)) (xr (nlga-const b (gm--cp x)))
         (gex (mapcar (lambda (ex) (list :wg (nlga-param b (gm--cp (plist-get ex :wg))) :bg (nlga-param b (gm--cp (plist-get ex :bg)))
                                         :wu (nlga-param b (gm--cp (plist-get ex :wu))) :bu (nlga-param b (gm--cp (plist-get ex :bu)))
                                         :wd (nlga-param b (gm--cp (plist-get ex :wd))) :bd (nlga-param b (gm--cp (plist-get ex :bd))))) exb))
         (blk (list :ln1g (nlga-param b (gm--cp ln1g)) :wq (nlga-param b (gm--cp Wq)) :bq (nlga-param b (gm--cp bq))
                    :wk (nlga-param b (gm--cp Wk)) :bk (nlga-param b (gm--cp bk)) :wv (nlga-param b (gm--cp Wv)) :bv (nlga-param b (gm--cp bv))
                    :wo (nlga-param b (gm--cp Wo)) :bo (nlga-param b (gm--cp bo)) :ln2g (nlga-param b (gm--cp ln2g))
                    :router (nlga-param b (gm--cp router)) :brouter (nlga-param b (gm--cp brouter)) :experts gex :top-k topk))
         (lnfgr (nlga-param b (gm--cp lnfg))) (whr (nlga-param b (gm--cp Wh))) (bhr (nlga-param b (gm--cp bh)))
         (cosr (nlga-const b (car tables))) (sinr (nlga-const b (cdr tables)))
         (sposr (nlga-scalar b 1.0)) (snegr (nlga-scalar b -1.0)) (sclr (nlga-scalar b scl)) (oner (nlga-scalar b 1.0))
         (maskr (nlga-const b mask)) (ohr (nlga-const b onehot)) (lrr (nlga-scalar b lr))
         (x2 (nlga-block b xr blk heads kvh cosr sinr sposr snegr sclr maskr))
         (xf (nlga-rmsnorm b x2 lnfgr)) (logits (nlga-linear b xf whr bhr)) (lout (nlga-keep b logits oner)))
    (nlga-seed-ce b logits ohr) (nlga-finish b lrr) (nlga-compile b)
    (let ((s 0)) (while (< s steps)
      (push (gm--ce (nth lout (nlga-step b)) seq vocab targets) gpu-losses) (setq s (1+ s))))
    (nlga-free b))
  (setq gpu-losses (nreverse gpu-losses))
  (nl-llm-gpu-disable)   ; CPU reference on the CPU backend
  ;; ---- CPU autograd reference (MoE) ----
  (let* ((P (lambda (tn) (photon-autograd-const (gm--cp tn))))
         (xc (funcall P x))
         (cex (mapcar (lambda (ex) (list :wg (funcall P (plist-get ex :wg)) :bg (funcall P (plist-get ex :bg))
                                         :wu (funcall P (plist-get ex :wu)) :bu (funcall P (plist-get ex :bu))
                                         :wd (funcall P (plist-get ex :wd)) :bd (funcall P (plist-get ex :bd)))) exb))
         (blk (list :ln1g (funcall P ln1g) :wq (funcall P Wq) :bq (funcall P bq) :wk (funcall P Wk) :bk (funcall P bk)
                    :wv (funcall P Wv) :bv (funcall P bv) :wo (funcall P Wo) :bo (funcall P bo) :ln2g (funcall P ln2g)
                    :router (funcall P router) :brouter (funcall P brouter) :experts cex :top-k topk))
         (lnfgc (funcall P lnfg)) (whc (funcall P Wh)) (bhc (funcall P bh))
         (params (append (list (plist-get blk :ln1g) (plist-get blk :wq) (plist-get blk :bq) (plist-get blk :wk) (plist-get blk :bk)
                               (plist-get blk :wv) (plist-get blk :bv) (plist-get blk :wo) (plist-get blk :bo) (plist-get blk :ln2g)
                               (plist-get blk :router) (plist-get blk :brouter))
                         (apply #'append (mapcar (lambda (ex) (list (plist-get ex :wg) (plist-get ex :bg) (plist-get ex :wu)
                                                                    (plist-get ex :bu) (plist-get ex :wd) (plist-get ex :bd))) cex))
                         (list lnfgc whc bhc)))
         (s 0))
    (while (< s steps)
      (photon-autograd-reset-tape)
      (let* ((x2 (nl-llm-ag-block xc blk heads kvh)) (xf (nl-llm-ag-rmsnorm x2 lnfgc))
             (logits (photon-autograd-linear xf whc bhc)) (loss (photon-autograd-softmax-ce logits targets)))
        (push (aref (photon-tensor-data (pav-value loss)) 0) cpu-losses)
        (photon-autograd-zero-grad params) (photon-autograd-backward loss) (photon-autograd-sgd params lr))
      (setq s (1+ s)))
    (setq cpu-losses (nreverse cpu-losses)))
  (let ((maxrel 0.0) (i 0))
    (while (< i steps)
      (setq maxrel (max maxrel (/ (abs (- (nth i gpu-losses) (nth i cpu-losses))) (max 1e-4 (abs (nth i cpu-losses))))))
      (setq i (1+ i)))
    (gm--ck "MoE block forward GPU == CPU (step 0)"
            (< (/ (abs (- (car gpu-losses) (car cpu-losses))) (abs (car cpu-losses))) 2e-2)
            (format "gpu=%.4f cpu=%.4f" (car gpu-losses) (car cpu-losses)))
    (gm--ck "MoE block training GPU == CPU" (< maxrel 1e-1) (format "maxrel=%.2e" maxrel)))
  (gm--ck "MoE block trains on GPU (loss down)" (< (car (last gpu-losses)) (car gpu-losses))
          (format "loss %.4f -> %.4f" (car gpu-losses) (car (last gpu-losses))))
  (princ (format "GPU: %s\nCPU: %s\n"
                 (mapcar (lambda (l) (/ (round (* l 1000)) 1000.0)) gpu-losses)
                 (mapcar (lambda (l) (/ (round (* l 1000)) 1000.0)) cpu-losses)))
  (princ (format "NL-LLM-GPU-MOE %s (%d failures)\n" (if (= gm--fail 0) "ALL-PASS" "HAS-FAILURES") gm--fail))
  (kill-emacs (if (= gm--fail 0) 0 1)))
;;; gpu-moe-test.el ends here
