;;; gpu-stream-test.el --- on-GPU StreamingLLM == CPU streaming oracle  -*- lexical-binding: t; -*-
;; Checks the on-GPU bounded decode (nl-llm-gpu-stream) against the CPU streaming
;; reference (nl-llm-stream), and against the plain full decode when the cap is
;; never reached.  Pins the cache-relative-RoPE attention kernel + ring append.
;; Skips (exit 0) without a Vulkan device.
;;   emacs -Q --batch -L lisp -L ../nelisp-photon/lisp -l test/gpu-stream-test.el
(add-to-list 'load-path (expand-file-name "lisp"))
(add-to-list 'load-path (expand-file-name "../nelisp-photon/lisp"))
(require 'cl-lib)
(require 'photon-tensor)
(require 'nl-llm-decode)
(require 'nl-llm-stream)
(require 'nl-llm-gpu)
(require 'nl-llm-gpu-ag)
(require 'nl-llm-gpu-decode)

(defvar gs--fail 0)
(defun gs--ck (name ok &optional extra)
  (princ (format "%-50s %s  %s\n" name (if ok "PASS" (progn (setq gs--fail (1+ gs--fail)) "FAIL")) (or extra ""))))
(defun gs--t (shape seed sc) (let ((n 1)) (dolist (d shape) (setq n (* n d)))
  (photon-tensor shape (let ((v (make-vector n 0.0)) (i 0))
    (while (< i n) (aset v i (* sc 2.0 (- (/ (float (mod (+ (* (1+ i) 2654435761) (* (1+ seed) 40503)) 65536)) 65536.0) 0.5))) (setq i (1+ i))) v))))
(defun gs--ones (n) (photon-tensor (list n) (make-vector n 1.0)))
(defun gs--maxrel (g c vocab)
  (let ((mr 0.0) (j 0)) (while (< j vocab)
    (setq mr (max mr (/ (abs (- (aref g j) (aref c j))) (max 1e-3 (abs (aref c j)))))) (setq j (1+ j))) mr))

(unless (nl-llm-gpu-enable)
  (princ "NL-LLM-GPU-STREAM SKIP (no GPU server / Vulkan device)\n") (kill-emacs 0))

(let* ((dim 16) (heads 4) (kvh 2) (ff 24) (vocab 12) (hd (/ dim heads)) (kvdim (* kvh hd)) (sc 0.4)
       (toks (vector 0 1 2 3 4 5 6 7 8 9 10 11 0 2 4 6 8 10 1 3 5 7 9 11))
       (wte (gs--t (list vocab dim) 1 sc)) (lnfg (gs--ones dim)) (bh (gs--t (list vocab) 19 0.1))
       (mkblk (lambda (s0) (list :ln1g (gs--ones dim) :wq (gs--t (list dim dim) (+ s0 1) sc) :bq (gs--t (list dim) (+ s0 11) 0.1)
                                 :wk (gs--t (list kvdim dim) (+ s0 2) sc) :bk (gs--t (list kvdim) (+ s0 12) 0.1)
                                 :wv (gs--t (list kvdim dim) (+ s0 3) sc) :bv (gs--t (list kvdim) (+ s0 13) 0.1)
                                 :wo (gs--t (list dim dim) (+ s0 4) sc) :bo (gs--t (list dim) (+ s0 14) 0.1) :ln2g (gs--ones dim)
                                 :wg (gs--t (list ff dim) (+ s0 5) sc) :bg (gs--t (list ff) (+ s0 15) 0.1)
                                 :wu (gs--t (list ff dim) (+ s0 6) sc) :bu (gs--t (list ff) (+ s0 16) 0.1)
                                 :wd (gs--t (list dim ff) (+ s0 7) sc) :bd (gs--t (list dim) (+ s0 17) 0.1))))
       (blocks (list (funcall mkblk 100) (funcall mkblk 200))))
  ;; --- (A) cap > len: GPU streaming == plain full decode (no eviction) ---
  (let* ((nsink 2) (win 20) (cap (+ nsink win)) (len 18)
         (tables (nl-llm-gpu-rope-tables cap hd))
         (ctx (nl-llm-gpu-stream-new wte blocks lnfg bh heads kvh dim vocab nsink win tables))
         (gpu nil) (p 0))
    (while (< p len) (push (copy-sequence (nl-llm-gpu-stream-step ctx (aref toks p) p)) gpu) (setq p (1+ p)))
    (nl-llm-gpu-stream-free ctx) (setq gpu (nreverse gpu))
    (nl-llm-gpu-disable)
    (let ((caches (mapcar (lambda (_) (nl-llm-dcache-new len dim heads kvh)) blocks)) (mr 0.0) (q 0))
      (while (< q len)
        (setq mr (max mr (gs--maxrel (nth q gpu) (nl-llm-decode-step (aref toks q) blocks caches wte lnfg bh dim) vocab)))
        (setq q (1+ q)))
      (gs--ck "cap>len: GPU streaming == full decode" (< mr 5e-3) (format "maxrel=%.2e" mr)))
    (nl-llm-gpu-enable))
  ;; --- (B) cap << len: GPU streaming == CPU streaming oracle (eviction) ---
  (let* ((nsink 2) (win 6) (cap (+ nsink win)) (len 24)
         (tables (nl-llm-gpu-rope-tables cap hd))
         (ctx (nl-llm-gpu-stream-new wte blocks lnfg bh heads kvh dim vocab nsink win tables))
         (gpu nil) (p 0))
    (while (< p len) (push (copy-sequence (nl-llm-gpu-stream-step ctx (aref toks p) p)) gpu) (setq p (1+ p)))
    (nl-llm-gpu-stream-free ctx) (setq gpu (nreverse gpu))
    (nl-llm-gpu-disable)
    (let ((scaches (mapcar (lambda (_) (nl-llm-scache-new nsink win dim heads kvh)) blocks)) (mr 0.0) (q 0))
      (while (< q len)
        (setq mr (max mr (gs--maxrel (nth q gpu) (nl-llm-stream-step (aref toks q) blocks scaches wte lnfg bh dim) vocab)))
        (setq q (1+ q)))
      (gs--ck "cap<len: GPU streaming == CPU streaming oracle" (< mr 5e-3) (format "maxrel=%.2e (cap=%d len=%d)" mr cap len))))
  (princ (format "NL-LLM-GPU-STREAM %s (%d failures)\n" (if (= gs--fail 0) "ALL-PASS" "HAS-FAILURES") gs--fail))
  (kill-emacs (if (= gs--fail 0) 0 1)))
;;; gpu-stream-test.el ends here
