;;; gpu-block-test.el --- on-device training of the full dense block  -*- lexical-binding: t; -*-
;; Trains the full modern dense block (RMSNorm + GQA/RoPE + SwiGLU) + an LM head
;; with cross-entropy, fully on-device via the resident-autograd builder, and
;; checks the loss trajectory matches the CPU autograd reference
;; (nl-llm-ag-block).  Skips (exit 0) without a Vulkan device.
;;   emacs -Q --batch -L lisp -L ../nelisp-photon/lisp -l test/gpu-block-test.el
(add-to-list 'load-path (expand-file-name "lisp"))
(add-to-list 'load-path (expand-file-name "../nelisp-photon/lisp"))
(require 'cl-lib)
(require 'photon-tensor)
(require 'photon-autograd)
(require 'nl-llm-autograd)
(require 'nl-llm-gpu)
(require 'nl-llm-gpu-ag)

(defvar gb--fail 0)
(defun gb--ck (name ok &optional extra)
  (princ (format "%-46s %s  %s\n" name
                 (if ok "PASS" (progn (setq gb--fail (1+ gb--fail)) "FAIL")) (or extra ""))))
(defun gb--vec (n seed sc)
  (let ((v (make-vector n 0.0)) (i 0))
    (while (< i n)
      (aset v i (* sc 2.0 (- (/ (float (mod (+ (* (1+ i) 2654435761) (* (1+ seed) 40503)) 65536))
                                65536.0) 0.5))) (setq i (1+ i))) v))
(defun gb--t (shape seed sc) (let ((n 1)) (dolist (d shape) (setq n (* n d)))
                               (photon-tensor shape (gb--vec n seed sc))))
(defun gb--ones (n) (photon-tensor (list n) (make-vector n 1.0)))
(defun gb--cp (tn) (photon-tensor (photon-tensor-shape tn) (copy-sequence (photon-tensor-data tn))))
(defun gb--ce (ld seq vocab targets)
  (let ((loss 0.0) (i 0))
    (while (< i seq)
      (let ((base (* i vocab)) (mx -1.0e30) (j 0))
        (while (< j vocab) (when (> (aref ld (+ base j)) mx) (setq mx (aref ld (+ base j)))) (setq j (1+ j)))
        (let ((s 0.0) (j2 0))
          (while (< j2 vocab) (setq s (+ s (exp (- (aref ld (+ base j2)) mx)))) (setq j2 (1+ j2)))
          (setq loss (- loss (- (- (aref ld (+ base (aref targets i))) mx) (log s))))))
      (setq i (1+ i)))
    (/ loss (float seq))))

(unless (nl-llm-gpu-enable)
  (princ "NL-LLM-GPU-BLOCK SKIP (no GPU server / Vulkan device)\n") (kill-emacs 0))

(let* ((seq 6) (dim 16) (heads 4) (kvh 2) (ff 32) (vocab 12) (hd (/ dim heads))
       (kvdim (* kvh hd)) (lr 0.05) (steps 6) (sc 0.4) (scl (/ 1.0 (sqrt (float hd))))
       (targets (vector 1 2 3 4 5 6))
       ;; base weights (shared init)
       (x (gb--t (list seq dim) 1 sc))
       (ln1g (gb--ones dim)) (Wq (gb--t (list dim dim) 2 sc)) (bq (gb--t (list dim) 12 0.0))
       (Wk (gb--t (list kvdim dim) 3 sc)) (bk (gb--t (list kvdim) 13 0.0))
       (Wv (gb--t (list kvdim dim) 4 sc)) (bv (gb--t (list kvdim) 14 0.0))
       (Wo (gb--t (list dim dim) 5 sc)) (bo (gb--t (list dim) 15 0.0)) (ln2g (gb--ones dim))
       (Wg (gb--t (list ff dim) 6 sc)) (bg (gb--t (list ff) 16 0.0))
       (Wu (gb--t (list ff dim) 7 sc)) (bu (gb--t (list ff) 17 0.0))
       (Wd (gb--t (list dim ff) 8 sc)) (bd (gb--t (list dim) 18 0.0)) (lnfg (gb--ones dim))
       (Wh (gb--t (list vocab dim) 9 sc)) (bh (gb--t (list vocab) 19 0.0))
       (tables (nl-llm-gpu-rope-tables seq hd))
       (onehot (let ((v (make-vector (* seq vocab) 0.0)) (i 0))
                 (while (< i seq) (aset v (+ (* i vocab) (aref targets i)) 1.0) (setq i (1+ i)))
                 (photon-tensor (list seq vocab) v)))
       (mask (let ((md (make-vector (* seq seq) 0.0)) (i 0))
               (while (< i seq) (let ((j (1+ i))) (while (< j seq) (aset md (+ (* i seq) j) -1.0e30) (setq j (1+ j)))) (setq i (1+ i)))
               (photon-tensor (list seq seq) md)))
       (gpu-losses nil) (cpu-losses nil))
  ;; ---- GPU: resident-autograd builder ----
  (let* ((b (nlga-new))
         (xr (nlga-const b (gb--cp x)))
         (blk (list :ln1g (nlga-param b (gb--cp ln1g))
                    :wq (nlga-param b (gb--cp Wq)) :bq (nlga-param b (gb--cp bq))
                    :wk (nlga-param b (gb--cp Wk)) :bk (nlga-param b (gb--cp bk))
                    :wv (nlga-param b (gb--cp Wv)) :bv (nlga-param b (gb--cp bv))
                    :wo (nlga-param b (gb--cp Wo)) :bo (nlga-param b (gb--cp bo))
                    :ln2g (nlga-param b (gb--cp ln2g))
                    :wg (nlga-param b (gb--cp Wg)) :bg (nlga-param b (gb--cp bg))
                    :wu (nlga-param b (gb--cp Wu)) :bu (nlga-param b (gb--cp bu))
                    :wd (nlga-param b (gb--cp Wd)) :bd (nlga-param b (gb--cp bd))))
         (lnfgr (nlga-param b (gb--cp lnfg)))
         (whr (nlga-param b (gb--cp Wh))) (bhr (nlga-param b (gb--cp bh)))
         (cosr (nlga-const b (car tables))) (sinr (nlga-const b (cdr tables)))
         (sposr (nlga-scalar b 1.0)) (snegr (nlga-scalar b -1.0))
         (sclr (nlga-scalar b scl)) (oner (nlga-scalar b 1.0))
         (maskr (nlga-const b mask)) (ohr (nlga-const b onehot)) (lrr (nlga-scalar b lr))
         (x2 (nlga-block b xr blk heads kvh cosr sinr sposr snegr sclr maskr))
         (xf (nlga-rmsnorm b x2 lnfgr))
         (logits (nlga-linear b xf whr bhr))
         (lout (nlga-keep b logits oner)))
    (nlga-seed-ce b logits ohr)
    (nlga-finish b lrr) (nlga-compile b)   ; exercise the compiled (re-submit) path
    (let ((s 0))
      (while (< s steps)
        (let ((ld (nth lout (nlga-step b))))
          (push (gb--ce ld seq vocab targets) gpu-losses))
        (setq s (1+ s))))
    (nlga-free b))
  (setq gpu-losses (nreverse gpu-losses))
  (nl-llm-gpu-disable)   ; restore CPU backend BEFORE the reference (else it runs
                         ; on the GPU backend with stale resident weights)
  ;; ---- CPU autograd reference ----
  (let* ((xc (photon-autograd-const (gb--cp x)))
         (blk (list :ln1g (photon-autograd-const (gb--cp ln1g))
                    :wq (photon-autograd-const (gb--cp Wq)) :bq (photon-autograd-const (gb--cp bq))
                    :wk (photon-autograd-const (gb--cp Wk)) :bk (photon-autograd-const (gb--cp bk))
                    :wv (photon-autograd-const (gb--cp Wv)) :bv (photon-autograd-const (gb--cp bv))
                    :wo (photon-autograd-const (gb--cp Wo)) :bo (photon-autograd-const (gb--cp bo))
                    :ln2g (photon-autograd-const (gb--cp ln2g))
                    :wg (photon-autograd-const (gb--cp Wg)) :bg (photon-autograd-const (gb--cp bg))
                    :wu (photon-autograd-const (gb--cp Wu)) :bu (photon-autograd-const (gb--cp bu))
                    :wd (photon-autograd-const (gb--cp Wd)) :bd (photon-autograd-const (gb--cp bd))))
         (lnfgc (photon-autograd-const (gb--cp lnfg)))
         (whc (photon-autograd-const (gb--cp Wh))) (bhc (photon-autograd-const (gb--cp bh)))
         (params (append (list (plist-get blk :ln1g) (plist-get blk :wq) (plist-get blk :bq)
                               (plist-get blk :wk) (plist-get blk :bk) (plist-get blk :wv) (plist-get blk :bv)
                               (plist-get blk :wo) (plist-get blk :bo) (plist-get blk :ln2g)
                               (plist-get blk :wg) (plist-get blk :bg) (plist-get blk :wu) (plist-get blk :bu)
                               (plist-get blk :wd) (plist-get blk :bd))
                         (list lnfgc whc bhc)))
         (s 0))
    (while (< s steps)
      (photon-autograd-reset-tape)
      (let* ((x2 (nl-llm-ag-block xc blk heads kvh))
             (xf (nl-llm-ag-rmsnorm x2 lnfgc))
             (logits (photon-autograd-linear xf whc bhc))
             (loss (photon-autograd-softmax-ce logits targets)))
        (push (aref (photon-tensor-data (pav-value loss)) 0) cpu-losses)
        (photon-autograd-zero-grad params)
        (photon-autograd-backward loss)
        (photon-autograd-sgd params lr))
      (setq s (1+ s)))
    (setq cpu-losses (nreverse cpu-losses)))
  (let ((maxrel 0.0) (i 0))
    (while (< i steps)
      (setq maxrel (max maxrel (/ (abs (- (nth i gpu-losses) (nth i cpu-losses)))
                                  (max 1e-4 (abs (nth i cpu-losses))))))
      (setq i (1+ i)))
    (gb--ck "block forward GPU == CPU (step 0)"
            (< (/ (abs (- (car gpu-losses) (car cpu-losses))) (abs (car cpu-losses))) 2e-2)
            (format "gpu=%.4f cpu=%.4f" (car gpu-losses) (car cpu-losses)))
    (gb--ck "block training GPU == CPU (trajectory)" (< maxrel 1e-1) (format "maxrel=%.2e" maxrel)))
  (gb--ck "block trains on GPU (loss down)"
          (< (car (last gpu-losses)) (car gpu-losses))
          (format "loss %.4f -> %.4f" (car gpu-losses) (car (last gpu-losses))))
  (princ (format "GPU: %s\nCPU: %s\n"
                 (mapcar (lambda (l) (/ (round (* l 1000)) 1000.0)) gpu-losses)
                 (mapcar (lambda (l) (/ (round (* l 1000)) 1000.0)) cpu-losses)))
  (princ (format "NL-LLM-GPU-BLOCK %s (%d failures)\n"
                 (if (= gb--fail 0) "ALL-PASS" "HAS-FAILURES") gb--fail))
  (kill-emacs (if (= gb--fail 0) 0 1)))
;;; gpu-block-test.el ends here
