;;; gpu-window-test.el --- on-device training over multiple windows  -*- lexical-binding: t; -*-
;; Trains a model on a sequence of sliding windows on-device: the batch is
;; compiled ONCE and re-submitted each window, with only the (resident) one-hot
;; token/target inputs refreshed per window via nlga-update.  Checks the loss
;; trajectory matches the CPU autograd reference.  Skips (exit 0) without a GPU.
;;   emacs -Q --batch -L lisp -L ../nelisp-photon/lisp -l test/gpu-window-test.el
(add-to-list 'load-path (expand-file-name "lisp"))
(add-to-list 'load-path (expand-file-name "../nelisp-photon/lisp"))
(require 'cl-lib)
(require 'photon-tensor)
(require 'photon-autograd)
(require 'nl-llm-autograd)
(require 'nl-llm-gpu)
(require 'nl-llm-gpu-ag)

(defvar gw--fail 0)
(defun gw--ck (name ok &optional extra)
  (princ (format "%-46s %s  %s\n" name
                 (if ok "PASS" (progn (setq gw--fail (1+ gw--fail)) "FAIL")) (or extra ""))))
(defun gw--t (shape seed sc) (let ((n 1)) (dolist (d shape) (setq n (* n d)))
  (photon-tensor shape (let ((v (make-vector n 0.0)) (i 0))
    (while (< i n) (aset v i (* sc 2.0 (- (/ (float (mod (+ (* (1+ i) 2654435761) (* (1+ seed) 40503)) 65536)) 65536.0) 0.5))) (setq i (1+ i))) v))))
(defun gw--ones (n) (photon-tensor (list n) (make-vector n 1.0)))
(defun gw--zeros (sh) (let ((n 1)) (dolist (d sh) (setq n (* n d))) (photon-tensor sh (make-vector n 0.0))))
(defun gw--cp (tn) (photon-tensor (photon-tensor-shape tn) (copy-sequence (photon-tensor-data tn))))
(defun gw--oh (idxs seq vocab) ; one-hot (seq x vocab) from an index vector
  (let ((v (make-vector (* seq vocab) 0.0))) (dotimes (i seq) (aset v (+ (* i vocab) (aref idxs i)) 1.0)) (photon-tensor (list seq vocab) v)))
(defun gw--win (ids w seq) (let ((v (make-vector seq 0))) (dotimes (i seq) (aset v i (aref ids (+ w i)))) v))
(defun gw--ce (ld seq vocab tg) (let ((loss 0.0) (i 0))
  (while (< i seq) (let ((base (* i vocab)) (mx -1.0e30) (j 0))
    (while (< j vocab) (when (> (aref ld (+ base j)) mx) (setq mx (aref ld (+ base j)))) (setq j (1+ j)))
    (let ((s 0.0) (j2 0)) (while (< j2 vocab) (setq s (+ s (exp (- (aref ld (+ base j2)) mx)))) (setq j2 (1+ j2)))
      (setq loss (- loss (- (- (aref ld (+ base (aref tg i))) mx) (log s)))))) (setq i (1+ i))) (/ loss (float seq))))

(unless (nl-llm-gpu-enable)
  (princ "NL-LLM-GPU-WINDOW SKIP (no GPU server / Vulkan device)\n") (kill-emacs 0))

(let* ((seq 6) (dim 16) (heads 4) (kvh 2) (ff 24) (vocab 12) (hd (/ dim heads)) (kvdim (* kvh hd))
       (lr 0.1) (nwin 5) (sc 0.4) (scl (/ 1.0 (sqrt (float hd))))
       (ids (vector 0 1 2 3 4 5 6 7 8 9 10 11 0 2 4 6 8 10 1 3 5))   ; >= nwin+seq
       (wte (gw--t (list vocab dim) 1 sc))
       (blk0 (list :ln1g (gw--ones dim) :wq (gw--t (list dim dim) 2 sc) :bq (gw--zeros (list dim))
                   :wk (gw--t (list kvdim dim) 3 sc) :bk (gw--zeros (list kvdim))
                   :wv (gw--t (list kvdim dim) 4 sc) :bv (gw--zeros (list kvdim))
                   :wo (gw--t (list dim dim) 5 sc) :bo (gw--zeros (list dim)) :ln2g (gw--ones dim)
                   :wg (gw--t (list ff dim) 6 sc) :bg (gw--zeros (list ff))
                   :wu (gw--t (list ff dim) 7 sc) :bu (gw--zeros (list ff))
                   :wd (gw--t (list dim ff) 8 sc) :bd (gw--zeros (list dim))))
       (lnfg (gw--ones dim)) (Wh (gw--t (list vocab dim) 9 sc)) (bh (gw--zeros (list vocab)))
       (tables (nl-llm-gpu-rope-tables seq hd))
       (mask (let ((md (make-vector (* seq seq) 0.0)) (i 0)) (while (< i seq) (let ((j (1+ i))) (while (< j seq) (aset md (+ (* i seq) j) -1.0e30) (setq j (1+ j)))) (setq i (1+ i))) (photon-tensor (list seq seq) md)))
       (gpu-losses nil) (cpu-losses nil))
  ;; ---- GPU: compile once, slide windows by refreshing the one-hot inputs ----
  (let* ((b (nlga-new)) (wb (lambda (bt) (let ((o nil) (kv bt)) (while kv (push (car kv) o) (push (nlga-param b (gw--cp (cadr kv))) o) (setq kv (cddr kv))) (nreverse o))))
         (oh (nlga-const b (gw--oh (gw--win ids 0 seq) seq vocab)))
         (ohtgt (nlga-const b (gw--oh (gw--win ids 1 seq) seq vocab)))
         (wter (nlga-param b (gw--cp wte))) (g0 (funcall wb blk0))
         (lnfgr (nlga-param b (gw--cp lnfg))) (whr (nlga-param b (gw--cp Wh))) (bhr (nlga-param b (gw--cp bh)))
         (cosr (nlga-const b (car tables))) (sinr (nlga-const b (cdr tables)))
         (sposr (nlga-scalar b 1.0)) (snegr (nlga-scalar b -1.0)) (sclr (nlga-scalar b scl)) (oner (nlga-scalar b 1.0))
         (maskr (nlga-const b mask)) (lrr (nlga-scalar b lr))
         (logits (nlga-model b oh wter (list g0) lnfgr whr bhr heads kvh cosr sinr sposr snegr sclr maskr))
         (lout (nlga-keep b logits oner)))
    (nlga-seed-ce b logits ohtgt) (nlga-finish b lrr) (nlga-compile b)
    (let ((w 0)) (while (< w nwin)
      (let ((tg (gw--win ids (1+ w) seq)))
        (nlga-update oh (gw--oh (gw--win ids w seq) seq vocab))
        (nlga-update ohtgt (gw--oh tg seq vocab))
        (push (gw--ce (nth lout (nlga-step b)) seq vocab tg) gpu-losses))
      (setq w (1+ w))))
    (nlga-free b))
  (setq gpu-losses (nreverse gpu-losses))
  (nl-llm-gpu-disable)
  ;; ---- CPU autograd reference over the same windows ----
  (let* ((P (lambda (tn) (photon-autograd-const (gw--cp tn))))
         (wtep (funcall P wte)) (c0 (let ((o nil) (kv blk0)) (while kv (push (car kv) o) (push (funcall P (cadr kv)) o) (setq kv (cddr kv))) (nreverse o)))
         (lnfgc (funcall P lnfg)) (whc (funcall P Wh)) (bhc (funcall P bh))
         (params (append (list wtep) (let ((o nil) (kv c0)) (while kv (push (cadr kv) o) (setq kv (cddr kv))) (nreverse o)) (list lnfgc whc bhc)))
         (w 0))
    (while (< w nwin)
      (let ((tg (gw--win ids (1+ w) seq)))
        (photon-autograd-reset-tape)
        (let* ((x (photon-autograd-matmul (photon-autograd-const (gw--oh (gw--win ids w seq) seq vocab)) wtep))
               (x (nl-llm-ag-block x c0 heads kvh))
               (xf (nl-llm-ag-rmsnorm x lnfgc))
               (logits (photon-autograd-linear xf whc bhc))
               (loss (photon-autograd-softmax-ce logits tg)))
          (push (aref (photon-tensor-data (pav-value loss)) 0) cpu-losses)
          (photon-autograd-zero-grad params) (photon-autograd-backward loss) (photon-autograd-sgd params lr)))
      (setq w (1+ w)))
    (setq cpu-losses (nreverse cpu-losses)))
  (let ((maxrel 0.0) (i 0))
    (while (< i nwin)
      (setq maxrel (max maxrel (/ (abs (- (nth i gpu-losses) (nth i cpu-losses))) (max 1e-4 (abs (nth i cpu-losses))))))
      (setq i (1+ i)))
    (gw--ck "multi-window training GPU == CPU" (< maxrel 1e-1) (format "maxrel=%.2e" maxrel)))
  (gw--ck "multi-window training decreases loss" (< (car (last gpu-losses)) (car gpu-losses))
          (format "loss %.4f -> %.4f" (car gpu-losses) (car (last gpu-losses))))
  (princ (format "GPU: %s\nCPU: %s\n"
                 (mapcar (lambda (l) (/ (round (* l 1000)) 1000.0)) gpu-losses)
                 (mapcar (lambda (l) (/ (round (* l 1000)) 1000.0)) cpu-losses)))
  (princ (format "NL-LLM-GPU-WINDOW %s (%d failures)\n" (if (= gw--fail 0) "ALL-PASS" "HAS-FAILURES") gw--fail))
  (kill-emacs (if (= gw--fail 0) 0 1)))
;;; gpu-window-test.el ends here
