;;; gpu-lora-test.el --- resident-autograd LoRA correctness  -*- lexical-binding: t; -*-
;; Validates LoRA on the resident-autograd builder with a frozen base weight:
;; identity at zero-up init, forward agreement with a CPU merged-weight
;; reference, real GPU training with only A/B trainable, and round-trip
;; readback of the trained adapter.  Skips (exit 0) without a Vulkan device.
;;   emacs -Q --batch -L lisp -L ../nelisp-photon/lisp -l test/gpu-lora-test.el
(add-to-list 'load-path (expand-file-name "lisp"))
(add-to-list 'load-path (expand-file-name "../nelisp-photon/lisp"))
(require 'cl-lib)
(require 'photon-tensor)
(require 'nl-llm-gpu)
(require 'nl-llm-gpu-ag)
(require 'nl-llm-lora-gpu)

(defvar glo--fail 0)
(defun glo--ck (name ok &optional extra)
  (princ (format "%-46s %s  %s\n" name
                 (if ok "PASS" (progn (setq glo--fail (1+ glo--fail)) "FAIL")) (or extra ""))))
(defun glo--vec (n seed sc)
  (let ((v (make-vector n 0.0)) (i 0))
    (while (< i n)
      (aset v i (* sc 2.0 (- (/ (float (mod (+ (* (1+ i) 2654435761) (* (1+ seed) 40503)) 65536))
                                65536.0) 0.5)))
      (setq i (1+ i)))
    v))
(defun glo--t (shape seed sc) (let ((n 1)) (dolist (d shape) (setq n (* n d)))
                                (photon-tensor shape (glo--vec n seed sc))))
(defun glo--copy (tn) (photon-tensor (photon-tensor-shape tn) (copy-sequence (photon-tensor-data tn))))

(defun glo--lora (in out rank alpha a-seed a-sc b-seed b-sc)
  (list :a (glo--t (list rank in) a-seed a-sc)
        :b (glo--t (list out rank) b-seed b-sc)
        :rank rank :alpha alpha :in in :out out))

(defun glo--copy-lora (lora)
  (list :a (glo--copy (plist-get lora :a))
        :b (glo--copy (plist-get lora :b))
        :rank (plist-get lora :rank)
        :alpha (plist-get lora :alpha)
        :in (plist-get lora :in)
        :out (plist-get lora :out)))

(defun glo--lora-scale (lora)
  (/ (float (plist-get lora :alpha)) (float (plist-get lora :rank))))

(defun glo--merge-lora (w lora)
  (photon-tensor-add
   w
   (photon-tensor-scale
    (photon-tensor-matmul (plist-get lora :b) (plist-get lora :a))
    (glo--lora-scale lora))))

(defun glo--max-abs-diff (a b)
  (let ((n (length a)) (mx 0.0) (i 0))
    (while (< i n)
      (setq mx (max mx (abs (- (aref a i) (aref b i)))))
      (setq i (1+ i)))
    mx))

(defun glo--max-rel-diff (got ref)
  (let ((n (length got)) (mx 0.0) (i 0))
    (while (< i n)
      (setq mx (max mx (/ (abs (- (aref got i) (aref ref i)))
                          (max 1.0e-4 (abs (aref ref i))))))
      (setq i (1+ i)))
    mx))

(defun glo--half-mse (got ref)
  (let ((n (length got)) (inv (/ 1.0 (float (length got)))) (acc 0.0) (i 0))
    (while (< i n)
      (let ((d (- (aref got i) (aref ref i))))
        (setq acc (+ acc (* d d))))
      (setq i (1+ i)))
    (* 0.5 inv acc)))

(defun glo--count-rises (xs)
  (let ((rest xs) (rises 0))
    (while (cdr rest)
      (when (> (cadr rest) (+ (car rest) 1.0e-8))
        (setq rises (1+ rises)))
      (setq rest (cdr rest)))
    rises))

(defun glo--vec-exact-p (a b)
  (let ((n (length a)) (ok t) (i 0))
    (while (and ok (< i n))
      (unless (= (aref a i) (aref b i))
        (setq ok nil))
      (setq i (1+ i)))
    ok))

(unless (file-writable-p temporary-file-directory)
  (setq temporary-file-directory (file-name-as-directory "/tmp"))
  (setenv "TMPDIR" temporary-file-directory))

(unless (nl-llm-gpu-enable)
  (princ "NL-LLM-GPU-LORA SKIP (no GPU server / Vulkan device)\n") (kill-emacs 0))

(let (id-maxabs ref-maxrel rt-maxrel)
  ;; ---- Test 1: zero-up init is identity ----
  (let* ((seq 5) (in 4) (out 3) (rank 2)
         (x (glo--t (list seq in) 1 0.35))
         (w (glo--t (list out in) 2 0.25))
         (bias (glo--t (list out) 3 0.10))
         (lora (glo--lora in out rank 6.0 4 0.20 5 0.0))
         (b (nlga-new))
         (xr (nlga-const b (glo--copy x)))
         (wr (nlga-const b (glo--copy w)))
         (br (nlga-const b (glo--copy bias)))
         (lora-rts (nl-llm-lora-gpu-attach b (glo--copy-lora lora) nil))
         (one (nlga-scalar b 1.0))
         (plain-out (nlga-keep b (nlga-linear b xr wr br) one))
         (lora-out (nlga-keep b (nlga-lora-linear b xr wr br lora-rts) one))
         (outs (nlga-step b)))
    (setq id-maxabs (glo--max-abs-diff (nth plain-out outs) (nth lora-out outs)))
    (glo--ck "LoRA init B=0 matches plain linear"
             (< id-maxabs 1.0e-5)
             (format "maxabs=%.3e" id-maxabs))
    (nlga-free b))

  ;; ---- Test 2: non-zero LoRA forward matches CPU merged-weight math ----
  (let* ((seq 6) (in 5) (out 4) (rank 3)
         (x (glo--t (list seq in) 11 0.30))
         (w (glo--t (list out in) 12 0.22))
         (bias (glo--t (list out) 13 0.08))
         (lora (glo--lora in out rank 9.0 14 0.16 15 0.12))
         (b (nlga-new))
         (xr (nlga-const b (glo--copy x)))
         (wr (nlga-const b (glo--copy w)))
         (br (nlga-const b (glo--copy bias)))
         (lora-rts (nl-llm-lora-gpu-attach b (glo--copy-lora lora) nil))
         (one (nlga-scalar b 1.0))
         (y-idx (nlga-keep b (nlga-lora-linear b xr wr br lora-rts) one))
         (gpu-y (nth y-idx (nlga-step b))))
    (nlga-free b)
    (nl-llm-gpu-disable)
    (let* ((merged (glo--merge-lora w lora))
           (cpu-y (photon-tensor-linear x merged bias)))
      (setq ref-maxrel (glo--max-rel-diff gpu-y (photon-tensor-data cpu-y)))
      (glo--ck "LoRA forward matches CPU merged weight"
               (< ref-maxrel 1.0e-4)
               (format "maxrel=%.3e" ref-maxrel))))

  ;; ---- Prepare the frozen-base training case on the CPU backend ----
  (let* ((seq 6) (in 5) (out 4) (rank 2)
         (steps 28) (lr 0.20) (alpha 8.0)
         (ntot (* seq out)) (invn (/ 1.0 (float ntot)))
         (x (glo--t (list seq in) 21 0.36))
         (w-base (glo--t (list out in) 22 0.12))
         (w-base0 (glo--copy w-base))
         (bias (glo--t (list out) 23 0.05))
         (train-lora (glo--lora in out rank alpha 24 0.30 25 0.0))
         (target-lora (glo--copy-lora train-lora))
         (target-b (glo--t (list out rank) 26 0.40))
         (target nil)
         (target-data nil)
         (train-losses nil)
         (eval-loss 0.0)
         (rises 0)
         (w-before nil)
         (w-readback nil)
         (eval-y nil))
    (setf (plist-get target-lora :b) target-b)
    (setq target (photon-tensor-linear x (glo--merge-lora w-base target-lora) bias))
    (setq target-data (photon-tensor-data target))
    (unless (nl-llm-gpu-enable)
      (error "gpu-lora-test: GPU server did not restart for training"))
    ;; ---- Test 3/4: train only the adapter, keep the base frozen ----
    (let* ((b (nlga-new))
           (xr (nlga-const b (glo--copy x)))
           (wr (nlga-const b (glo--copy w-base)))
           (br (nlga-const b (glo--copy bias)))
           (adapter (glo--copy-lora train-lora))
           (lora-rts (nl-llm-lora-gpu-attach b adapter))
           (tr (nlga-const b (glo--copy target)))
           (invr (nlga-scalar b invn))
           (lrr (nlga-scalar b lr))
           (one (nlga-scalar b 1.0))
           (y (nlga-lora-linear b xr wr br lora-rts))
           (y-idx (nlga-keep b y one))
           (params (nl-llm-lora-gpu-params lora-rts))
           (s 0))
      (glo--ck "LoRA params order is explicit"
               (and (eq (car params) (plist-get lora-rts :a))
                    (eq (cadr params) (plist-get lora-rts :b)))
               "")
      (nlga-seed-mse b y tr invr)
      (nlga-finish b lrr)
      (nlga-compile b)
      (setq w-before (nelisp-gpu-server-read-resident (nlga-rt-handle wr) (* out in)))
      (while (< s steps)
        (let ((yv (nth y-idx (nlga-step b))))
          (push (glo--half-mse yv target-data) train-losses))
        (setq s (1+ s)))
      (setq train-losses (nreverse train-losses))
      (setq rises (glo--count-rises train-losses))
      (nlga-update lrr (photon-tensor '(1) (vector 0.0)))
      (setq eval-y (nth y-idx (nlga-step b)))
      (setq eval-loss (glo--half-mse eval-y target-data))
      (setq w-readback (nelisp-gpu-server-read-resident (nlga-rt-handle wr) (* out in)))
      (nl-llm-lora-gpu-pull lora-rts adapter)
      (nlga-free b)
      (glo--ck "LoRA frozen-base training lowers MSE"
               (and (< eval-loss (* 0.30 (car train-losses))) (<= rises 4))
               (format "loss %.4f -> %.4f, rises=%d"
                       (car train-losses) eval-loss rises))
      (glo--ck "LoRA base weight stays frozen"
               (glo--vec-exact-p w-readback w-before)
               "readback exact")
      (nl-llm-gpu-disable)
      (let* ((merged (glo--merge-lora w-base adapter))
             (cpu-y (photon-tensor-linear x merged bias)))
        (setq rt-maxrel (glo--max-rel-diff eval-y (photon-tensor-data cpu-y)))
        (glo--ck "LoRA trained adapter round-trips"
                 (< rt-maxrel 1.0e-4)
                 (format "maxrel=%.3e" rt-maxrel)))))
  (ignore-errors (nl-llm-gpu-disable))
  (princ (format "NL-LLM-GPU-LORA %s (%d failures)\n"
                 (if (= glo--fail 0) "ALL-PASS" "HAS-FAILURES") glo--fail))
  (kill-emacs (if (= glo--fail 0) 0 1)))
;;; gpu-lora-test.el ends here
