;;; gpu-tie-test.el --- weight-tied embedding/head training, on-device  -*- lexical-binding: t; -*-
;; Trains a model whose LM head shares the embedding matrix (head = wte^T) on
;; device, and checks it matches a CPU autograd reference that also ties wte.
;; This exercises the gwritten fan-out path: wte's gradient is accumulated from
;; BOTH the embedding (gather) backward and the head (linear) backward.
;; Skips (exit 0) without a Vulkan device.
;;   emacs -Q --batch -L lisp -L ../nelisp-photon/lisp -l test/gpu-tie-test.el
(add-to-list 'load-path (expand-file-name "lisp"))
(add-to-list 'load-path (expand-file-name "../nelisp-photon/lisp"))
(require 'cl-lib)
(require 'photon-tensor)
(require 'photon-autograd)
(require 'nl-llm-autograd)
(require 'nl-llm-gpu)
(require 'nl-llm-gpu-ag)

(defvar gt--fail 0)
(defun gt--ck (name ok &optional extra)
  (princ (format "%-46s %s  %s\n" name
                 (if ok "PASS" (progn (setq gt--fail (1+ gt--fail)) "FAIL")) (or extra ""))))
(defun gt--t (shape seed sc) (let ((n 1)) (dolist (d shape) (setq n (* n d)))
  (photon-tensor shape (let ((v (make-vector n 0.0)) (i 0))
    (while (< i n) (aset v i (* sc 2.0 (- (/ (float (mod (+ (* (1+ i) 2654435761) (* (1+ seed) 40503)) 65536)) 65536.0) 0.5))) (setq i (1+ i))) v))))
(defun gt--ones (n) (photon-tensor (list n) (make-vector n 1.0)))
(defun gt--zeros (sh) (let ((n 1)) (dolist (d sh) (setq n (* n d))) (photon-tensor sh (make-vector n 0.0))))
(defun gt--cp (tn) (photon-tensor (photon-tensor-shape tn) (copy-sequence (photon-tensor-data tn))))
(defun gt--ce (ld seq vocab tg) (let ((loss 0.0) (i 0))
  (while (< i seq) (let ((base (* i vocab)) (mx -1.0e30) (j 0))
    (while (< j vocab) (when (> (aref ld (+ base j)) mx) (setq mx (aref ld (+ base j)))) (setq j (1+ j)))
    (let ((s 0.0) (j2 0)) (while (< j2 vocab) (setq s (+ s (exp (- (aref ld (+ base j2)) mx)))) (setq j2 (1+ j2)))
      (setq loss (- loss (- (- (aref ld (+ base (aref tg i))) mx) (log s)))))) (setq i (1+ i))) (/ loss (float seq))))

(unless (nl-llm-gpu-enable)
  (princ "NL-LLM-GPU-TIE SKIP (no GPU server / Vulkan device)\n") (kill-emacs 0))

(let* ((seq 6) (dim 16) (heads 4) (kvh 2) (ff 24) (vocab 12) (hd (/ dim heads)) (kvdim (* kvh hd))
       (lr 0.1) (steps 6) (sc 0.4) (scl (/ 1.0 (sqrt (float hd))))
       (tokens (vector 0 1 2 3 4 5)) (targets (vector 1 2 3 4 5 6))
       (toklist (append tokens nil))
       (wte (gt--t (list vocab dim) 1 sc)) (bh (gt--zeros (list vocab)))
       (blk0 (list :ln1g (gt--ones dim) :wq (gt--t (list dim dim) 2 sc) :bq (gt--zeros (list dim))
                   :wk (gt--t (list kvdim dim) 3 sc) :bk (gt--zeros (list kvdim))
                   :wv (gt--t (list kvdim dim) 4 sc) :bv (gt--zeros (list kvdim))
                   :wo (gt--t (list dim dim) 5 sc) :bo (gt--zeros (list dim)) :ln2g (gt--ones dim)
                   :wg (gt--t (list ff dim) 6 sc) :bg (gt--zeros (list ff))
                   :wu (gt--t (list ff dim) 7 sc) :bu (gt--zeros (list ff))
                   :wd (gt--t (list dim ff) 8 sc) :bd (gt--zeros (list dim))))
       (lnfg (gt--ones dim))
       (tables (nl-llm-gpu-rope-tables seq hd))
       (idxt (photon-tensor (list seq) (let ((v (make-vector seq 0.0))) (dotimes (i seq) (aset v i (float (aref tokens i)))) v)))
       (tgtt (photon-tensor (list seq) (let ((v (make-vector seq 0.0))) (dotimes (i seq) (aset v i (float (aref targets i)))) v)))
       (mask (let ((md (make-vector (* seq seq) 0.0)) (i 0)) (while (< i seq) (let ((j (1+ i))) (while (< j seq) (aset md (+ (* i seq) j) -1.0e30) (setq j (1+ j)))) (setq i (1+ i))) (photon-tensor (list seq seq) md)))
       (gpu-losses nil) (cpu-losses nil))
  ;; ---- GPU: tied head (gather embed + linear with the SAME wte) ----
  (let* ((b (nlga-new)) (wb (lambda (bt) (let ((o nil) (kv bt)) (while kv (push (car kv) o) (push (nlga-param b (gt--cp (cadr kv))) o) (setq kv (cddr kv))) (nreverse o))))
         (tok (nlga-const b (gt--cp idxt))) (tgt (nlga-const b (gt--cp tgtt)))
         (wter (nlga-param b (gt--cp wte))) (bhr (nlga-param b (gt--cp bh))) (g0 (funcall wb blk0))
         (lnfgr (nlga-param b (gt--cp lnfg)))
         (cosr (nlga-const b (car tables))) (sinr (nlga-const b (cdr tables)))
         (sposr (nlga-scalar b 1.0)) (snegr (nlga-scalar b -1.0)) (sclr (nlga-scalar b scl)) (oner (nlga-scalar b 1.0))
         (maskr (nlga-const b mask)) (lrr (nlga-scalar b lr))
         (x (nlga-embed b tok wter))
         (x (nlga-block b x g0 heads kvh cosr sinr sposr snegr sclr maskr))
         (xf (nlga-rmsnorm b x lnfgr))
         (logits (nlga-linear b xf wter bhr))
         (lout (nlga-keep b logits oner)))
    (nlga-seed-ce-idx b logits tgt) (nlga-finish b lrr) (nlga-compile b)
    (let ((s 0)) (while (< s steps) (push (gt--ce (nth lout (nlga-step b)) seq vocab targets) gpu-losses) (setq s (1+ s))))
    (nlga-free b))
  (setq gpu-losses (nreverse gpu-losses))
  (nl-llm-gpu-disable)
  ;; ---- CPU autograd reference (same wte for embed + head) ----
  (let* ((P (lambda (tn) (photon-autograd-const (gt--cp tn))))
         (wtep (funcall P wte)) (bhc (funcall P bh))
         (c0 (let ((o nil) (kv blk0)) (while kv (push (car kv) o) (push (funcall P (cadr kv)) o) (setq kv (cddr kv))) (nreverse o)))
         (lnfgc (funcall P lnfg))
         (params (append (list wtep bhc) (let ((o nil) (kv c0)) (while kv (push (cadr kv) o) (setq kv (cddr kv))) (nreverse o)) (list lnfgc)))
         (s 0))
    (while (< s steps)
      (photon-autograd-reset-tape)
      (let* ((x (photon-autograd-embedding wtep toklist dim))
             (x (nl-llm-ag-block x c0 heads kvh))
             (xf (nl-llm-ag-rmsnorm x lnfgc))
             (logits (photon-autograd-linear xf wtep bhc))     ; TIED
             (loss (photon-autograd-softmax-ce logits targets)))
        (push (aref (photon-tensor-data (pav-value loss)) 0) cpu-losses)
        (photon-autograd-zero-grad params) (photon-autograd-backward loss) (photon-autograd-sgd params lr))
      (setq s (1+ s)))
    (setq cpu-losses (nreverse cpu-losses)))
  (let ((maxrel 0.0) (i 0))
    (while (< i steps)
      (setq maxrel (max maxrel (/ (abs (- (nth i gpu-losses) (nth i cpu-losses))) (max 1e-4 (abs (nth i cpu-losses))))))
      (setq i (1+ i)))
    (gt--ck "tied embed/head training GPU == CPU" (< maxrel 1e-1) (format "maxrel=%.2e" maxrel)))
  (gt--ck "tied model trains on GPU (loss down)" (< (car (last gpu-losses)) (car gpu-losses))
          (format "loss %.4f -> %.4f" (car gpu-losses) (car (last gpu-losses))))
  (princ (format "GPU: %s\nCPU: %s\n"
                 (mapcar (lambda (l) (/ (round (* l 1000)) 1000.0)) gpu-losses)
                 (mapcar (lambda (l) (/ (round (* l 1000)) 1000.0)) cpu-losses)))
  (princ (format "NL-LLM-GPU-TIE %s (%d failures)\n" (if (= gt--fail 0) "ALL-PASS" "HAS-FAILURES") gt--fail))
  (kill-emacs (if (= gt--fail 0) 0 1)))
;;; gpu-tie-test.el ends here
