;;; gpu-stack-test.el --- on-device training of a multi-block stacked model  -*- lexical-binding: t; -*-
;; Trains a 2-block model (block 0 dense SwiGLU, block 1 top-k MoE) with a
;; trainable embedding (one-hot @ wte) and LM head, fully on-device via the
;; resident-autograd builder, and checks the loss trajectory matches the CPU
;; autograd reference to f32 precision.  Skips (exit 0) without a Vulkan device.
;;   emacs -Q --batch -L lisp -L ../nelisp-photon/lisp -l test/gpu-stack-test.el
(add-to-list 'load-path (expand-file-name "lisp"))
(add-to-list 'load-path (expand-file-name "../nelisp-photon/lisp"))
(require 'cl-lib)
(require 'photon-tensor)
(require 'photon-autograd)
(require 'nl-llm-autograd)
(require 'nl-llm-gpu)
(require 'nl-llm-gpu-ag)

(defvar gs--fail 0)
(defun gs--ck (name ok &optional extra)
  (princ (format "%-46s %s  %s\n" name
                 (if ok "PASS" (progn (setq gs--fail (1+ gs--fail)) "FAIL")) (or extra ""))))
(defun gs--t (shape seed sc) (let ((n 1)) (dolist (d shape) (setq n (* n d)))
  (photon-tensor shape (let ((v (make-vector n 0.0)) (i 0))
    (while (< i n) (aset v i (* sc 2.0 (- (/ (float (mod (+ (* (1+ i) 2654435761) (* (1+ seed) 40503)) 65536)) 65536.0) 0.5))) (setq i (1+ i))) v))))
(defun gs--ones (n) (photon-tensor (list n) (make-vector n 1.0)))
(defun gs--cp (tn) (photon-tensor (photon-tensor-shape tn) (copy-sequence (photon-tensor-data tn))))
(defun gs--ce (ld seq vocab tg) (let ((loss 0.0) (i 0))
  (while (< i seq) (let ((base (* i vocab)) (mx -1.0e30) (j 0))
    (while (< j vocab) (when (> (aref ld (+ base j)) mx) (setq mx (aref ld (+ base j)))) (setq j (1+ j)))
    (let ((s 0.0) (j2 0)) (while (< j2 vocab) (setq s (+ s (exp (- (aref ld (+ base j2)) mx)))) (setq j2 (1+ j2)))
      (setq loss (- loss (- (- (aref ld (+ base (aref tg i))) mx) (log s)))))) (setq i (1+ i))) (/ loss (float seq))))
;; wrap a block-of-tensors plist into a block-of-(rt|pav) plist via WRAP
(defun gs--wrap (bt wrap)
  (let ((out nil) (kv bt)) (while kv (let ((k (car kv)) (v (cadr kv)))
    (push k out)
    (push (cond ((eq k :experts) (mapcar (lambda (ex) (gs--wrap ex wrap)) v))
                ((eq k :top-k) v) (t (funcall wrap v))) out)) (setq kv (cddr kv))) (nreverse out)))
(defun gs--pavs (blk)  ; collect all pav leaves of a wrapped block (for CPU sgd)
  (let ((out nil) (kv blk)) (while kv (let ((k (car kv)) (v (cadr kv)))
    (cond ((eq k :experts) (dolist (ex v) (setq out (append out (gs--pavs ex)))))
          ((eq k :top-k) nil) (t (push v out)))) (setq kv (cddr kv))) (nreverse out)))

(unless (nl-llm-gpu-enable)
  (princ "NL-LLM-GPU-STACK SKIP (no GPU server / Vulkan device)\n") (kill-emacs 0))

(let* ((seq 6) (dim 16) (heads 4) (kvh 2) (ff 24) (vocab 12) (ne 3) (topk 2)
       (hd (/ dim heads)) (kvdim (* kvh hd)) (lr 0.05) (steps 5) (sc 0.4)
       (scl (/ 1.0 (sqrt (float hd)))) (tokens (vector 0 1 2 3 4 5)) (targets (vector 1 2 3 4 5 6))
       (wte (gs--t (list vocab dim) 1 sc))
       ;; block 0: dense SwiGLU
       (blk0 (list :ln1g (gs--ones dim) :wq (gs--t (list dim dim) 2 sc) :bq (gs--t (list dim) 12 0.0)
                   :wk (gs--t (list kvdim dim) 3 sc) :bk (gs--t (list kvdim) 13 0.0)
                   :wv (gs--t (list kvdim dim) 4 sc) :bv (gs--t (list kvdim) 14 0.0)
                   :wo (gs--t (list dim dim) 5 sc) :bo (gs--t (list dim) 15 0.0) :ln2g (gs--ones dim)
                   :wg (gs--t (list ff dim) 6 sc) :bg (gs--t (list ff) 16 0.0)
                   :wu (gs--t (list ff dim) 7 sc) :bu (gs--t (list ff) 17 0.0)
                   :wd (gs--t (list dim ff) 8 sc) :bd (gs--t (list dim) 18 0.0)))
       ;; block 1: MoE
       (blk1 (list :ln1g (gs--ones dim) :wq (gs--t (list dim dim) 22 sc) :bq (gs--t (list dim) 32 0.0)
                   :wk (gs--t (list kvdim dim) 23 sc) :bk (gs--t (list kvdim) 33 0.0)
                   :wv (gs--t (list kvdim dim) 24 sc) :bv (gs--t (list kvdim) 34 0.0)
                   :wo (gs--t (list dim dim) 25 sc) :bo (gs--t (list dim) 35 0.0) :ln2g (gs--ones dim)
                   :router (gs--t (list ne dim) 40 sc) :brouter (gs--t (list ne) 41 0.0)
                   :experts (let ((l nil) (e 0)) (while (< e ne)
                     (push (list :wg (gs--t (list ff dim) (+ 50 (* e 6)) sc) :bg (gs--t (list ff) (+ 51 (* e 6)) 0.0)
                                 :wu (gs--t (list ff dim) (+ 52 (* e 6)) sc) :bu (gs--t (list ff) (+ 53 (* e 6)) 0.0)
                                 :wd (gs--t (list dim ff) (+ 54 (* e 6)) sc) :bd (gs--t (list dim) (+ 55 (* e 6)) 0.0)) l)
                     (setq e (1+ e))) (nreverse l)) :top-k topk))
       (lnfg (gs--ones dim)) (Wh (gs--t (list vocab dim) 9 sc)) (bh (gs--t (list vocab) 19 0.0))
       (tables (nl-llm-gpu-rope-tables seq hd))
       (oh-tok (let ((v (make-vector (* seq vocab) 0.0)) (i 0)) (while (< i seq) (aset v (+ (* i vocab) (aref tokens i)) 1.0) (setq i (1+ i))) (photon-tensor (list seq vocab) v)))
       (oh-tgt (let ((v (make-vector (* seq vocab) 0.0)) (i 0)) (while (< i seq) (aset v (+ (* i vocab) (aref targets i)) 1.0) (setq i (1+ i))) (photon-tensor (list seq vocab) v)))
       (mask (let ((md (make-vector (* seq seq) 0.0)) (i 0)) (while (< i seq) (let ((j (1+ i))) (while (< j seq) (aset md (+ (* i seq) j) -1.0e30) (setq j (1+ j)))) (setq i (1+ i))) (photon-tensor (list seq seq) md)))
       (gpu-losses nil) (cpu-losses nil))
  ;; ---- GPU: 2-block stacked model on-device ----
  (let* ((b (nlga-new)) (wrap (lambda (tn) (nlga-param b (gs--cp tn))))
         (oh (nlga-const b (gs--cp oh-tok))) (wter (nlga-param b (gs--cp wte)))
         (g0 (gs--wrap blk0 wrap)) (g1 (gs--wrap blk1 wrap))
         (lnfgr (nlga-param b (gs--cp lnfg))) (whr (nlga-param b (gs--cp Wh))) (bhr (nlga-param b (gs--cp bh)))
         (cosr (nlga-const b (car tables))) (sinr (nlga-const b (cdr tables)))
         (sposr (nlga-scalar b 1.0)) (snegr (nlga-scalar b -1.0)) (sclr (nlga-scalar b scl)) (oner (nlga-scalar b 1.0))
         (maskr (nlga-const b mask)) (ohtgt (nlga-const b oh-tgt)) (lrr (nlga-scalar b lr))
         (logits (nlga-model b oh wter (list g0 g1) lnfgr whr bhr heads kvh cosr sinr sposr snegr sclr maskr))
         (lout (nlga-keep b logits oner)))
    (nlga-seed-ce b logits ohtgt) (nlga-finish b lrr) (nlga-compile b)
    (let ((s 0)) (while (< s steps) (push (gs--ce (nth lout (nlga-step b)) seq vocab targets) gpu-losses) (setq s (1+ s))))
    (nlga-free b))
  (setq gpu-losses (nreverse gpu-losses))
  (nl-llm-gpu-disable)
  ;; ---- CPU autograd reference ----
  (let* ((P (lambda (tn) (photon-autograd-const (gs--cp tn))))
         (ohp (funcall P oh-tok)) (wtep (funcall P wte))
         (c0 (gs--wrap blk0 P)) (c1 (gs--wrap blk1 P))
         (lnfgc (funcall P lnfg)) (whc (funcall P Wh)) (bhc (funcall P bh))
         (params (append (list wtep) (gs--pavs c0) (gs--pavs c1) (list lnfgc whc bhc))) (s 0))
    (while (< s steps)
      (photon-autograd-reset-tape)
      (let* ((x (photon-autograd-matmul ohp wtep))
             (x (nl-llm-ag-block x c0 heads kvh))
             (x (nl-llm-ag-block x c1 heads kvh))
             (xf (nl-llm-ag-rmsnorm x lnfgc))
             (logits (photon-autograd-linear xf whc bhc))
             (loss (photon-autograd-softmax-ce logits targets)))
        (push (aref (photon-tensor-data (pav-value loss)) 0) cpu-losses)
        (photon-autograd-zero-grad params) (photon-autograd-backward loss) (photon-autograd-sgd params lr))
      (setq s (1+ s)))
    (setq cpu-losses (nreverse cpu-losses)))
  (let ((maxrel 0.0) (i 0))
    (while (< i steps)
      (setq maxrel (max maxrel (/ (abs (- (nth i gpu-losses) (nth i cpu-losses))) (max 1e-4 (abs (nth i cpu-losses))))))
      (setq i (1+ i)))
    (gs--ck "stacked model forward GPU == CPU (step 0)"
            (< (/ (abs (- (car gpu-losses) (car cpu-losses))) (abs (car cpu-losses))) 2e-2)
            (format "gpu=%.4f cpu=%.4f" (car gpu-losses) (car cpu-losses)))
    (gs--ck "stacked model training GPU == CPU" (< maxrel 1e-1) (format "maxrel=%.2e" maxrel)))
  (gs--ck "stacked model trains on GPU (loss down)" (< (car (last gpu-losses)) (car gpu-losses))
          (format "loss %.4f -> %.4f" (car gpu-losses) (car (last gpu-losses))))
  (princ (format "GPU: %s\nCPU: %s\n"
                 (mapcar (lambda (l) (/ (round (* l 1000)) 1000.0)) gpu-losses)
                 (mapcar (lambda (l) (/ (round (* l 1000)) 1000.0)) cpu-losses)))
  (princ (format "NL-LLM-GPU-STACK %s (%d failures)\n" (if (= gs--fail 0) "ALL-PASS" "HAS-FAILURES") gs--fail))
  (kill-emacs (if (= gs--fail 0) 0 1)))
;;; gpu-stack-test.el ends here
