;;; gpu-decode-test.el --- on-GPU KV-cache decode == CPU decode  -*- lexical-binding: t; -*-
;; Checks the on-GPU incremental decoder (nl-llm-gpu-decode) produces the same
;; per-position logits as the CPU KV-cache decode (nl-llm-decode, itself verified
;; == prefill).  Skips (exit 0) without a Vulkan device.
;;   emacs -Q --batch -L lisp -L ../nelisp-photon/lisp -l test/gpu-decode-test.el
(add-to-list 'load-path (expand-file-name "lisp"))
(add-to-list 'load-path (expand-file-name "../nelisp-photon/lisp"))
(require 'cl-lib)
(require 'photon-tensor)
(require 'nl-llm-decode)
(require 'nl-llm-gpu)
(require 'nl-llm-gpu-ag)
(require 'nl-llm-gpu-decode)

(defvar gx--fail 0)
(defun gx--ck (name ok &optional extra)
  (princ (format "%-44s %s  %s\n" name (if ok "PASS" (progn (setq gx--fail (1+ gx--fail)) "FAIL")) (or extra ""))))
(defun gx--t (shape seed sc) (let ((n 1)) (dolist (d shape) (setq n (* n d)))
  (photon-tensor shape (let ((v (make-vector n 0.0)) (i 0))
    (while (< i n) (aset v i (* sc 2.0 (- (/ (float (mod (+ (* (1+ i) 2654435761) (* (1+ seed) 40503)) 65536)) 65536.0) 0.5))) (setq i (1+ i))) v))))
(defun gx--ones (n) (photon-tensor (list n) (make-vector n 1.0)))

(unless (nl-llm-gpu-enable)
  (princ "NL-LLM-GPU-DECODE SKIP (no GPU server / Vulkan device)\n") (kill-emacs 0))

(let* ((seq 8) (dim 16) (heads 4) (kvh 2) (ff 24) (vocab 12) (hd (/ dim heads)) (kvdim (* kvh hd))
       (sc 0.4) (tokens (vector 0 3 1 4 2 5 3 6))
       (wte (gx--t (list vocab dim) 1 sc)) (lnfg (gx--ones dim)) (bh (gx--t (list vocab) 19 0.1))
       (mkblk (lambda (s0) (list :ln1g (gx--ones dim) :wq (gx--t (list dim dim) (+ s0 1) sc) :bq (gx--t (list dim) (+ s0 11) 0.1)
                                 :wk (gx--t (list kvdim dim) (+ s0 2) sc) :bk (gx--t (list kvdim) (+ s0 12) 0.1)
                                 :wv (gx--t (list kvdim dim) (+ s0 3) sc) :bv (gx--t (list kvdim) (+ s0 13) 0.1)
                                 :wo (gx--t (list dim dim) (+ s0 4) sc) :bo (gx--t (list dim) (+ s0 14) 0.1) :ln2g (gx--ones dim)
                                 :wg (gx--t (list ff dim) (+ s0 5) sc) :bg (gx--t (list ff) (+ s0 15) 0.1)
                                 :wu (gx--t (list ff dim) (+ s0 6) sc) :bu (gx--t (list ff) (+ s0 16) 0.1)
                                 :wd (gx--t (list dim ff) (+ s0 7) sc) :bd (gx--t (list dim) (+ s0 17) 0.1))))
       (blocks (list (funcall mkblk 100) (funcall mkblk 200)))
       (tables (nl-llm-gpu-rope-tables seq hd))
       (gpu-logits nil) (cpu-logits nil))
  ;; GPU decode
  (let ((ctx (nl-llm-gpu-decode-new wte blocks lnfg bh heads kvh dim vocab seq tables)) (p 0))
    (while (< p seq)
      (push (copy-sequence (nl-llm-gpu-decode-step ctx (aref tokens p) p)) gpu-logits)
      (setq p (1+ p)))
    (nl-llm-gpu-decode-free ctx))
  (setq gpu-logits (nreverse gpu-logits))
  (nl-llm-gpu-disable)
  ;; CPU decode (verified == prefill in decode-test)
  (let ((caches (mapcar (lambda (_) (nl-llm-dcache-new seq dim heads kvh)) blocks)) (p 0))
    (while (< p seq)
      (push (copy-sequence (nl-llm-decode-step (aref tokens p) blocks caches wte lnfg bh dim)) cpu-logits)
      (setq p (1+ p)))
    (setq cpu-logits (nreverse cpu-logits)))
  (let ((maxrel 0.0) (p 0))
    (while (< p seq)
      (let ((g (nth p gpu-logits)) (c (nth p cpu-logits)) (j 0))
        (while (< j vocab) (setq maxrel (max maxrel (/ (abs (- (aref g j) (aref c j))) (max 1e-3 (abs (aref c j)))))) (setq j (1+ j))))
      (setq p (1+ p)))
    (gx--ck "GPU decode == CPU decode (all positions)" (< maxrel 5e-3) (format "maxrel=%.2e" maxrel)))
  (princ (format "NL-LLM-GPU-DECODE %s (%d failures)\n" (if (= gx--fail 0) "ALL-PASS" "HAS-FAILURES") gx--fail))
  (kill-emacs (if (= gx--fail 0) 0 1)))
;;; gpu-decode-test.el ends here
