;;; gpu-clip-test.el --- on-device global-norm gradient clipping  -*- lexical-binding: t; -*-
;; Trains a block on-device with SGD + global-norm gradient clipping and checks
;; the loss trajectory matches a CPU reference that clips the same way, and that
;; the clip actually engages (grad norm > threshold).  Skips without a GPU.
;;   emacs -Q --batch -L lisp -L ../nelisp-photon/lisp -l test/gpu-clip-test.el
(add-to-list 'load-path (expand-file-name "lisp"))
(add-to-list 'load-path (expand-file-name "../nelisp-photon/lisp"))
(require 'cl-lib)
(require 'photon-tensor)
(require 'photon-autograd)
(require 'nl-llm-autograd)
(require 'nl-llm-gpu)
(require 'nl-llm-gpu-ag)

(defvar gc--fail 0)
(defun gc--ck (name ok &optional extra)
  (princ (format "%-46s %s  %s\n" name (if ok "PASS" (progn (setq gc--fail (1+ gc--fail)) "FAIL")) (or extra ""))))
(defun gc--t (shape seed sc) (let ((n 1)) (dolist (d shape) (setq n (* n d)))
  (photon-tensor shape (let ((v (make-vector n 0.0)) (i 0))
    (while (< i n) (aset v i (* sc 2.0 (- (/ (float (mod (+ (* (1+ i) 2654435761) (* (1+ seed) 40503)) 65536)) 65536.0) 0.5))) (setq i (1+ i))) v))))
(defun gc--ones (n) (photon-tensor (list n) (make-vector n 1.0)))
(defun gc--zeros (sh) (let ((n 1)) (dolist (d sh) (setq n (* n d))) (photon-tensor sh (make-vector n 0.0))))
(defun gc--cp (tn) (photon-tensor (photon-tensor-shape tn) (copy-sequence (photon-tensor-data tn))))
(defun gc--ce (ld seq vocab tg) (let ((loss 0.0) (i 0))
  (while (< i seq) (let ((base (* i vocab)) (mx -1.0e30) (j 0))
    (while (< j vocab) (when (> (aref ld (+ base j)) mx) (setq mx (aref ld (+ base j)))) (setq j (1+ j)))
    (let ((s 0.0) (j2 0)) (while (< j2 vocab) (setq s (+ s (exp (- (aref ld (+ base j2)) mx)))) (setq j2 (1+ j2)))
      (setq loss (- loss (- (- (aref ld (+ base (aref tg i))) mx) (log s)))))) (setq i (1+ i))) (/ loss (float seq))))
(defun gc--gnorm (params) (let ((ss 0.0)) (dolist (p params) (let ((g (photon-tensor-data (pav-grad p))) (i 0)) (while (< i (length g)) (setq ss (+ ss (* (aref g i) (aref g i)))) (setq i (1+ i))))) (sqrt ss)))

(unless (nl-llm-gpu-enable)
  (princ "NL-LLM-GPU-CLIP SKIP (no GPU server / Vulkan device)\n") (kill-emacs 0))

(let* ((seq 6) (dim 16) (heads 4) (kvh 2) (ff 24) (vocab 12) (hd (/ dim heads)) (kvdim (* kvh hd))
       (lr 0.2) (clip 0.2) (steps 6) (sc 0.4) (scl (/ 1.0 (sqrt (float hd)))) (targets (vector 1 2 3 4 5 6))
       (x (gc--t (list seq dim) 1 sc))
       (blk0 (list :ln1g (gc--ones dim) :wq (gc--t (list dim dim) 2 sc) :bq (gc--zeros (list dim))
                   :wk (gc--t (list kvdim dim) 3 sc) :bk (gc--zeros (list kvdim))
                   :wv (gc--t (list kvdim dim) 4 sc) :bv (gc--zeros (list kvdim))
                   :wo (gc--t (list dim dim) 5 sc) :bo (gc--zeros (list dim)) :ln2g (gc--ones dim)
                   :wg (gc--t (list ff dim) 6 sc) :bg (gc--zeros (list ff))
                   :wu (gc--t (list ff dim) 7 sc) :bu (gc--zeros (list ff))
                   :wd (gc--t (list dim ff) 8 sc) :bd (gc--zeros (list dim))))
       (lnfg (gc--ones dim)) (Wh (gc--t (list vocab dim) 9 sc)) (bh (gc--zeros (list vocab)))
       (tables (nl-llm-gpu-rope-tables seq hd))
       (onehot (let ((v (make-vector (* seq vocab) 0.0)) (i 0)) (while (< i seq) (aset v (+ (* i vocab) (aref targets i)) 1.0) (setq i (1+ i))) (photon-tensor (list seq vocab) v)))
       (mask (let ((md (make-vector (* seq seq) 0.0)) (i 0)) (while (< i seq) (let ((j (1+ i))) (while (< j seq) (aset md (+ (* i seq) j) -1.0e30) (setq j (1+ j)))) (setq i (1+ i))) (photon-tensor (list seq seq) md)))
       (gpu-losses nil) (cpu-losses nil) (norm0 0.0))
  ;; ---- GPU: SGD + global-norm clip ----
  (let* ((b (nlga-new)) (wb (lambda (bt) (let ((o nil) (kv bt)) (while kv (push (car kv) o) (push (nlga-param b (gc--cp (cadr kv))) o) (setq kv (cddr kv))) (nreverse o))))
         (xr (nlga-const b (gc--cp x))) (g0 (funcall wb blk0))
         (lnfgr (nlga-param b (gc--cp lnfg))) (whr (nlga-param b (gc--cp Wh))) (bhr (nlga-param b (gc--cp bh)))
         (cosr (nlga-const b (car tables))) (sinr (nlga-const b (cdr tables)))
         (sposr (nlga-scalar b 1.0)) (snegr (nlga-scalar b -1.0)) (sclr (nlga-scalar b scl)) (oner (nlga-scalar b 1.0))
         (maskr (nlga-const b mask)) (ohr (nlga-const b onehot)) (lrr (nlga-scalar b lr))
         (x2 (nlga-block b xr g0 heads kvh cosr sinr sposr snegr sclr maskr))
         (xf (nlga-rmsnorm b x2 lnfgr)) (logits (nlga-linear b xf whr bhr)) (lout (nlga-keep b logits oner)))
    (nlga-seed-ce b logits ohr) (nlga-finish b lrr clip) (nlga-compile b)
    (let ((s 0)) (while (< s steps) (push (gc--ce (nth lout (nlga-step b)) seq vocab targets) gpu-losses) (setq s (1+ s))))
    (nlga-free b))
  (setq gpu-losses (nreverse gpu-losses))
  (nl-llm-gpu-disable)
  ;; ---- CPU reference: SGD + global-norm clip ----
  (let* ((P (lambda (tn) (photon-autograd-const (gc--cp tn))))
         (xc (funcall P x)) (c0 (let ((o nil) (kv blk0)) (while kv (push (car kv) o) (push (funcall P (cadr kv)) o) (setq kv (cddr kv))) (nreverse o)))
         (lnfgc (funcall P lnfg)) (whc (funcall P Wh)) (bhc (funcall P bh))
         (params (append (let ((o nil) (kv c0)) (while kv (push (cadr kv) o) (setq kv (cddr kv))) (nreverse o)) (list lnfgc whc bhc)))
         (s 0))
    (while (< s steps)
      (photon-autograd-reset-tape)
      (let* ((x2 (nl-llm-ag-block xc c0 heads kvh)) (xf (nl-llm-ag-rmsnorm x2 lnfgc))
             (logits (photon-autograd-linear xf whc bhc)) (loss (photon-autograd-softmax-ce logits targets)))
        (push (aref (photon-tensor-data (pav-value loss)) 0) cpu-losses)
        (photon-autograd-zero-grad params) (photon-autograd-backward loss)
        (let* ((norm (gc--gnorm params)) (scale (min 1.0 (/ clip norm))))
          (when (= s 0) (setq norm0 norm))
          (dolist (p params)
            (let ((g (photon-tensor-data (pav-grad p))) (w (photon-tensor-data (pav-value p))) (i 0))
              (while (< i (length w)) (aset w i (- (aref w i) (* lr scale (aref g i)))) (setq i (1+ i)))))))
      (setq s (1+ s)))
    (setq cpu-losses (nreverse cpu-losses)))
  (let ((maxrel 0.0) (i 0))
    (while (< i steps)
      (setq maxrel (max maxrel (/ (abs (- (nth i gpu-losses) (nth i cpu-losses))) (max 1e-4 (abs (nth i cpu-losses))))))
      (setq i (1+ i)))
    (gc--ck "clipped SGD GPU == CPU" (< maxrel 1e-1) (format "maxrel=%.2e" maxrel)))
  (gc--ck "clip engaged (grad norm > threshold)" (> norm0 clip) (format "norm0=%.3f clip=%.2f" norm0 clip))
  (gc--ck "clipped training decreases loss" (< (car (last gpu-losses)) (car gpu-losses))
          (format "loss %.4f -> %.4f" (car gpu-losses) (car (last gpu-losses))))
  (princ (format "GPU: %s\nCPU: %s\n"
                 (mapcar (lambda (l) (/ (round (* l 1000)) 1000.0)) gpu-losses)
                 (mapcar (lambda (l) (/ (round (* l 1000)) 1000.0)) cpu-losses)))
  (princ (format "NL-LLM-GPU-CLIP %s (%d failures)\n" (if (= gc--fail 0) "ALL-PASS" "HAS-FAILURES") gc--fail))
  (kill-emacs (if (= gc--fail 0) 0 1)))
;;; gpu-clip-test.el ends here
