;;; gpu-train-test.el --- correctness of on-device (resident) training  -*- lexical-binding: t; -*-
;; Trains the same 2-layer MLP two ways from identical initial weights:
;;   - on the GPU, fully on-device (nl-llm-gpu-mlp-train)
;;   - on the CPU with photon-autograd (host reference)
;; and checks the per-step MSE loss trajectories agree (so the fused on-device
;; forward+backward+SGD is correct), and that the loss falls.  Skips (exit 0)
;; without a Vulkan device.
;;   emacs -Q --batch -L lisp -L ../nelisp-photon/lisp -l test/gpu-train-test.el
(add-to-list 'load-path (expand-file-name "lisp"))
(add-to-list 'load-path (expand-file-name "../nelisp-photon/lisp"))
(require 'cl-lib)
(require 'photon-tensor)
(require 'photon-autograd)
(require 'nl-llm-gpu)
(require 'nl-llm-gpu-train)

(defvar gt--fail 0)
(defun gt--ck (name ok &optional extra)
  (princ (format "%-46s %s  %s\n" name
                 (if ok "PASS" (progn (setq gt--fail (1+ gt--fail)) "FAIL")) (or extra ""))))
(defun gt--vec (n seed sc)
  (let ((v (make-vector n 0.0)) (i 0))
    (while (< i n)
      (aset v i (* sc 2.0 (- (/ (float (mod (+ (* (1+ i) 2654435761) (* (1+ seed) 40503)) 65536))
                                65536.0) 0.5)))
      (setq i (1+ i)))
    v))
(defun gt--t (shape seed sc) (let ((n 1)) (dolist (d shape) (setq n (* n d)))
                               (photon-tensor shape (gt--vec n seed sc))))
(defun gt--copy (tn) (photon-tensor (photon-tensor-shape tn)
                                    (copy-sequence (photon-tensor-data tn))))

(unless (nl-llm-gpu-enable)
  (princ "NL-LLM-GPU-TRAIN SKIP (no GPU server / Vulkan device)\n")
  (kill-emacs 0))

(let* ((seq 4) (in 6) (hid 8) (out 5) (lr 0.05) (steps 8)
       (ntot (* seq out)) (invn (/ 1.0 (float ntot))) (sc 0.4)
       (x  (gt--t (list seq in) 1 sc)) (target (gt--t (list seq out) 9 sc))
       (W1 (gt--t (list hid in) 2 sc)) (b1 (gt--t (list hid) 3 sc))
       (W2 (gt--t (list out hid) 4 sc)) (b2 (gt--t (list out) 5 sc))
       ;; GPU copies (mutated in place by the trainer)
       (gw1 (gt--copy W1)) (gb1 (gt--copy b1)) (gw2 (gt--copy W2)) (gb2 (gt--copy b2))
       (gpu-losses (nl-llm-gpu-mlp-train (gt--copy x) gw1 gb1 gw2 gb2 (gt--copy target) lr steps))
       ;; CPU reference with photon-autograd, identical init
       (xc  (photon-autograd-const (gt--copy x)))
       (w1c (photon-autograd-const (gt--copy W1))) (b1c (photon-autograd-const (gt--copy b1)))
       (w2c (photon-autograd-const (gt--copy W2))) (b2c (photon-autograd-const (gt--copy b2)))
       (params (list w1c b1c w2c b2c)) (td (photon-tensor-data target))
       (cpu-losses nil))
  (photon-tensor-use-cpu-backend)   ; reference must run on the CPU backend
  (let ((s 0))
    (while (< s steps)
      (photon-autograd-reset-tape)
      (let* ((y (photon-autograd-linear (photon-autograd-gelu (photon-autograd-linear xc w1c b1c))
                                        w2c b2c))
             (yd (photon-tensor-data (pav-value y))) (gd (photon-tensor-data (pav-grad y)))
             (loss 0.0) (i 0))
        (while (< i ntot)
          (let ((d (- (aref yd i) (aref td i))))
            (setq loss (+ loss (* d d))) (aset gd i (* d invn)))
          (setq i (1+ i)))
        (photon-autograd-zero-grad params)
        (dolist (v photon-autograd--tape) (when (pav-backward v) (funcall (pav-backward v) (pav-grad v))))
        (photon-autograd-sgd params lr)
        (push (* 0.5 invn loss) cpu-losses))
      (setq s (1+ s))))
  (setq cpu-losses (nreverse cpu-losses))
  (nl-llm-gpu-disable)
  ;; compare trajectories
  (let ((maxrel 0.0) (i 0))
    (while (< i steps)
      (let ((c (nth i cpu-losses)) (gp (nth i gpu-losses)))
        (setq maxrel (max maxrel (/ (abs (- gp c)) (max 1e-4 (abs c))))))
      (setq i (1+ i)))
    (gt--ck "on-device MLP loss == CPU autograd" (< maxrel 5e-2) (format "maxrel=%.2e" maxrel)))
  (gt--ck "on-device training decreases loss"
          (< (car (last gpu-losses)) (* 0.9 (car gpu-losses)))
          (format "loss %.4f -> %.4f" (car gpu-losses) (car (last gpu-losses))))
  (princ (format "GPU losses: %s\n" (mapcar (lambda (l) (/ (round (* l 10000)) 10000.0)) gpu-losses)))
  (princ (format "NL-LLM-GPU-TRAIN %s (%d failures)\n"
                 (if (= gt--fail 0) "ALL-PASS" "HAS-FAILURES") gt--fail))
  (kill-emacs (if (= gt--fail 0) 0 1)))
;;; gpu-train-test.el ends here
