;;; gpu-gather-test.el --- on-device gather embedding correctness  -*- lexical-binding: t; -*-
;; Trains a model with a GATHER embedding (token indices, not one-hot) and an
;; index-based CE loss over sliding windows on-device, and checks the loss
;; trajectory matches the CPU autograd reference (photon-autograd-embedding +
;; softmax-ce).  The per-window input is seq indices, not a seq x vocab one-hot.
;; Skips (exit 0) without a Vulkan device.
;;   emacs -Q --batch -L lisp -L ../nelisp-photon/lisp -l test/gpu-gather-test.el
(add-to-list 'load-path (expand-file-name "lisp"))
(add-to-list 'load-path (expand-file-name "../nelisp-photon/lisp"))
(require 'cl-lib)
(require 'photon-tensor)
(require 'photon-autograd)
(require 'nl-llm-autograd)
(require 'nl-llm-gpu)
(require 'nl-llm-gpu-ag)

(defvar gg--fail 0)
(defun gg--ck (name ok &optional extra)
  (princ (format "%-46s %s  %s\n" name
                 (if ok "PASS" (progn (setq gg--fail (1+ gg--fail)) "FAIL")) (or extra ""))))
(defun gg--t (shape seed sc) (let ((n 1)) (dolist (d shape) (setq n (* n d)))
  (photon-tensor shape (let ((v (make-vector n 0.0)) (i 0))
    (while (< i n) (aset v i (* sc 2.0 (- (/ (float (mod (+ (* (1+ i) 2654435761) (* (1+ seed) 40503)) 65536)) 65536.0) 0.5))) (setq i (1+ i))) v))))
(defun gg--ones (n) (photon-tensor (list n) (make-vector n 1.0)))
(defun gg--zeros (sh) (let ((n 1)) (dolist (d sh) (setq n (* n d))) (photon-tensor sh (make-vector n 0.0))))
(defun gg--cp (tn) (photon-tensor (photon-tensor-shape tn) (copy-sequence (photon-tensor-data tn))))
(defun gg--idx (ids start seq) (photon-tensor (list seq) (let ((v (make-vector seq 0.0))) (dotimes (i seq) (aset v i (float (aref ids (+ start i))))) v)))
(defun gg--toks (ids start seq) (let ((l nil)) (dotimes (i seq) (push (aref ids (+ start i)) l)) (nreverse l)))
(defun gg--win (ids w seq) (let ((v (make-vector seq 0))) (dotimes (i seq) (aset v i (aref ids (+ w i)))) v))
(defun gg--ce (ld seq vocab tg) (let ((loss 0.0) (i 0))
  (while (< i seq) (let ((base (* i vocab)) (mx -1.0e30) (j 0))
    (while (< j vocab) (when (> (aref ld (+ base j)) mx) (setq mx (aref ld (+ base j)))) (setq j (1+ j)))
    (let ((s 0.0) (j2 0)) (while (< j2 vocab) (setq s (+ s (exp (- (aref ld (+ base j2)) mx)))) (setq j2 (1+ j2)))
      (setq loss (- loss (- (- (aref ld (+ base (aref tg i))) mx) (log s)))))) (setq i (1+ i))) (/ loss (float seq))))

(unless (nl-llm-gpu-enable)
  (princ "NL-LLM-GPU-GATHER SKIP (no GPU server / Vulkan device)\n") (kill-emacs 0))

(let* ((seq 6) (dim 16) (heads 4) (kvh 2) (ff 24) (vocab 12) (hd (/ dim heads)) (kvdim (* kvh hd))
       (lr 0.1) (nwin 5) (sc 0.4) (scl (/ 1.0 (sqrt (float hd))))
       (ids (vector 0 1 2 3 4 5 6 7 8 9 10 11 0 2 4 6 8 10 1 3 5))
       (wte (gg--t (list vocab dim) 1 sc))
       (blk0 (list :ln1g (gg--ones dim) :wq (gg--t (list dim dim) 2 sc) :bq (gg--zeros (list dim))
                   :wk (gg--t (list kvdim dim) 3 sc) :bk (gg--zeros (list kvdim))
                   :wv (gg--t (list kvdim dim) 4 sc) :bv (gg--zeros (list kvdim))
                   :wo (gg--t (list dim dim) 5 sc) :bo (gg--zeros (list dim)) :ln2g (gg--ones dim)
                   :wg (gg--t (list ff dim) 6 sc) :bg (gg--zeros (list ff))
                   :wu (gg--t (list ff dim) 7 sc) :bu (gg--zeros (list ff))
                   :wd (gg--t (list dim ff) 8 sc) :bd (gg--zeros (list dim))))
       (lnfg (gg--ones dim)) (Wh (gg--t (list vocab dim) 9 sc)) (bh (gg--zeros (list vocab)))
       (tables (nl-llm-gpu-rope-tables seq hd))
       (mask (let ((md (make-vector (* seq seq) 0.0)) (i 0)) (while (< i seq) (let ((j (1+ i))) (while (< j seq) (aset md (+ (* i seq) j) -1.0e30) (setq j (1+ j)))) (setq i (1+ i))) (photon-tensor (list seq seq) md)))
       (gpu-losses nil) (cpu-losses nil))
  ;; ---- GPU: gather embedding + index CE, sliding windows ----
  (let* ((b (nlga-new)) (wb (lambda (bt) (let ((o nil) (kv bt)) (while kv (push (car kv) o) (push (nlga-param b (gg--cp (cadr kv))) o) (setq kv (cddr kv))) (nreverse o))))
         (tok (nlga-const b (gg--idx ids 0 seq))) (tgt (nlga-const b (gg--idx ids 1 seq)))
         (wter (nlga-param b (gg--cp wte))) (g0 (funcall wb blk0))
         (lnfgr (nlga-param b (gg--cp lnfg))) (whr (nlga-param b (gg--cp Wh))) (bhr (nlga-param b (gg--cp bh)))
         (cosr (nlga-const b (car tables))) (sinr (nlga-const b (cdr tables)))
         (sposr (nlga-scalar b 1.0)) (snegr (nlga-scalar b -1.0)) (sclr (nlga-scalar b scl)) (oner (nlga-scalar b 1.0))
         (maskr (nlga-const b mask)) (lrr (nlga-scalar b lr))
         (x (nlga-embed b tok wter))
         (x (nlga-block b x g0 heads kvh cosr sinr sposr snegr sclr maskr))
         (xf (nlga-rmsnorm b x lnfgr)) (logits (nlga-linear b xf whr bhr)) (lout (nlga-keep b logits oner)))
    (nlga-seed-ce-idx b logits tgt) (nlga-finish b lrr) (nlga-compile b)
    (let ((w 0)) (while (< w nwin)
      (let ((tg (gg--win ids (1+ w) seq)))
        (nlga-update tok (gg--idx ids w seq))
        (nlga-update tgt (gg--idx ids (1+ w) seq))
        (push (gg--ce (nth lout (nlga-step b)) seq vocab tg) gpu-losses))
      (setq w (1+ w))))
    (nlga-free b))
  (setq gpu-losses (nreverse gpu-losses))
  (nl-llm-gpu-disable)
  ;; ---- CPU autograd reference (photon-autograd-embedding) ----
  (let* ((P (lambda (tn) (photon-autograd-const (gg--cp tn))))
         (wtep (funcall P wte)) (c0 (let ((o nil) (kv blk0)) (while kv (push (car kv) o) (push (funcall P (cadr kv)) o) (setq kv (cddr kv))) (nreverse o)))
         (lnfgc (funcall P lnfg)) (whc (funcall P Wh)) (bhc (funcall P bh))
         (params (append (list wtep) (let ((o nil) (kv c0)) (while kv (push (cadr kv) o) (setq kv (cddr kv))) (nreverse o)) (list lnfgc whc bhc)))
         (w 0))
    (while (< w nwin)
      (let ((tg (gg--win ids (1+ w) seq)))
        (photon-autograd-reset-tape)
        (let* ((x (photon-autograd-embedding wtep (gg--toks ids w seq) dim))
               (x (nl-llm-ag-block x c0 heads kvh))
               (xf (nl-llm-ag-rmsnorm x lnfgc))
               (logits (photon-autograd-linear xf whc bhc))
               (loss (photon-autograd-softmax-ce logits tg)))
          (push (aref (photon-tensor-data (pav-value loss)) 0) cpu-losses)
          (photon-autograd-zero-grad params) (photon-autograd-backward loss) (photon-autograd-sgd params lr)))
      (setq w (1+ w)))
    (setq cpu-losses (nreverse cpu-losses)))
  (let ((maxrel 0.0) (i 0))
    (while (< i nwin)
      (setq maxrel (max maxrel (/ (abs (- (nth i gpu-losses) (nth i cpu-losses))) (max 1e-4 (abs (nth i cpu-losses))))))
      (setq i (1+ i)))
    (gg--ck "gather-embedding training GPU == CPU" (< maxrel 1e-1) (format "maxrel=%.2e" maxrel)))
  (gg--ck "gather-embedding training decreases loss" (< (car (last gpu-losses)) (car gpu-losses))
          (format "loss %.4f -> %.4f" (car gpu-losses) (car (last gpu-losses))))
  (princ (format "GPU: %s\nCPU: %s\n"
                 (mapcar (lambda (l) (/ (round (* l 1000)) 1000.0)) gpu-losses)
                 (mapcar (lambda (l) (/ (round (* l 1000)) 1000.0)) cpu-losses)))
  (princ (format "NL-LLM-GPU-GATHER %s (%d failures)\n" (if (= gg--fail 0) "ALL-PASS" "HAS-FAILURES") gg--fail))
  (kill-emacs (if (= gg--fail 0) 0 1)))
;;; gpu-gather-test.el ends here
