;;; gpu-resume-test.el --- seamless Adam resume (state checkpoint)  -*- lexical-binding: t; -*-
;; Checks that saving the Adam state (m/v) + step and resuming reproduces the
;; *continuous* training trajectory exactly: train 2K steps straight vs train K,
;; checkpoint weights+optimiser+step, reload, restore and train K more -- the
;; resumed losses must match the continuous run (f32-exact, since all resident
;; state round-trips through f32).  Skips without a GPU.
;;   emacs -Q --batch -L lisp -L ../nelisp-photon/lisp -l test/gpu-resume-test.el
(add-to-list 'load-path (expand-file-name "lisp"))
(add-to-list 'load-path (expand-file-name "../nelisp-photon/lisp"))
(require 'cl-lib)
(require 'photon-tensor)
(require 'nl-llm-gpu)
(require 'nl-llm-gpu-ag)

(defvar gr--fail 0)
(defun gr--ck (name ok &optional extra)
  (princ (format "%-46s %s  %s\n" name (if ok "PASS" (progn (setq gr--fail (1+ gr--fail)) "FAIL")) (or extra ""))))
(defun gr--t (shape seed sc) (let ((n 1)) (dolist (d shape) (setq n (* n d)))
  (photon-tensor shape (let ((v (make-vector n 0.0)) (i 0))
    (while (< i n) (aset v i (* sc 2.0 (- (/ (float (mod (+ (* (1+ i) 2654435761) (* (1+ seed) 40503)) 65536)) 65536.0) 0.5))) (setq i (1+ i))) v))))
(defun gr--ones (n) (photon-tensor (list n) (make-vector n 1.0)))
(defun gr--zeros (sh) (let ((n 1)) (dolist (d sh) (setq n (* n d))) (photon-tensor sh (make-vector n 0.0))))
(defun gr--cp (tn) (photon-tensor (photon-tensor-shape tn) (copy-sequence (photon-tensor-data tn))))
(defun gr--cpblk (blk) (let ((o nil) (kv blk)) (while kv (push (car kv) o) (push (gr--cp (cadr kv)) o) (setq kv (cddr kv))) (nreverse o)))
(defun gr--ce (ld seq vocab tg) (let ((loss 0.0) (i 0))
  (while (< i seq) (let ((base (* i vocab)) (mx -1.0e30) (j 0))
    (while (< j vocab) (when (> (aref ld (+ base j)) mx) (setq mx (aref ld (+ base j)))) (setq j (1+ j)))
    (let ((s 0.0) (j2 0)) (while (< j2 vocab) (setq s (+ s (exp (- (aref ld (+ base j2)) mx)))) (setq j2 (1+ j2)))
      (setq loss (- loss (- (- (aref ld (+ base (aref tg i))) mx) (log s)))))) (setq i (1+ i))) (/ loss (float seq))))

(unless (nl-llm-gpu-enable)
  (princ "NL-LLM-GPU-RESUME SKIP (no GPU server / Vulkan device)\n") (kill-emacs 0))

(let* ((seq 6) (dim 16) (heads 4) (kvh 2) (ff 24) (vocab 12) (hd (/ dim heads)) (kvdim (* kvh hd))
       (lr 0.02) (K 4) (total 8) (sc 0.4) (scl (/ 1.0 (sqrt (float hd)))) (targets (vector 1 2 3 4 5 6))
       (x (gr--t (list seq dim) 1 sc))
       (blk (list :ln1g (gr--ones dim) :wq (gr--t (list dim dim) 2 sc) :bq (gr--zeros (list dim))
                  :wk (gr--t (list kvdim dim) 3 sc) :bk (gr--zeros (list kvdim))
                  :wv (gr--t (list kvdim dim) 4 sc) :bv (gr--zeros (list kvdim))
                  :wo (gr--t (list dim dim) 5 sc) :bo (gr--zeros (list dim)) :ln2g (gr--ones dim)
                  :wg (gr--t (list ff dim) 6 sc) :bg (gr--zeros (list ff))
                  :wu (gr--t (list ff dim) 7 sc) :bu (gr--zeros (list ff))
                  :wd (gr--t (list dim ff) 8 sc) :bd (gr--zeros (list dim))))
       (lnfg (gr--ones dim)) (Wh (gr--t (list vocab dim) 9 sc)) (bh (gr--zeros (list vocab)))
       (tables (nl-llm-gpu-rope-tables seq hd))
       (onehot (let ((v (make-vector (* seq vocab) 0.0)) (i 0)) (while (< i seq) (aset v (+ (* i vocab) (aref targets i)) 1.0) (setq i (1+ i))) (photon-tensor (list seq vocab) v)))
       (mask (let ((md (make-vector (* seq seq) 0.0)) (i 0)) (while (< i seq) (let ((j (1+ i))) (while (< j seq) (aset md (+ (* i seq) j) -1.0e30) (setq j (1+ j)))) (setq i (1+ i))) (photon-tensor (list seq seq) md))))
  (cl-flet ((run (xw blkw lnfgw whw bhw t0 nsteps restore-opt)
              ;; train NSTEPS on the given (mutated-by-readback) weight tensors; return (:losses :opt)
              (let* ((b (nlga-new))
                     (wb (lambda (bt) (let ((o nil) (kv bt)) (while kv (push (car kv) o) (push (nlga-param b (cadr kv)) o) (setq kv (cddr kv))) (nreverse o))))
                     (xr (nlga-const b xw)) (g0 (funcall wb blkw))
                     (lnfgr (nlga-param b lnfgw)) (whr (nlga-param b whw)) (bhr (nlga-param b bhw))
                     (cosr (nlga-const b (car tables))) (sinr (nlga-const b (cdr tables)))
                     (sposr (nlga-scalar b 1.0)) (snegr (nlga-scalar b -1.0)) (sclr (nlga-scalar b scl)) (oner (nlga-scalar b 1.0))
                     (maskr (nlga-const b mask)) (ohr (nlga-const b onehot))
                     (x2 (nlga-block b xr g0 heads kvh cosr sinr sposr snegr sclr maskr))
                     (xf (nlga-rmsnorm b x2 lnfgr)) (logits (nlga-linear b xf whr bhr)) (lout (nlga-keep b logits oner))
                     (losses nil) (s 0))
                (nlga-seed-ce b logits ohr) (nlga-finish-adam b lr) (nlga-compile b)
                (when restore-opt (nlga-adam-restore b restore-opt))
                (while (< s nsteps)
                  (nlga-adam-update-t b (+ t0 s 1) lr)
                  (push (gr--ce (nth lout (nlga-step b)) seq vocab targets) losses)
                  (setq s (1+ s)))
                (let ((opt (nlga-adam-state b))) (nlga-readback b) (nlga-free b)
                  (list :losses (nreverse losses) :opt opt)))))
    ;; A: continuous 2K steps
    (let* ((aw-blk (gr--cpblk blk)) (aw-lnfg (gr--cp lnfg)) (aw-wh (gr--cp Wh)) (aw-bh (gr--cp bh))
           (lossesA (plist-get (run (gr--cp x) aw-blk aw-lnfg aw-wh aw-bh 0 total nil) :losses)))
      ;; B1: K steps, then checkpoint weights (readback) + adam state
      (let* ((bw-blk (gr--cpblk blk)) (bw-lnfg (gr--cp lnfg)) (bw-wh (gr--cp Wh)) (bw-bh (gr--cp bh))
             (r1 (run (gr--cp x) bw-blk bw-lnfg bw-wh bw-bh 0 K nil))   ; bw-* now hold weights@K
             (optK (plist-get r1 :opt))
             ;; B2: reload weights@K, restore Adam state, resume K..total
             (r2 (run (gr--cp x) (gr--cpblk bw-blk) (gr--cp bw-lnfg) (gr--cp bw-wh) (gr--cp bw-bh) K (- total K) optK))
             (lossesB (plist-get r2 :losses))
             (maxd 0.0) (i 0))
        (nl-llm-gpu-disable)
        (while (< i (- total K))
          (setq maxd (max maxd (abs (- (nth i lossesB) (nth (+ K i) lossesA)))))
          (setq i (1+ i)))
        (gr--ck "resumed losses == continuous losses" (< maxd 1e-4) (format "maxdiff=%.2e" maxd))
        (princ (format "continuous[K..]: %s\nresumed        : %s\n"
                       (mapcar (lambda (l) (/ (round (* l 1000)) 1000.0)) (nthcdr K lossesA))
                       (mapcar (lambda (l) (/ (round (* l 1000)) 1000.0)) lossesB))))))
  (princ (format "NL-LLM-GPU-RESUME %s (%d failures)\n" (if (= gr--fail 0) "ALL-PASS" "HAS-FAILURES") gr--fail))
  (kill-emacs (if (= gr--fail 0) 0 1)))
;;; gpu-resume-test.el ends here
