;;; gpu-sched-test.el --- LR-scheduled on-device training  -*- lexical-binding: t; -*-
;; Trains a block on-device with Adam under a warmup+cosine learning-rate
;; schedule (the scheduled base lr is fed to the resident hyperparameter buffer
;; each step), and checks the loss trajectory matches a CPU reference using the
;; same per-step lr.  Skips (exit 0) without a Vulkan device.
;;   emacs -Q --batch -L lisp -L ../nelisp-photon/lisp -l test/gpu-sched-test.el
(add-to-list 'load-path (expand-file-name "lisp"))
(add-to-list 'load-path (expand-file-name "../nelisp-photon/lisp"))
(require 'cl-lib)
(require 'photon-tensor)
(require 'photon-autograd)
(require 'nl-llm-autograd)
(require 'nl-llm-gpu)
(require 'nl-llm-gpu-ag)

(defvar gd--fail 0)
(defun gd--ck (name ok &optional extra)
  (princ (format "%-46s %s  %s\n" name
                 (if ok "PASS" (progn (setq gd--fail (1+ gd--fail)) "FAIL")) (or extra ""))))
(defun gd--t (shape seed sc) (let ((n 1)) (dolist (d shape) (setq n (* n d)))
  (photon-tensor shape (let ((v (make-vector n 0.0)) (i 0))
    (while (< i n) (aset v i (* sc 2.0 (- (/ (float (mod (+ (* (1+ i) 2654435761) (* (1+ seed) 40503)) 65536)) 65536.0) 0.5))) (setq i (1+ i))) v))))
(defun gd--ones (n) (photon-tensor (list n) (make-vector n 1.0)))
(defun gd--zeros (sh) (let ((n 1)) (dolist (d sh) (setq n (* n d))) (photon-tensor sh (make-vector n 0.0))))
(defun gd--cp (tn) (photon-tensor (photon-tensor-shape tn) (copy-sequence (photon-tensor-data tn))))
(defun gd--ce (ld seq vocab tg) (let ((loss 0.0) (i 0))
  (while (< i seq) (let ((base (* i vocab)) (mx -1.0e30) (j 0))
    (while (< j vocab) (when (> (aref ld (+ base j)) mx) (setq mx (aref ld (+ base j)))) (setq j (1+ j)))
    (let ((s 0.0) (j2 0)) (while (< j2 vocab) (setq s (+ s (exp (- (aref ld (+ base j2)) mx)))) (setq j2 (1+ j2)))
      (setq loss (- loss (- (- (aref ld (+ base (aref tg i))) mx) (log s)))))) (setq i (1+ i))) (/ loss (float seq))))

(unless (nl-llm-gpu-enable)
  (princ "NL-LLM-GPU-SCHED SKIP (no GPU server / Vulkan device)\n") (kill-emacs 0))

(let* ((seq 6) (dim 16) (heads 4) (kvh 2) (ff 24) (vocab 12) (hd (/ dim heads)) (kvdim (* kvh hd))
       (base 0.02) (warmup 2) (b1 0.9) (b2 0.999) (eps 1.0e-8) (steps 8) (minlr 0.002)
       (sc 0.4) (scl (/ 1.0 (sqrt (float hd)))) (targets (vector 1 2 3 4 5 6))
       (x (gd--t (list seq dim) 1 sc))
       (blk0 (list :ln1g (gd--ones dim) :wq (gd--t (list dim dim) 2 sc) :bq (gd--zeros (list dim))
                   :wk (gd--t (list kvdim dim) 3 sc) :bk (gd--zeros (list kvdim))
                   :wv (gd--t (list kvdim dim) 4 sc) :bv (gd--zeros (list kvdim))
                   :wo (gd--t (list dim dim) 5 sc) :bo (gd--zeros (list dim)) :ln2g (gd--ones dim)
                   :wg (gd--t (list ff dim) 6 sc) :bg (gd--zeros (list ff))
                   :wu (gd--t (list ff dim) 7 sc) :bu (gd--zeros (list ff))
                   :wd (gd--t (list dim ff) 8 sc) :bd (gd--zeros (list dim))))
       (lnfg (gd--ones dim)) (Wh (gd--t (list vocab dim) 9 sc)) (bh (gd--zeros (list vocab)))
       (tables (nl-llm-gpu-rope-tables seq hd))
       (onehot (let ((v (make-vector (* seq vocab) 0.0)) (i 0)) (while (< i seq) (aset v (+ (* i vocab) (aref targets i)) 1.0) (setq i (1+ i))) (photon-tensor (list seq vocab) v)))
       (mask (let ((md (make-vector (* seq seq) 0.0)) (i 0)) (while (< i seq) (let ((j (1+ i))) (while (< j seq) (aset md (+ (* i seq) j) -1.0e30) (setq j (1+ j)))) (setq i (1+ i))) (photon-tensor (list seq seq) md)))
       (lrs (let ((l nil) (tt 1)) (while (<= tt steps) (push (nl-llm-lr-warmup-cosine tt steps warmup base minlr) l) (setq tt (1+ tt))) (nreverse l)))
       (gpu-losses nil) (cpu-losses nil))
  ;; ---- GPU: Adam + scheduled lr ----
  (let* ((b (nlga-new)) (wb (lambda (bt) (let ((o nil) (kv bt)) (while kv (push (car kv) o) (push (nlga-param b (gd--cp (cadr kv))) o) (setq kv (cddr kv))) (nreverse o))))
         (xr (nlga-const b (gd--cp x))) (g0 (funcall wb blk0))
         (lnfgr (nlga-param b (gd--cp lnfg))) (whr (nlga-param b (gd--cp Wh))) (bhr (nlga-param b (gd--cp bh)))
         (cosr (nlga-const b (car tables))) (sinr (nlga-const b (cdr tables)))
         (sposr (nlga-scalar b 1.0)) (snegr (nlga-scalar b -1.0)) (sclr (nlga-scalar b scl)) (oner (nlga-scalar b 1.0))
         (maskr (nlga-const b mask)) (ohr (nlga-const b onehot))
         (x2 (nlga-block b xr g0 heads kvh cosr sinr sposr snegr sclr maskr))
         (xf (nlga-rmsnorm b x2 lnfgr)) (logits (nlga-linear b xf whr bhr)) (lout (nlga-keep b logits oner)))
    (nlga-seed-ce b logits ohr) (nlga-finish-adam b base b1 b2 eps) (nlga-compile b)
    (let ((tt 1)) (while (<= tt steps)
      (nlga-adam-update-t b tt (nth (1- tt) lrs))    ; scheduled base lr
      (push (gd--ce (nth lout (nlga-step b)) seq vocab targets) gpu-losses)
      (setq tt (1+ tt))))
    (nlga-free b))
  (setq gpu-losses (nreverse gpu-losses))
  (nl-llm-gpu-disable)
  ;; ---- CPU reference: Adam with the same per-step lr schedule ----
  (let* ((P (lambda (tn) (photon-autograd-const (gd--cp tn))))
         (xc (funcall P x)) (c0 (let ((o nil) (kv blk0)) (while kv (push (car kv) o) (push (funcall P (cadr kv)) o) (setq kv (cddr kv))) (nreverse o)))
         (lnfgc (funcall P lnfg)) (whc (funcall P Wh)) (bhc (funcall P bh))
         (params (append (let ((o nil) (kv c0)) (while kv (push (cadr kv) o) (setq kv (cddr kv))) (nreverse o)) (list lnfgc whc bhc)))
         (ms (mapcar (lambda (p) (make-vector (length (photon-tensor-data (pav-value p))) 0.0)) params))
         (vs (mapcar (lambda (p) (make-vector (length (photon-tensor-data (pav-value p))) 0.0)) params))
         (tt 1))
    (while (<= tt steps)
      (photon-autograd-reset-tape)
      (let* ((x2 (nl-llm-ag-block xc c0 heads kvh)) (xf (nl-llm-ag-rmsnorm x2 lnfgc))
             (logits (photon-autograd-linear xf whc bhc)) (loss (photon-autograd-softmax-ce logits targets)))
        (push (aref (photon-tensor-data (pav-value loss)) 0) cpu-losses)
        (photon-autograd-zero-grad params) (photon-autograd-backward loss)
        (let ((lr-t (* (nth (1- tt) lrs) (/ (sqrt (- 1.0 (expt b2 tt))) (- 1.0 (expt b1 tt))))) (pl params) (ml ms) (vl vs))
          (while pl
            (let* ((p (car pl)) (mvv (car ml)) (vvv (car vl))
                   (gd (photon-tensor-data (pav-grad p))) (wd (photon-tensor-data (pav-value p))) (n (length wd)) (i 0))
              (while (< i n)
                (let ((g (aref gd i)))
                  (aset mvv i (+ (* b1 (aref mvv i)) (* (- 1.0 b1) g)))
                  (aset vvv i (+ (* b2 (aref vvv i)) (* (- 1.0 b2) (* g g))))
                  (aset wd i (- (aref wd i) (* lr-t (/ (aref mvv i) (+ (sqrt (aref vvv i)) eps))))))
                (setq i (1+ i))))
            (setq pl (cdr pl) ml (cdr ml) vl (cdr vl)))))
      (setq tt (1+ tt)))
    (setq cpu-losses (nreverse cpu-losses)))
  (let ((maxrel 0.0) (i 0))
    (while (< i steps)
      (setq maxrel (max maxrel (/ (abs (- (nth i gpu-losses) (nth i cpu-losses))) (max 1e-4 (abs (nth i cpu-losses))))))
      (setq i (1+ i)))
    (gd--ck "LR-scheduled Adam GPU == CPU" (< maxrel 1e-1) (format "maxrel=%.2e" maxrel)))
  (gd--ck "LR schedule warmup then decay"
          (and (< (nth 0 lrs) (nth 1 lrs)) (> (nth 1 lrs) (car (last lrs))))
          (format "lr[1..]=%s" (mapcar (lambda (l) (/ (round (* l 10000)) 10000.0)) lrs)))
  (gd--ck "LR-scheduled training decreases loss" (< (car (last gpu-losses)) (car gpu-losses))
          (format "loss %.4f -> %.4f" (car gpu-losses) (car (last gpu-losses))))
  (princ (format "GPU: %s\nCPU: %s\n"
                 (mapcar (lambda (l) (/ (round (* l 1000)) 1000.0)) gpu-losses)
                 (mapcar (lambda (l) (/ (round (* l 1000)) 1000.0)) cpu-losses)))
  (princ (format "NL-LLM-GPU-SCHED %s (%d failures)\n" (if (= gd--fail 0) "ALL-PASS" "HAS-FAILURES") gd--fail))
  (kill-emacs (if (= gd--fail 0) 0 1)))
;;; gpu-sched-test.el ends here
