;;; gpu-ag-test.el --- resident-autograd builder correctness (MLP)  -*- lexical-binding: t; -*-
;; Re-expresses the 2-layer MLP on the resident-autograd builder (nl-llm-gpu-ag)
;; and checks that the auto-derived on-device forward+backward+SGD matches the
;; CPU autograd reference -- validating the builder before it is used for the
;; full transformer block.  Skips (exit 0) without a Vulkan device.
;;   emacs -Q --batch -L lisp -L ../nelisp-photon/lisp -l test/gpu-ag-test.el
(add-to-list 'load-path (expand-file-name "lisp"))
(add-to-list 'load-path (expand-file-name "../nelisp-photon/lisp"))
(require 'cl-lib)
(require 'photon-tensor)
(require 'photon-autograd)
(require 'nl-llm-gpu)
(require 'nl-llm-gpu-ag)

(defvar ga--fail 0)
(defun ga--ck (name ok &optional extra)
  (princ (format "%-46s %s  %s\n" name
                 (if ok "PASS" (progn (setq ga--fail (1+ ga--fail)) "FAIL")) (or extra ""))))
(defun ga--vec (n seed sc)
  (let ((v (make-vector n 0.0)) (i 0))
    (while (< i n)
      (aset v i (* sc 2.0 (- (/ (float (mod (+ (* (1+ i) 2654435761) (* (1+ seed) 40503)) 65536))
                                65536.0) 0.5)))
      (setq i (1+ i)))
    v))
(defun ga--t (shape seed sc) (let ((n 1)) (dolist (d shape) (setq n (* n d)))
                               (photon-tensor shape (ga--vec n seed sc))))
(defun ga--copy (tn) (photon-tensor (photon-tensor-shape tn) (copy-sequence (photon-tensor-data tn))))

(unless (nl-llm-gpu-enable)
  (princ "NL-LLM-GPU-AG SKIP (no GPU server / Vulkan device)\n") (kill-emacs 0))

(let* ((seq 4) (in 6) (hid 8) (out 5) (lr 0.05) (steps 8)
       (ntot (* seq out)) (invn (/ 1.0 (float ntot))) (sc 0.4)
       (x (ga--t (list seq in) 1 sc)) (target (ga--t (list seq out) 9 sc))
       (W1 (ga--t (list hid in) 2 sc)) (b1 (ga--t (list hid) 3 sc))
       (W2 (ga--t (list out hid) 4 sc)) (b2 (ga--t (list out) 5 sc))
       (td (photon-tensor-data target)) (gpu-losses nil))
  ;; ---- GPU via the resident-autograd builder ----
  (let* ((b (nlga-new))
         (xr (nlga-const b (ga--copy x)))
         (w1r (nlga-param b (ga--copy W1))) (b1r (nlga-param b (ga--copy b1)))
         (w2r (nlga-param b (ga--copy W2))) (b2r (nlga-param b (ga--copy b2)))
         (tr (nlga-const b (ga--copy target)))
         (invr (nlga-scalar b invn)) (lrr (nlga-scalar b lr)) (oner (nlga-scalar b 1.0))
         (h1 (nlga-linear b xr w1r b1r)) (a (nlga-gelu b h1)) (y (nlga-linear b a w2r b2r))
         (yout (nlga-keep b y oner)))
    (nlga-seed-mse b y tr invr)
    (nlga-finish b lrr) (nlga-compile b)   ; exercise the compiled (re-submit) path
    (let ((s 0))
      (while (< s steps)
        (let* ((outs (nlga-step b)) (yv (nth yout outs)) (acc 0.0) (i 0))
          (while (< i ntot) (let ((d (- (aref yv i) (aref td i)))) (setq acc (+ acc (* d d)))) (setq i (1+ i)))
          (push (* 0.5 invn acc) gpu-losses))
        (setq s (1+ s))))
    (nlga-free b))
  (setq gpu-losses (nreverse gpu-losses))
  (nl-llm-gpu-disable)   ; CPU reference must run on the CPU backend
  ;; ---- CPU autograd reference (identical init) ----
  (let* ((xc (photon-autograd-const (ga--copy x)))
         (w1c (photon-autograd-const (ga--copy W1))) (b1c (photon-autograd-const (ga--copy b1)))
         (w2c (photon-autograd-const (ga--copy W2))) (b2c (photon-autograd-const (ga--copy b2)))
         (params (list w1c b1c w2c b2c)) (cpu-losses nil) (s 0))
    (while (< s steps)
      (photon-autograd-reset-tape)
      (let* ((y (photon-autograd-linear (photon-autograd-gelu (photon-autograd-linear xc w1c b1c)) w2c b2c))
             (yd (photon-tensor-data (pav-value y))) (gd (photon-tensor-data (pav-grad y)))
             (loss 0.0) (i 0))
        (while (< i ntot)
          (let ((d (- (aref yd i) (aref td i)))) (setq loss (+ loss (* d d))) (aset gd i (* d invn)))
          (setq i (1+ i)))
        (photon-autograd-zero-grad params)
        (dolist (v photon-autograd--tape) (when (pav-backward v) (funcall (pav-backward v) (pav-grad v))))
        (photon-autograd-sgd params lr)
        (push (* 0.5 invn loss) cpu-losses))
      (setq s (1+ s)))
    (setq cpu-losses (nreverse cpu-losses))
    (let ((maxrel 0.0) (i 0))
      (while (< i steps)
        (setq maxrel (max maxrel (/ (abs (- (nth i gpu-losses) (nth i cpu-losses)))
                                    (max 1e-4 (abs (nth i cpu-losses))))))
        (setq i (1+ i)))
      (ga--ck "builder MLP loss == CPU autograd" (< maxrel 5e-2) (format "maxrel=%.2e" maxrel)))
    (ga--ck "builder MLP decreases loss"
            (< (car (last gpu-losses)) (* 0.95 (car gpu-losses)))
            (format "loss %.4f -> %.4f" (car gpu-losses) (car (last gpu-losses))))))
(princ (format "NL-LLM-GPU-AG %s (%d failures)\n"
               (if (= ga--fail 0) "ALL-PASS" "HAS-FAILURES") ga--fail))
(kill-emacs (if (= ga--fail 0) 0 1))
;;; gpu-ag-test.el ends here
