;;; gpu-bitnet-dp4a-model-test.el --- whole-model DP4A decode  -*- lexical-binding: t; -*-
;; Wires hardware DP4A (1-f32 bitcast int8) through a whole-model KV-cache decode:
;; every block linear runs via bitlinear-dp4a-1f.  Checks it against a CPU
;; reference that applies the SAME int8-activation / ternary-weight linear (with
;; the identical attention/SwiGLU glue, reusing nl-llm-bitnet--blk), and reports
;; the block-linear weight VRAM (1 byte/weight = 4x less than f32).
;; Skips (exit 0) without a Vulkan device.
;;   emacs -Q --batch -L lisp -L ../nelisp-photon/lisp -l test/gpu-bitnet-dp4a-model-test.el
(add-to-list 'load-path (expand-file-name "lisp"))
(add-to-list 'load-path (expand-file-name "../nelisp-photon/lisp"))
(require 'cl-lib)
(require 'photon-tensor)
(require 'nl-llm-decode)
(require 'nl-llm-bitnet)
(require 'nl-llm-gpu)

(defvar bm--fail 0)
(defun bm--ck (name ok &optional extra)
  (princ (format "%-48s %s  %s\n" name (if ok "PASS" (progn (setq bm--fail (1+ bm--fail)) "FAIL")) (or extra ""))))
(defun bm--t (shape seed sc) (let ((n 1)) (dolist (d shape) (setq n (* n d)))
  (photon-tensor shape (let ((v (make-vector n 0.0)) (i 0))
    (while (< i n) (aset v i (* sc 2.0 (- (/ (float (mod (+ (* (1+ i) 2654435761) (* (1+ seed) 40503)) 65536)) 65536.0) 0.5))) (setq i (1+ i))) v))))
(defun bm--ones (n) (photon-tensor (list n) (make-vector n 1.0)))

;; CPU int8-activation / ternary-weight linear matching bitlinear-dp4a-1f exactly.
(defun bm--cpu-i8 (xrow w bias)
  (let* ((xd (photon-tensor-data xrow)) (wd (photon-tensor-data w)) (bd (photon-tensor-data bias))
         (in (length xd)) (out (length bd)) (n (* out in)) (amax 0.0) (wacc 0.0))
    (dotimes (i in) (setq amax (max amax (abs (aref xd i)))))
    (dotimes (i n) (setq wacc (+ wacc (abs (aref wd i)))))
    (let* ((gamma (/ amax 127.0)) (beta (/ wacc (float n))) (y (make-vector out 0.0)))
      (dotimes (o out)
        (let ((dot 0) (i 0))
          (while (< i in)
            (let* ((a8 (if (> gamma 0.0) (max -127 (min 127 (round (/ (aref xd i) gamma)))) 0))
                   (q (if (> beta 0.0) (/ (aref wd (+ (* o in) i)) beta) 0.0))
                   (w8 (cond ((>= q 0.5) 1) ((<= q -0.5) -1) (t 0))))
              (setq dot (+ dot (* a8 w8)))) (setq i (1+ i)))
          (aset y o (+ (aref bd o) (* beta gamma dot)))))
      y)))
(defun bm--cpu-step (token blocks caches wte lnfg bh dim)
  (let* ((wd (photon-tensor-data wte))
         (x (photon-tensor (list 1 dim) (let ((v (make-vector dim 0.0))) (dotimes (j dim) (aset v j (aref wd (+ (* token dim) j)))) v)))
         (bl blocks) (cl caches))
    (while bl (setq x (nl-llm-bitnet--blk x (car bl) (car cl) #'bm--cpu-i8 nil)) (setq bl (cdr bl) cl (cdr cl)))
    (photon-tensor-data (photon-tensor-linear (nl-llm-rmsnorm x lnfg) wte bh))))

(unless (nl-llm-gpu-enable)
  (princ "NL-LLM-GPU-BITNET-DP4A-MODEL SKIP (no GPU server / Vulkan device)\n") (kill-emacs 0))

(let* ((dim 32) (heads 4) (kvh 2) (ff 64) (nblocks 2) (vocab 24) (hd (/ dim heads)) (kvdim (* kvh hd)) (sc 0.4) (maxseq 16)
       (wte (bm--t (list vocab dim) 1 sc)) (lnfg (bm--ones dim)) (bh (bm--t (list vocab) 19 0.1))
       (mkblk (lambda (s0) (list :ln1g (bm--ones dim) :wq (bm--t (list dim dim) (+ s0 1) sc) :bq (bm--t (list dim) (+ s0 11) 0.1)
                                 :wk (bm--t (list kvdim dim) (+ s0 2) sc) :bk (bm--t (list kvdim) (+ s0 12) 0.1)
                                 :wv (bm--t (list kvdim dim) (+ s0 3) sc) :bv (bm--t (list kvdim) (+ s0 13) 0.1)
                                 :wo (bm--t (list dim dim) (+ s0 4) sc) :bo (bm--t (list dim) (+ s0 14) 0.1) :ln2g (bm--ones dim)
                                 :wg (bm--t (list ff dim) (+ s0 5) sc) :bg (bm--t (list ff) (+ s0 15) 0.1)
                                 :wu (bm--t (list ff dim) (+ s0 6) sc) :bu (bm--t (list ff) (+ s0 16) 0.1)
                                 :wd (bm--t (list dim ff) (+ s0 7) sc) :bd (bm--t (list dim) (+ s0 17) 0.1))))
       (blocks (list (funcall mkblk 100) (funcall mkblk 200)))
       (prompt '(1 5 2 9 3 7)) (gpu nil) (cpu nil))
  (let ((pblocks (mapcar #'nl-llm-bitnet-dp4a-pack-block blocks))
        (gc (mapcar (lambda (_) (nl-llm-dcache-new maxseq dim heads kvh)) blocks)))
    (dolist (tk prompt) (push (copy-sequence (nl-llm-bitnet-dp4a-decode-step tk pblocks gc wte lnfg bh dim)) gpu))
    (nl-llm-bitnet-dp4a-free-blocks pblocks))
  (nl-llm-gpu-disable)
  (setq gpu (nreverse gpu))
  (let ((cc (mapcar (lambda (_) (nl-llm-dcache-new maxseq dim heads kvh)) blocks)))
    (dolist (tk prompt) (push (copy-sequence (bm--cpu-step tk blocks cc wte lnfg bh dim)) cpu)))
  (setq cpu (nreverse cpu))
  (let ((maxrel 0.0) (p 0))
    (dotimes (i (length gpu))
      (let ((g (nth i gpu)) (c (nth i cpu)) (j 0))
        (while (< j vocab) (setq maxrel (max maxrel (/ (abs (- (aref g j) (aref c j))) (max 1e-3 (abs (aref c j)))))) (setq j (1+ j))))
      (setq p (1+ p)))
    (bm--ck "whole-model DP4A decode == CPU int8 ternary" (< maxrel 5e-3) (format "maxrel=%.2e over %d toks" maxrel p)))
  ;; VRAM: block-linear weights f32 vs 1-byte-per-weight DP4A pack
  (let ((f32 0) (i8 0))
    (dolist (blk blocks)
      (let ((kv blk)) (while kv (when (memq (car kv) '(:wq :wk :wv :wg :wu :wd :wo))
        (let* ((sh (photon-tensor-shape (cadr kv))) (out (car sh)) (in (nth 1 sh)))
          (setq f32 (+ f32 (* out in 4))) (setq i8 (+ i8 (* out (/ (+ in 3) 4) 4))))) (setq kv (cddr kv)))))
    (bm--ck "DP4A weight VRAM is 1 byte/weight (4x less)" (<= i8 (/ f32 3))
            (format "%.1f KB -> %.1f KB (%.1fx)" (/ f32 1024.0) (/ i8 1024.0) (/ (float f32) i8))))
  (princ (format "NL-LLM-GPU-BITNET-DP4A-MODEL %s (%d failures)\n" (if (= bm--fail 0) "ALL-PASS" "HAS-FAILURES") bm--fail))
  (kill-emacs (if (= bm--fail 0) 0 1)))
;;; gpu-bitnet-dp4a-model-test.el ends here
