;;; lora-test.el --- CPU autograd checks for LoRA adapters  -*- lexical-binding: t; -*-
;; Run: emacs -Q --batch -L lisp -L ../nelisp-photon/lisp -l test/lora-test.el
(add-to-list 'load-path (expand-file-name "lisp"))
(add-to-list 'load-path (expand-file-name "../nelisp-photon/lisp"))
(require 'photon-tensor)
(require 'photon-autograd)
(require 'nl-llm-lora)

(defvar lora--fail 0)
(defun lora--ck (name ok &optional extra)
  (princ (format "%-46s %s  %s\n" name (if ok "PASS"
                                         (progn (setq lora--fail (1+ lora--fail)) "FAIL"))
                 (or extra ""))))
(defun lora--hash (index seed)
  (/ (float (mod (+ (* (1+ index) 2654435761) (* (1+ seed) 40503)) 65536))
     65536.0))
(defun lora--t (shape seed sc)
  (let ((n 1))
    (dolist (d shape) (setq n (* n d)))
    (photon-tensor shape
                   (let ((v (make-vector n 0.0)) (i 0))
                     (while (< i n)
                       (aset v i (* sc 2.0 (- (lora--hash i seed) 0.5)))
                       (setq i (1+ i)))
                     v))))
(defun lora--copy (tn)
  (photon-tensor (copy-sequence (photon-tensor-shape tn))
                 (copy-sequence (photon-tensor-data tn))))
(defun lora--fill! (tn seed sc)
  (let* ((d (photon-tensor-data tn)) (n (length d)) (i 0))
    (while (< i n)
      (aset d i (* sc 2.0 (- (lora--hash i seed) 0.5)))
      (setq i (1+ i))))
  tn)
(defun lora--zero! (tn)
  (let* ((d (photon-tensor-data tn)) (n (length d)) (i 0))
    (while (< i n) (aset d i 0.0) (setq i (1+ i))))
  tn)
(defun lora--mask (n)
  (let ((v (make-vector n 0.0)) (i 0))
    (while (< i n) (aset v i (- (mod (* (1+ i) 13) 7) 3.0)) (setq i (1+ i)))
    v))
(defun lora--loss (out w)
  (let* ((d (photon-tensor-data (pav-value out))) (n (length d)) (s 0.0) (i 0))
    (while (< i n) (setq s (+ s (* (aref d i) (aref w i)))) (setq i (1+ i)))
    s))
(defun lora--maxabs (a b)
  (let* ((ad (photon-tensor-data a)) (bd (photon-tensor-data b))
         (n (length ad)) (m 0.0) (i 0))
    (while (< i n)
      (let ((e (abs (- (aref ad i) (aref bd i)))))
        (when (> e m) (setq m e)))
      (setq i (1+ i)))
    m))
(defun lora--same-data-p (a b)
  (let* ((ad (photon-tensor-data a)) (bd (photon-tensor-data b))
         (n (length ad)) (ok t) (i 0))
    (while (< i n)
      (unless (= (aref ad i) (aref bd i)) (setq ok nil))
      (setq i (1+ i)))
    ok))
(defun lora--moved-p (a b)
  (not (lora--same-data-p a b)))
(defun lora--mse-seed (out target)
  (let* ((yd (photon-tensor-data (pav-value out))) (td (photon-tensor-data target))
         (gd (photon-tensor-data (pav-grad out))) (n (length yd))
         (inv (/ 1.0 (float n))) (ss 0.0) (i 0))
    (while (< i n)
      (let ((d (- (aref yd i) (aref td i))))
        (setq ss (+ ss (* d d)))
        (aset gd i (* d inv)))
      (setq i (1+ i)))
    (* 0.5 inv ss)))
(defun lora--backward-tape ()
  (dolist (v photon-autograd--tape)
    (when (pav-backward v) (funcall (pav-backward v) (pav-grad v)))))
(defun lora--gradcheck (name inputs forward idx)
  (let ((eps 1.0e-5) (tol 1.0e-3))
    (photon-autograd-zero-grad inputs)
    (photon-autograd-reset-tape)
    (let* ((out (funcall forward)) (od (photon-tensor-data (pav-value out))) (w (lora--mask (length od))))
      (let ((og (photon-tensor-data (pav-grad out))) (i 0) (n (length od)))
        (while (< i n) (aset og i (aref w i)) (setq i (1+ i))))
      (lora--backward-tape)
      (let* ((target (nth idx inputs))
             (ana (copy-sequence (photon-tensor-data (pav-grad target))))
             (xd (photon-tensor-data (pav-value target))) (nx (length xd))
             (maxrel 0.0) (k 0))
        (while (< k nx)
          (let ((orig (aref xd k)))
            (aset xd k (+ orig eps)) (photon-autograd-reset-tape)
            (let ((lp (lora--loss (funcall forward) w)))
              (aset xd k (- orig eps)) (photon-autograd-reset-tape)
              (let* ((lm (lora--loss (funcall forward) w))
                     (num (/ (- lp lm) (* 2.0 eps)))
                     (den (max 1.0e-4 (abs num) (abs (aref ana k))))
                     (rel (/ (abs (- num (aref ana k))) den)))
                (when (> rel maxrel) (setq maxrel rel)))
              (aset xd k orig)))
          (setq k (1+ k)))
        (lora--ck name (< maxrel tol) (format "maxrel=%.2e" maxrel))))))

;; identity at init (B = 0 -> exact no-op)
(let* ((seq 3) (in 4) (out 5) (rank 2)
       (x (photon-autograd-const (lora--t (list seq in) 1 0.3)))
       (w (photon-autograd-const (lora--t (list out in) 2 0.25)))
       (b (photon-autograd-const (lora--t (list out) 3 0.1)))
       (lora (nl-llm-lora-make out in rank nil 7))
       (attached (nl-llm-lora-attach lora))
       (y0 (photon-autograd-linear x w b))
       (y1 (nl-llm-ag-lora-linear x w b attached)))
  (lora--ck "lora init is exact identity"
            (and (equal (photon-tensor-shape (pav-value y0)) (photon-tensor-shape (pav-value y1)))
                 (equal (photon-tensor-data (pav-value y0)) (photon-tensor-data (pav-value y1))))))

;; gradient checks through the full layer
(let* ((seq 3) (in 4) (out 5) (rank 2)
       (x (photon-autograd-const (lora--t (list seq in) 11 0.25)))
       (w (photon-autograd-const (lora--t (list out in) 12 0.2)))
       (b (photon-autograd-const (lora--t (list out) 13 0.08)))
       (lora (nl-llm-lora-make out in rank nil 17)))
  (lora--fill! (plist-get lora :b) 18 0.15)
  (let* ((attached (nl-llm-lora-attach lora))
         (ap (plist-get attached :a)) (bp (plist-get attached :b)))
    (lora--gradcheck "ag-lora-linear d/dA" (list x w b ap bp)
                     (lambda () (nl-llm-ag-lora-linear x w b attached)) 3)
    (lora--gradcheck "ag-lora-linear d/dB" (list x w b ap bp)
                     (lambda () (nl-llm-ag-lora-linear x w b attached)) 4)
    (lora--gradcheck "ag-lora-linear d/dx" (list x w b ap bp)
                     (lambda () (nl-llm-ag-lora-linear x w b attached)) 0)))

;; merge equivalence with a non-zero adapter
(let* ((seq 4) (in 5) (out 4) (rank 2)
       (xt (lora--t (list seq in) 21 0.3))
       (wt (lora--t (list out in) 22 0.25))
       (bt (lora--t (list out) 23 0.1))
       (x (photon-autograd-const (lora--copy xt)))
       (w (photon-autograd-const (lora--copy wt)))
       (b (photon-autograd-const (lora--copy bt)))
       (lora (nl-llm-lora-make out in rank nil 24)))
  (lora--fill! (plist-get lora :b) 25 0.12)
  (let* ((attached (nl-llm-lora-attach lora))
         (merged (nl-llm-lora-merge wt lora))
         (ym (photon-autograd-linear x (photon-autograd-const merged) b))
         (yl (nl-llm-ag-lora-linear x w b attached))
         (maxd (lora--maxabs (pav-value ym) (pav-value yl))))
    (lora--ck "lora merge == branch forward" (< maxd 1.0e-9) (format "maxdiff=%.2e" maxd))))

;; unmerge round-trip
(let* ((out 5) (in 4) (rank 2)
       (w (lora--t (list out in) 31 0.2))
       (lora (nl-llm-lora-make out in rank nil 32)))
  (lora--fill! (plist-get lora :b) 33 0.11)
  (let* ((w2 (nl-llm-lora-unmerge (nl-llm-lora-merge w lora) lora))
         (maxd (lora--maxabs w w2)))
    (lora--ck "lora unmerge(merge(W)) == W" (< maxd 1.0e-12) (format "maxdiff=%.2e" maxd))))

;; base weight stays frozen when only LoRA params are optimized
(let* ((seq 4) (in 4) (out 5) (rank 2) (lr 0.15)
       (target (lora--t (list seq out) 41 0.2))
       (x (photon-autograd-const (lora--t (list seq in) 42 0.3)))
       (w (photon-autograd-const (lora--t (list out in) 43 0.25)))
       (b (photon-autograd-const (lora--t (list out) 44 0.1)))
       (lora (nl-llm-lora-make out in rank nil 45)))
  (lora--fill! (plist-get lora :b) 46 0.12)
  (let* ((attached (nl-llm-lora-attach lora))
         (params (nl-llm-lora-params attached))
         (w0 (lora--copy (pav-value w)))
         (a0 (lora--copy (pav-value (plist-get attached :a))))
         (b0 (lora--copy (pav-value (plist-get attached :b)))))
    (photon-autograd-reset-tape)
    (let ((y (nl-llm-ag-lora-linear x w b attached)))
      (photon-autograd-zero-grad params)
      (lora--mse-seed y target)
      (lora--backward-tape)
      (photon-autograd-sgd params lr))
    (lora--ck "lora keeps base W frozen" (lora--same-data-p w0 (pav-value w)))
    (lora--ck "lora updates A and B only"
              (and (lora--moved-p a0 (pav-value (plist-get attached :a)))
                   (lora--moved-p b0 (pav-value (plist-get attached :b)))))))

;; adapter training actually reduces a deterministic fit loss
(let* ((seq 5) (in 4) (out 5) (rank 2) (lr 0.5) (steps 200)
       (xt (lora--t (list seq in) 51 0.35))
       (wt (lora--t (list out in) 52 0.2))
       (bt (lora--t (list out) 53 0.08))
       (truth (nl-llm-lora-make out in rank nil 55))
       (fit (nl-llm-lora-make out in rank nil 55))
       (x (photon-autograd-const (lora--copy xt)))
       (w (photon-autograd-const (lora--copy wt)))
       (b (photon-autograd-const (lora--copy bt))))
  (lora--fill! (plist-get truth :b) 56 0.35)
  (let* ((target (photon-tensor-linear xt (nl-llm-lora-merge wt truth) bt))
         (attached (nl-llm-lora-attach fit))
         (params (nl-llm-lora-params attached))
         (loss0 nil) (lossn nil) (s 0))
    (while (< s steps)
      (photon-autograd-reset-tape)
      (let* ((y (nl-llm-ag-lora-linear x w b attached))
             (loss (progn
                     (photon-autograd-zero-grad params)
                     (lora--mse-seed y target))))
        (lora--backward-tape)
        (photon-autograd-sgd params lr)
        (unless loss0 (setq loss0 loss))
        (setq lossn loss))
      (setq s (1+ s)))
    (setq fit (nl-llm-lora-detach attached fit))
    (lora--ck "lora adapter fit lowers MSE"
              (< lossn (* 0.4 loss0))
              (format "mse %.6f -> %.6f" loss0 lossn))))

;; parameter economy
(let* ((out 6) (in 8) (rank 2)
       (lora (nl-llm-lora-make out in rank nil 61))
       (pc (nl-llm-lora-param-count lora))
       (fc (nl-llm-lora-full-count lora)))
  (lora--ck "lora parameter count is economical"
            (and (< pc fc) (= pc (* rank (+ in out))))
            (format "%d vs %d" pc fc)))

;; error cases
(lora--ck "lora rank 0 signals"
          (condition-case nil
              (progn (nl-llm-lora-make 4 4 0) nil)
            (error t)))
(lora--ck "lora rank > bottleneck signals"
          (condition-case nil
              (progn (nl-llm-lora-make 4 3 4) nil)
            (error t)))

(princ (format "NL-LLM-LORA %s (%d failures)\n"
               (if (= lora--fail 0) "ALL-PASS" "HAS-FAILURES") lora--fail))
(kill-emacs (if (= lora--fail 0) 0 1))
;;; lora-test.el ends here
