;;; nl-llm-qwen-tokenizer.el --- donor-compatible byte-level BPE  -*- lexical-binding: t; -*-

;; Doc 08 (docs/design/08-weight-import.org) Phase 1: reproduce a donor's token
;; ids exactly, so an imported checkpoint sees the id sequence it was trained
;; on.  This is a *replay* tokenizer for a fixed donor table, complementary to
;; `photon-bpe', which learns merges from a corpus.  Keeping them separate is
;; deliberate: photon-bpe owns training, this file owns donor fidelity.
;;
;; Why fidelity is the whole job: a byte-level BPE with the right merges but the
;; wrong pre-tokenizer still produces valid ids, just not the donor's ids.  The
;; model then reads plausible-looking nonsense and degrades quietly instead of
;; failing.  `test/qwen-tokenizer-test.el' therefore compares against ids
;; generated by the reference implementation, and carries negative controls
;; proving the comparison can go red.
;;
;; Pipeline, in the order `tokenizers' applies it:
;;
;;   1. split on added/special tokens (before normalisation -- the reference
;;      extracts them from the raw input, so doing this after NFC would fold
;;      characters inside a special token's text)
;;   2. NFC-normalise each remaining gap
;;   3. pre-tokenise the gap with the donor's Split regex, reimplemented as a
;;      scanner over Unicode general categories
;;   4. UTF-8 each piece, map bytes to their single-byte token ids
;;   5. apply merges by ascending rank until no adjacent pair has one
;;
;; The merge table, the vocabulary bytes, the added tokens AND the Unicode
;; category ranges all come from `tools/qwen-tokenizer-export.py' as one binary
;; file.  The categories travel with the table on purpose: reading them from
;; the host would make token ids depend on whichever Unicode version the running
;; Emacs or NeLisp ships, and that dependency fails silently.

;;; Code:

(require 'cl-lib)
(require 'nl-llm-compat)

(declare-function ucs-normalize-NFC-string "ucs-normalize" (str))

(defconst nl-llm-qwen-tok-magic "nl-llm-tok-v2\0\0\0"
  "Magic bytes at the head of an exported tokenizer table.")

(cl-defstruct (nl-llm-qwen-tok (:constructor nl-llm-qwen-tok--make))
  offs        ; vector of n+1 blob offsets, indexed by table slot
  slot-of-id  ; vector mapping token id -> table slot, or nil
  blob        ; unibyte string holding every token's raw bytes
  byte->id    ; 256-element vector: byte value -> token id
  merges      ; hash (LEFT * 262144 + RIGHT) -> RANK * 262144 + RESULT
  added       ; list of (TEXT . ID), longest TEXT first
  lranges     ; flat vector of inclusive (lo hi) pairs for \p{L}
  nranges     ; flat vector of inclusive (lo hi) pairs for \p{N}
  vocab-size) ; the model's padded vocabulary size

(defconst nl-llm-qwen-tok--shift 262144
  "Radix for packing two token ids, or a rank and an id, into one fixnum.
Must exceed any token id; 262144 = 2^18 covers vocabularies up to that size.")

;;; --- binary table loading ------------------------------------------------

(defsubst nl-llm-qwen-tok--u32 (s i)
  "Read a little-endian unsigned 32-bit integer from unibyte S at index I."
  (+ (aref s i)
     (ash (aref s (+ i 1)) 8)
     (ash (aref s (+ i 2)) 16)
     (ash (aref s (+ i 3)) 24)))

(defun nl-llm-qwen-tok--u32-vector (raw at count)
  "Read COUNT little-endian u32s from RAW starting at AT into a vector."
  (let ((out (make-vector count 0)))
    (dotimes (i count)
      (aset out i (nl-llm-qwen-tok--u32 raw (+ at (* 4 i)))))
    out))

;;;###autoload
(defun nl-llm-qwen-tok-load (path)
  "Load the exported tokenizer table at PATH and return a `nl-llm-qwen-tok'."
  (let ((raw (with-temp-buffer
               (set-buffer-multibyte nil)
               (let ((coding-system-for-read 'binary))
                 (insert-file-contents-literally path))
               (buffer-substring-no-properties (point-min) (point-max)))))
    (unless (string-prefix-p nl-llm-qwen-tok-magic raw)
      (error "nl-llm-qwen-tok-load: %s is not an %s table (regenerate with \
make qwen-tokenizer-table)"
             path (substring nl-llm-qwen-tok-magic 0 13)))
    (let* ((n-vocab (nl-llm-qwen-tok--u32 raw 16))
           (n-merge (nl-llm-qwen-tok--u32 raw 20))
           (n-added (nl-llm-qwen-tok--u32 raw 24))
           (vocab-size (nl-llm-qwen-tok--u32 raw 28))
           (n-lrange (nl-llm-qwen-tok--u32 raw 32))
           (n-nrange (nl-llm-qwen-tok--u32 raw 36))
           (offs-at 40)
           (merges-at (+ offs-at (* 4 (1+ n-vocab))))
           (added-at (+ merges-at (* 12 n-merge)))
           (lrange-at (+ added-at (* 8 n-added)))
           (nrange-at (+ lrange-at (* 8 n-lrange)))
           (blob-at (+ nrange-at (* 8 n-nrange)))
           (offs (nl-llm-qwen-tok--u32-vector raw offs-at (1+ n-vocab)))
           (lranges (nl-llm-qwen-tok--u32-vector raw lrange-at (* 2 n-lrange)))
           (nranges (nl-llm-qwen-tok--u32-vector raw nrange-at (* 2 n-nrange)))
           (merges (make-hash-table :test 'eql :size (max 1 (* 2 n-merge))))
           (byte->id (make-vector 256 nil))
           (slot-of-id (make-vector (max vocab-size n-vocab) nil))
           (added nil))
      (unless (= (+ blob-at (aref offs n-vocab)) (length raw))
        (error "nl-llm-qwen-tok-load: %s is truncated (want %d bytes, got %d)"
               path (+ blob-at (aref offs n-vocab)) (length raw)))
      (let ((blob (substring raw blob-at)))
        (dotimes (i n-merge)
          (let ((at (+ merges-at (* 12 i))))
            (puthash (+ (* (nl-llm-qwen-tok--u32 raw at) nl-llm-qwen-tok--shift)
                        (nl-llm-qwen-tok--u32 raw (+ at 4)))
                     (+ (* i nl-llm-qwen-tok--shift)
                        (nl-llm-qwen-tok--u32 raw (+ at 8)))
                     merges)))
        ;; Plain vocabulary slots are id-ordered; added tokens carry their id.
        (dotimes (i n-vocab) (aset slot-of-id i i))
        (dotimes (i n-added)
          (let* ((at (+ added-at (* 8 i)))
                 (id (nl-llm-qwen-tok--u32 raw at))
                 (slot (nl-llm-qwen-tok--u32 raw (+ at 4)))
                 (text (decode-coding-string
                        (substring blob (aref offs slot) (aref offs (1+ slot)))
                        'utf-8-unix)))
            (aset slot-of-id id slot)
            (push (cons text id) added)))
        ;; The byte-level alphabet is exactly the single-byte tokens, and the
        ;; byte -> token map is a bijection on them.  Deriving it here instead
        ;; of exporting it removes a table that could disagree with the blob.
        (dotimes (i n-vocab)
          (when (= 1 (- (aref offs (1+ i)) (aref offs i)))
            (let ((b (aref blob (aref offs i))))
              (when (aref byte->id b)
                (error "nl-llm-qwen-tok-load: byte %d has two single-byte tokens"
                       b))
              (aset byte->id b i))))
        (let ((holes (cl-loop for b below 256 unless (aref byte->id b) collect b)))
          (when holes
            (error "nl-llm-qwen-tok-load: %d byte values have no token (first %S)"
                   (length holes) (car holes))))
        (when (or (zerop n-lrange) (zerop n-nrange))
          (error "nl-llm-qwen-tok-load: %s carries no category ranges" path))
        (nl-llm-qwen-tok--make
         :offs offs :slot-of-id slot-of-id :blob blob :byte->id byte->id
         :merges merges :lranges lranges :nranges nranges
         ;; Longest first, so a token that is a prefix of another cannot win.
         :added (sort added (lambda (a b) (> (length (car a)) (length (car b)))))
         :vocab-size vocab-size)))))

;;; --- character classes --------------------------------------------------

(defconst nl-llm-qwen-tok--white-space
  ;; Unicode White_Space, which is what \s means to the donor's regex engine.
  ;; Hard-coded rather than exported because the set is 26 code points fixed
  ;; since Unicode 4.1, unlike the letter and number categories which grow.
  '((#x0009 . #x000D) (#x0020 . #x0020) (#x0085 . #x0085) (#x00A0 . #x00A0)
    (#x1680 . #x1680) (#x2000 . #x200A) (#x2028 . #x2029) (#x202F . #x202F)
    (#x205F . #x205F) (#x3000 . #x3000))
  "Inclusive code-point ranges of Unicode White_Space.")

(defun nl-llm-qwen-tok--space-p (ch)
  "Non-nil when CH is Unicode White_Space."
  (cl-loop for (lo . hi) in nl-llm-qwen-tok--white-space
           thereis (and (>= ch lo) (<= ch hi))))

(defun nl-llm-qwen-tok--in-ranges (ranges ch)
  "Non-nil when CH falls in RANGES, a flat ascending vector of (lo hi) pairs."
  (let ((lo 0) (hi (1- (/ (length ranges) 2))) (found nil))
    (while (and (not found) (<= lo hi))
      (let ((mid (/ (+ lo hi) 2)))
        (cond ((< ch (aref ranges (* 2 mid))) (setq hi (1- mid)))
              ((> ch (aref ranges (1+ (* 2 mid)))) (setq lo (1+ mid)))
              (t (setq found t)))))
    found))

(defun nl-llm-qwen-tok-letter-p (tok ch)
  "Non-nil when CH is in Unicode category L per TOK's pinned ranges."
  (nl-llm-qwen-tok--in-ranges (nl-llm-qwen-tok-lranges tok) ch))

(defun nl-llm-qwen-tok-number-p (tok ch)
  "Non-nil when CH is in Unicode category N per TOK's pinned ranges."
  (nl-llm-qwen-tok--in-ranges (nl-llm-qwen-tok-nranges tok) ch))

(defsubst nl-llm-qwen-tok--nl-p (ch) (or (eq ch ?\n) (eq ch ?\r)))

(defun nl-llm-qwen-tok--preds (tok)
  "Return the character predicates the pre-tokenizer needs from TOK.
A 4-element vector [LETTER NUMBER SPACE OTHER], built once per call so the
scanner allocates no closures per piece."
  (let ((letter (lambda (ch) (nl-llm-qwen-tok-letter-p tok ch)))
        (number (lambda (ch) (nl-llm-qwen-tok-number-p tok ch))))
    (vector letter number
            #'nl-llm-qwen-tok--space-p
            ;; [^\s\p{L}\p{N}]
            (lambda (ch) (not (or (nl-llm-qwen-tok--space-p ch)
                                  (funcall letter ch)
                                  (funcall number ch)))))))

;;; --- pre-tokenizer ------------------------------------------------------

(defconst nl-llm-qwen-tok--contractions '("s" "t" "re" "ve" "m" "ll" "d")
  "Suffixes of the donor regex's leading (?i:'s|'t|'re|'ve|'m|'ll|'d) branch.")

(defun nl-llm-qwen-tok--match-contraction (v n i)
  "Return the end index of a contraction match in char vector V at I, or nil."
  (when (eq (aref v i) ?\')
    (cl-loop for suffix in nl-llm-qwen-tok--contractions
             for len = (length suffix)
             when (and (<= (+ i 1 len) n)
                       (cl-loop for k below len
                                always (eq (downcase (aref v (+ i 1 k)))
                                           (aref suffix k))))
             return (+ i 1 len))))

(defun nl-llm-qwen-tok--run (v n i pred)
  "Return the end index of the maximal run from I in V of chars matching PRED."
  (let ((j i))
    (while (and (< j n) (funcall pred (aref v j))) (setq j (1+ j)))
    j))

(defun nl-llm-qwen-tok--next-piece (preds v n i)
  "Return the end index of the pre-tokenizer piece starting at I in V.
PREDS is the vector from `nl-llm-qwen-tok--preds'.

The donor's pattern is one alternation tried left to right with backtracking:

  (?i:'s|'t|'re|'ve|'m|'ll|'d)   contractions
  [^\\r\\n\\p{L}\\p{N}]?\\p{L}+  a letter run, optionally with one leading char
  \\p{N}                         exactly one number character
   ?[^\\s\\p{L}\\p{N}]+[\\r\\n]* a symbol run, optionally with one leading space
  \\s*[\\r\\n]+                  whitespace ending at its last newline
  \\s+(?!\\S)                    a whitespace run, minus its last character
  \\s+                           a whitespace run

Each branch below is that branch's leftmost-longest match, with the three
whitespace branches resolved analytically rather than by re-scanning.  The
ordering is load-bearing: it is what makes \" b\" one piece rather than two."
  (let ((letter (aref preds 0)) (number (aref preds 1))
        (space (aref preds 2)) (other (aref preds 3))
        (ch (aref v i)))
    (or
     ;; 1. contractions
     (nl-llm-qwen-tok--match-contraction v n i)
     ;; 2. one optional non-newline non-alphanumeric char, then letters
     (and (not (nl-llm-qwen-tok--nl-p ch))
          (not (funcall letter ch))
          (not (funcall number ch))
          (< (1+ i) n)
          (funcall letter (aref v (1+ i)))
          (nl-llm-qwen-tok--run v n (1+ i) letter))
     (and (funcall letter ch)
          (nl-llm-qwen-tok--run v n i letter))
     ;; 3. a single number character
     (and (funcall number ch) (1+ i))
     ;; 4. one optional space, then symbols, then trailing newlines
     (and (eq ch ?\s) (< (1+ i) n) (funcall other (aref v (1+ i)))
          (nl-llm-qwen-tok--run
           v n (nl-llm-qwen-tok--run v n (1+ i) other)
           #'nl-llm-qwen-tok--nl-p))
     (and (funcall other ch)
          (nl-llm-qwen-tok--run
           v n (nl-llm-qwen-tok--run v n i other)
           #'nl-llm-qwen-tok--nl-p))
     ;; 5/6/7. whitespace.  \s* is greedy, so \s*[\r\n]+ ends just after the
     ;; run's LAST newline; \s+(?!\S) gives back one character when a non-space
     ;; follows, which is what leaves a single space to start the next piece.
     (let ((end (nl-llm-qwen-tok--run v n i space)))
       (when (> end i)
         (let ((last-nl (cl-loop for k from (1- end) downto i
                                 when (nl-llm-qwen-tok--nl-p (aref v k))
                                 return k)))
           (cond
            (last-nl (1+ last-nl))
            ((= end n) end)
            ((> (- end i) 1) (1- end))
            (t end)))))
     ;; Unreachable for any input: the alternation above is total.
     (error "nl-llm-qwen-tok: no pre-tokenizer branch matched char %S" ch))))

(defun nl-llm-qwen-tok-pretokenize (tok text)
  "Split TEXT into TOK's donor pre-tokenizer pieces, as a list of strings."
  (let* ((preds (nl-llm-qwen-tok--preds tok))
         (v (string-to-vector text)) (n (length v)) (i 0) (out nil))
    (while (< i n)
      (let ((j (nl-llm-qwen-tok--next-piece preds v n i)))
        (unless (> j i)
          (error "nl-llm-qwen-tok: pre-tokenizer made no progress at %d" i))
        (push (concat (cl-subseq v i j)) out)
        (setq i j)))
    (nreverse out)))

;;; --- BPE ----------------------------------------------------------------

(defun nl-llm-qwen-tok--bpe (tok piece)
  "Return the token ids of PIECE (a string) under TOK's merge table."
  ;; utf-8-unix, not utf-8: the plain coding system applies EOL conversion and
  ;; would fold CRLF to LF, shifting every id after a Windows line ending.
  (let* ((bytes (encode-coding-string piece 'utf-8-unix))
         (byte->id (nl-llm-qwen-tok-byte->id tok))
         (merges (nl-llm-qwen-tok-merges tok))
         (n (length bytes))
         (ids (make-vector n 0)))
    (dotimes (k n) (aset ids k (aref byte->id (aref bytes k))))
    (let ((len n) (again t))
      (while (and again (> len 1))
        (setq again nil)
        (let ((best-rank nil) (best-at nil) (best-id nil) (k 0))
          (while (< k (1- len))
            (let ((hit (gethash (+ (* (aref ids k) nl-llm-qwen-tok--shift)
                                   (aref ids (1+ k)))
                                merges)))
              (when hit
                (let ((rank (/ hit nl-llm-qwen-tok--shift)))
                  (when (or (null best-rank) (< rank best-rank))
                    (setq best-rank rank best-at k
                          best-id (mod hit nl-llm-qwen-tok--shift))))))
            (setq k (1+ k)))
          (when best-at
            (aset ids best-at best-id)
            (let ((k (1+ best-at)))
              (while (< k (1- len))
                (aset ids k (aref ids (1+ k)))
                (setq k (1+ k))))
            (setq len (1- len) again t))))
      (cl-loop for k below len collect (aref ids k)))))

;;; --- public API ---------------------------------------------------------

(defun nl-llm-qwen-tok--split-added (tok text)
  "Split TEXT on TOK's added tokens.
Returns a list of either strings (ordinary text) or integers (token ids).
This runs before normalisation, matching the reference implementation."
  (let ((added (nl-llm-qwen-tok-added tok))
        (n (length text)) (i 0) (start 0) (out nil))
    (while (< i n)
      ;; `compare-strings' returns t on equality, not 0 -- testing for 0 here
      ;; makes every special token tokenize as ordinary text, with no error.
      (let ((hit (cl-loop for (txt . id) in added
                          when (and (<= (+ i (length txt)) n)
                                    (eq t (compare-strings
                                           text i (+ i (length txt))
                                           txt nil nil)))
                          return (cons txt id))))
        (if hit
            (progn
              (when (> i start) (push (substring text start i) out))
              (push (cdr hit) out)
              (setq i (+ i (length (car hit))) start i))
          (setq i (1+ i)))))
    (when (> n start) (push (substring text start n) out))
    (nreverse out)))

;;;###autoload
(defun nl-llm-qwen-tok-encode (tok text)
  "Return the donor token ids of TEXT under TOK."
  (unless (fboundp 'ucs-normalize-NFC-string)
    (require 'ucs-normalize nil t))
  (unless (fboundp 'ucs-normalize-NFC-string)
    ;; Silently skipping NFC would shift ids for any decomposed input, which is
    ;; the class of bug this file exists to prevent.
    (error "nl-llm-qwen-tok-encode: NFC normalisation is unavailable"))
  (let ((out nil))
    (dolist (part (nl-llm-qwen-tok--split-added tok text))
      (if (integerp part)
          (push part out)
        (dolist (piece (nl-llm-qwen-tok-pretokenize
                        tok (ucs-normalize-NFC-string part)))
          (dolist (id (nl-llm-qwen-tok--bpe tok piece))
            (push id out)))))
    (nreverse out)))

;;;###autoload
(defun nl-llm-qwen-tok-decode (tok ids)
  "Return the text of token IDS under TOK."
  (let ((offs (nl-llm-qwen-tok-offs tok))
        (slots (nl-llm-qwen-tok-slot-of-id tok))
        (blob (nl-llm-qwen-tok-blob tok))
        (parts nil))
    (dolist (id ids)
      (let ((slot (and (< id (length slots)) (aref slots id))))
        (unless slot
          (error "nl-llm-qwen-tok-decode: id %d has no token" id))
        (push (substring blob (aref offs slot) (aref offs (1+ slot))) parts)))
    (decode-coding-string (apply #'concat (nreverse parts)) 'utf-8-unix)))

(provide 'nl-llm-qwen-tokenizer)
;;; nl-llm-qwen-tokenizer.el ends here
