;;; agent-gpu-finetune-demo.el --- P5 scale: fine-tune agent trajectories on the GPU  -*- lexical-binding: t; -*-
;; The self-improvement fine-tune step scales to the GPU.  Given the agent's
;; successful trajectories (correct synthesised actions for a bank of tasks), an
;; nlga model is trained on them ON-DEVICE (CE + Adam -- the same gradient engine
;; behind train-*-gpu) and the loss drops.  This is the path from the CPU autograd
;; loop (which already closes end-to-end) to GPU-scale training of the agent on its
;; own wins; wiring the GPU-trained weights back into the rollout decoder closes the
;; whole loop on-device (the next integration).  Needs a Vulkan device.
;;   emacs -Q --batch -L lisp -L ../nelisp-photon/lisp -l examples/agent-gpu-finetune-demo.el
(add-to-list 'load-path (expand-file-name "lisp"))
(add-to-list 'load-path (expand-file-name "../nelisp-photon/lisp"))
(require 'cl-lib)
(require 'photon-tensor)
(require 'nl-llm-agent-model)
(require 'nl-llm-gpu)
(require 'nl-llm-gpu-ag)
(require 'nl-llm-gpu-decode)

(defun gd--t (shape seed sc) (let ((n 1)) (dolist (d shape) (setq n (* n d)))
  (photon-tensor shape (let ((v (make-vector n 0.0)) (i 0))
    (while (< i n) (aset v i (* sc 2.0 (- (/ (float (mod (+ (* (1+ i) 2654435761) (* (1+ seed) 40503)) 65536)) 65536.0) 0.5))) (setq i (1+ i))) v))))
(defun gd--ones (n) (photon-tensor (list n) (make-vector n 1.0)))
(defun gd--zeros (shape) (let ((n 1)) (dolist (d shape) (setq n (* n d))) (photon-tensor shape (make-vector n 0.0))))
(defun gd--encode (s seq) (let ((toks (make-vector seq 0)) (tgts (make-vector seq 0)) (cs (append s nil)) (i 0))
  (while (and cs (< i seq)) (aset toks i (nl-llm-agent--char->id (car cs))) (setq cs (cdr cs) i (1+ i)))
  (dotimes (j seq) (aset tgts j (if (< (1+ j) seq) (aref toks (1+ j)) 0))) (cons toks tgts)))
(defun gd--onehot (vec vocab) (let ((seq (length vec)) (v (make-vector (* (length vec) vocab) 0.0)))
  (dotimes (i seq) (aset v (+ (* i vocab) (aref vec i)) 1.0)) (photon-tensor (list seq vocab) v)))
(defun gd--ce (logits seq vocab targets) (let ((s 0.0)) (dotimes (i seq)
  (let ((mx -1e30) (z 0.0) (base (* i vocab)))
    (dotimes (c vocab) (when (> (aref logits (+ base c)) mx) (setq mx (aref logits (+ base c)))))
    (dotimes (c vocab) (setq z (+ z (exp (- (aref logits (+ base c)) mx)))))
    (setq s (+ s (- (- (aref logits (+ base (aref targets i))) mx) (log z)))))) (/ (- s) seq)))

(princ "=== P5 scale: fine-tuning the agent's trajectories on the GPU (nlga) ===\n")
(unless (nl-llm-gpu-enable) (princ "SKIP: no Vulkan device\n") (kill-emacs 0))
(let* ((vocab nl-llm-agent-char-vocab) (dim 24) (ff 24) (heads 2) (kvh 2) (hd (/ dim heads)) (kvdim (* kvh hd))
       (nblocks 1) (seq 40) (scl (/ 1.0 (sqrt (float hd)))) (sc (/ 1.0 (sqrt (float dim)))) (lr 0.05)
       (trajs (mapcar (lambda (s) (gd--encode s seq))
                      '("```elisp\n(defun f235 (x) (* x 2))\n```" "```elisp\n(defun f235 (x) (* x 3))\n```"
                        "```elisp\n(defun f235 (x) (* x 4))\n```" "```elisp\n(defun f235 (x) (* x 5))\n```")))
       (tables (nl-llm-gpu-rope-tables seq hd))
       (mkblk (lambda (s0) (list :ln1g (gd--ones dim) :wq (gd--t (list dim dim) (+ s0 1) sc) :bq (gd--zeros (list dim))
                                 :wk (gd--t (list kvdim dim) (+ s0 2) sc) :bk (gd--zeros (list kvdim))
                                 :wv (gd--t (list kvdim dim) (+ s0 3) sc) :bv (gd--zeros (list kvdim))
                                 :wo (gd--t (list dim dim) (+ s0 4) sc) :bo (gd--zeros (list dim)) :ln2g (gd--ones dim)
                                 :wg (gd--t (list ff dim) (+ s0 5) sc) :bg (gd--zeros (list ff))
                                 :wu (gd--t (list ff dim) (+ s0 6) sc) :bu (gd--zeros (list ff))
                                 :wd (gd--t (list dim ff) (+ s0 7) sc) :bd (gd--zeros (list dim)))))
       (b (nlga-new)))
  (princ (format "model on-device: blocks=%d dim=%d heads=%d/%d ff=%d seq=%d vocab=%d | %d trajectories\n\n"
                 nblocks dim heads kvh ff seq vocab (length trajs)))
  (cl-flet ((wp (tn) (nlga-param b tn))
            (wb (bt) (let ((out nil) (kv bt)) (while kv (push (car kv) out) (push (nlga-param b (cadr kv)) out) (setq kv (cddr kv))) (nreverse out))))
    (let* ((oh (nlga-const b (gd--onehot (car (car trajs)) vocab)))
           (ohtgt (nlga-const b (gd--onehot (cdr (car trajs)) vocab)))
           (wter (wp (gd--t (list vocab dim) 99 sc)))
           (blks (let ((l nil) (n 0)) (while (< n nblocks) (push (wb (funcall mkblk (* (1+ n) 100))) l) (setq n (1+ n))) (nreverse l)))
           (lnfgr (wp (gd--ones dim))) (whr (wp (gd--t (list vocab dim) 9 sc))) (bhr (wp (gd--zeros (list vocab))))
           (cosr (nlga-const b (car tables))) (sinr (nlga-const b (cdr tables)))
           (sposr (nlga-scalar b 1.0)) (snegr (nlga-scalar b -1.0)) (sclr (nlga-scalar b scl)) (oner (nlga-scalar b 1.0))
           (maskr (nlga-const b (let ((md (make-vector (* seq seq) 0.0)) (i 0))
                                  (while (< i seq) (let ((j (1+ i))) (while (< j seq) (aset md (+ (* i seq) j) -1.0e30) (setq j (1+ j)))) (setq i (1+ i))) (photon-tensor (list seq seq) md))))
           (lrr (nlga-scalar b lr))
           (logits (nlga-model b oh wter blks lnfgr whr bhr heads kvh cosr sinr sposr snegr sclr maskr))
           (lout (nlga-keep b logits oner)) (nt (length trajs)) (losses nil))
      (nlga-seed-ce b logits ohtgt) (nlga-finish b lrr) (nlga-compile b)
      (let ((s 0) (steps 60))
        (while (< s steps)
          (let ((tr (nth (mod s nt) trajs)))
            (nlga-update oh (gd--onehot (car tr) vocab))
            (nlga-update ohtgt (gd--onehot (cdr tr) vocab))
            (let ((ce (gd--ce (nth lout (nlga-step b)) seq vocab (cdr tr))))
              (push ce losses)
              (when (or (= (% s 12) 0) (= s (1- steps))) (princ (format "  step %2d  trajectory CE = %.3f\n" s ce))))
            (setq s (1+ s)))))
      (nlga-free b) (nl-llm-gpu-disable)
      (setq losses (nreverse losses))
      (let ((f (/ (apply #'+ (cl-subseq losses 0 nt)) nt))
            (l (/ (apply #'+ (last losses nt)) nt)))
        (princ (format "\ntrajectory CE on GPU: %.3f -> %.3f\n" f l))
        (princ (format "nlga fine-tunes the agent's trajectories on the GPU: %s\n" (if (< l (* 0.6 f)) "YES (loss dropped)" "NO")))
        (kill-emacs (if (< l (* 0.6 f)) 0 1))))))
;;; agent-gpu-finetune-demo.el ends here
