;;; bench-gpu.el --- CPU vs GPU wall-clock for the modern block  -*- lexical-binding: t; -*-
;; Measures, at a few model sizes, the time for:
;;   - inference: one full forward (steady state; weights resident on GPU)
;;   - training:  one forward+backward+SGD step (weights re-uploaded each step)
;; and prints a CPU-vs-GPU table.  Honest: inference is where residency pays
;; off; training re-encodes the (mutated) weights every step.
;;   emacs -Q --batch -L lisp -L ../nelisp-photon/lisp -l examples/bench-gpu.el
(add-to-list 'load-path (expand-file-name "lisp"))
(add-to-list 'load-path (expand-file-name "../nelisp-photon/lisp"))
(require 'cl-lib)
(require 'photon-tensor)
(require 'photon-autograd)
(require 'nl-llm-arch) (require 'nl-llm-attn) (require 'nl-llm-moe) (require 'nl-llm-block)
(require 'nl-llm-autograd)
(require 'nl-llm-gpu)

(defun b--t (shape seed sc)
  (let ((n 1)) (dolist (d shape) (setq n (* n d)))
    (photon-tensor-from-list
     shape
     (mapcar (lambda (i) (* sc 2.0 (- (/ (float (mod (+ (* (1+ i) 2654435761) (* (1+ seed) 40503)) 65536))
                                         65536.0) 0.5)))
             (number-sequence 0 (1- n))))))
(defun b--ones (n) (photon-tensor-create (list n) 1.0))
(defmacro b--ms (&rest body) `(let ((t0 (float-time))) ,@body (* 1000.0 (- (float-time) t0))))
(defun b--avg (reps thunk) (let ((s 0.0) (r 0)) (while (< r reps) (setq s (+ s (b--ms (funcall thunk)))) (setq r (1+ r))) (/ s reps)))

(defun b--fwd-model (vocab dim ff heads kvh sc)
  (let* ((hd (/ dim heads)) (kvdim (* kvh hd))
         (block (list :ln1g (b--ones dim) :wq (b--t (list dim dim) 2 sc)
                      :wk (b--t (list kvdim dim) 3 sc) :wv (b--t (list kvdim dim) 4 sc)
                      :wo (b--t (list dim dim) 5 sc) :ln2g (b--ones dim)
                      :wg (b--t (list ff dim) 6 sc) :wu (b--t (list ff dim) 7 sc)
                      :wd (b--t (list dim ff) 8 sc))))
    (list :wte (b--t (list vocab dim) 1 sc) :blocks (list block) :lnf (b--ones dim)
          :head (b--t (list vocab dim) 9 sc) :dim dim :heads heads :kv-heads kvh)))

(defun b--train-thunk (vocab dim ff heads kvh sc seq)
  "Return a closure that runs one forward+backward+SGD+invalidate step."
  (cl-flet ((p (shape seed) (photon-autograd-const (b--t shape seed sc)))
            (ones (n) (photon-autograd-const (b--ones n)))
            (zeros (n) (photon-autograd-const (photon-tensor-create (list n) 0.0))))
    (let* ((hd (/ dim heads)) (kvdim (* kvh hd))
           (wte (p (list vocab dim) 1)) (ln1g (ones dim))
           (Wq (p (list dim dim) 2)) (bq (zeros dim)) (Wk (p (list kvdim dim) 3)) (bk (zeros kvdim))
           (Wv (p (list kvdim dim) 4)) (bv (zeros kvdim)) (Wo (p (list dim dim) 5)) (bo (zeros dim))
           (ln2g (ones dim))
           (Wg (p (list ff dim) 6)) (bg (zeros ff)) (Wu (p (list ff dim) 7)) (bu (zeros ff))
           (Wd (p (list dim ff) 8)) (bd (zeros dim))
           (lnfg (ones dim)) (Wh (p (list vocab dim) 9)) (bh (zeros vocab))
           (block (list :ln1g ln1g :wq Wq :bq bq :wk Wk :bk bk :wv Wv :bv bv :wo Wo :bo bo
                        :ln2g ln2g :wg Wg :bg bg :wu Wu :bu bu :wd Wd :bd bd))
           (params (list wte ln1g Wq bq Wk bk Wv bv Wo bo ln2g Wg bg Wu bu Wd bd lnfg Wh bh))
           (toks (number-sequence 1 seq)) (tgts (apply #'vector (number-sequence 2 (1+ seq)))))
      (lambda ()
        (photon-autograd-reset-tape)
        (let* ((x (photon-autograd-embedding wte toks dim))
               (h (nl-llm-ag-block x block heads kvh))
               (xf (nl-llm-ag-rmsnorm h lnfg))
               (l (photon-autograd-softmax-ce (photon-autograd-linear xf Wh bh) tgts)))
          (photon-autograd-zero-grad params)
          (photon-autograd-backward l)
          (photon-autograd-sgd params 0.1)
          (nl-llm-gpu-invalidate params))))))

(let ((have-gpu (nl-llm-gpu-enable)))
  (photon-tensor-use-cpu-backend)        ; start from CPU; toggle per measurement
  (unless have-gpu (princ "(no GPU server -- CPU-only timings)\n"))
  (princ (format "%-22s %10s %10s %8s\n" "config" "CPU ms" "GPU ms" "speedup"))
  (dolist (cfg '((64 2 1) (128 4 2) (256 8 4)))
    (let* ((dim (nth 0 cfg)) (heads (nth 1 cfg)) (kvh (nth 2 cfg))
           (ff (* 4 dim)) (vocab 256) (seq 16) (sc (/ 1.0 (sqrt (float dim))))
           (model (b--fwd-model vocab dim ff heads kvh sc))
           (toks (number-sequence 1 seq)))
      ;; inference
      (photon-tensor-use-cpu-backend)
      (let ((cpu (b--avg 5 (lambda () (nl-llm-model-forward model toks)))))
        (if (not have-gpu)
            (princ (format "%-22s %10.1f %10s %8s\n" (format "infer dim=%d" dim) cpu "-" "-"))
          (photon-tensor-use-gpu-backend)
          (nl-llm-model-forward model toks)             ; warm up resident weights
          (let ((gpu (b--avg 5 (lambda () (nl-llm-model-forward model toks)))))
            (princ (format "%-22s %10.1f %10.1f %7.2fx\n" (format "infer dim=%d" dim) cpu gpu (/ cpu gpu))))))
      ;; training (one step = fwd+bwd+sgd)
      (photon-tensor-use-cpu-backend)
      (let* ((cpu-step (b--train-thunk vocab dim ff heads kvh sc seq))
             (cpu (b--avg 3 cpu-step)))
        (if (not have-gpu)
            (princ (format "%-22s %10.1f %10s %8s\n" (format "train dim=%d" dim) cpu "-" "-"))
          (photon-tensor-use-gpu-backend)
          (let* ((gpu-step (b--train-thunk vocab dim ff heads kvh sc seq))
                 (gpu (b--avg 3 gpu-step)))
            (princ (format "%-22s %10.1f %10.1f %7.2fx\n" (format "train dim=%d" dim) cpu gpu (/ cpu gpu))))))))
  (when have-gpu (nl-llm-gpu-disable)))
(princ "BENCH-GPU done\n")
;;; bench-gpu.el ends here
