;;; checkpoint-gpu.el --- train, checkpoint, restart, reload, generate  -*- lexical-binding: t; -*-
;; Demonstrates checkpointing: train a weight-tied model on-device, save a
;; checkpoint, STOP the GPU server, then load the checkpoint from disk, restart
;; the GPU, and generate from the loaded weights with the on-GPU KV-cache decode.
;; A correct round-trip reproduces the memorised passage from the reloaded model.
;;   emacs -Q --batch -L lisp -L ../nelisp-photon/lisp -l examples/checkpoint-gpu.el
(add-to-list 'load-path (expand-file-name "lisp"))
(add-to-list 'load-path (expand-file-name "../nelisp-photon/lisp"))
(require 'cl-lib)
(require 'photon-tensor)
(require 'photon-bpe)
(require 'nl-llm-ckpt)
(require 'nl-llm-gpu)
(require 'nl-llm-gpu-ag)
(require 'nl-llm-gpu-decode)

(defun cg--t (shape seed sc) (let ((n 1)) (dolist (d shape) (setq n (* n d)))
  (photon-tensor shape (let ((v (make-vector n 0.0)) (i 0))
    (while (< i n) (aset v i (* sc 2.0 (- (/ (float (mod (+ (* (1+ i) 2654435761) (* (1+ seed) 40503)) 65536)) 65536.0) 0.5))) (setq i (1+ i))) v))))
(defun cg--ones (n) (photon-tensor (list n) (make-vector n 1.0)))
(defun cg--zeros (sh) (let ((n 1)) (dolist (d sh) (setq n (* n d))) (photon-tensor sh (make-vector n 0.0))))
(defun cg--idx (ids start seq) (photon-tensor (list seq) (let ((v (make-vector seq 0.0))) (dotimes (i seq) (aset v i (float (aref ids (+ start i))))) v)))
(defun cg--argmax (d n) (let ((bi 0) (bv (aref d 0)) (j 1)) (while (< j n) (when (> (aref d j) bv) (setq bv (aref d j) bi j)) (setq j (1+ j))) bi))

(let* ((corpus (with-temp-buffer (insert-file-contents "data/corpus.txt") (buffer-string)))
       (bpe (photon-bpe-train (list corpus) 96))
       (ids (apply #'vector (photon-bpe-encode bpe corpus))) (vocab (photon-bpe-size bpe))
       (nblocks 2) (dim 64) (heads 4) (kvh 2) (ff 128) (seq 24) (steps 400) (plen 8) (lr 0.01)
       (hd (/ dim heads)) (kvdim (* kvh hd)) (sc (/ 1.0 (sqrt (float dim)))) (scl (/ 1.0 (sqrt (float hd))))
       (mkblk (lambda (s0) (list :ln1g (cg--ones dim) :wq (cg--t (list dim dim) (+ s0 1) sc) :bq (cg--zeros (list dim))
                                 :wk (cg--t (list kvdim dim) (+ s0 2) sc) :bk (cg--zeros (list kvdim))
                                 :wv (cg--t (list kvdim dim) (+ s0 3) sc) :bv (cg--zeros (list kvdim))
                                 :wo (cg--t (list dim dim) (+ s0 4) sc) :bo (cg--zeros (list dim)) :ln2g (cg--ones dim)
                                 :wg (cg--t (list ff dim) (+ s0 5) sc) :bg (cg--zeros (list ff))
                                 :wu (cg--t (list ff dim) (+ s0 6) sc) :bu (cg--zeros (list ff))
                                 :wd (cg--t (list dim ff) (+ s0 7) sc) :bd (cg--zeros (list dim)))))
       (wte (cg--t (list vocab dim) 99 sc)) (bh (cg--zeros (list vocab))) (lnfg (cg--ones dim))
       (blks (let ((l nil) (n 0)) (while (< n nblocks) (push (funcall mkblk (* (1+ n) 100)) l) (setq n (1+ n))) (nreverse l)))
       (tables (nl-llm-gpu-rope-tables seq hd))
       (mask (let ((md (make-vector (* seq seq) 0.0)) (i 0)) (while (< i seq) (let ((j (1+ i))) (while (< j seq) (aset md (+ (* i seq) j) -1.0e30) (setq j (1+ j)))) (setq i (1+ i))) (photon-tensor (list seq seq) md)))
       (ckpt (make-temp-file "nl-llm-ckpt" nil ".sexp")) (adam-st nil))
  (unless (nl-llm-gpu-enable) (princ "no GPU\n") (kill-emacs 0))
  ;; ---- train (memorise one window), readback, SAVE checkpoint ----
  (let* ((b (nlga-new)) (wb (lambda (bt) (let ((o nil) (kv bt)) (while kv (push (car kv) o) (push (nlga-param b (cadr kv)) o) (setq kv (cddr kv))) (nreverse o))))
         (tok (nlga-const b (cg--idx ids 0 seq))) (tgt (nlga-const b (cg--idx ids 1 seq)))
         (wter (nlga-param b wte)) (bhr (nlga-param b bh)) (gblks (mapcar wb blks)) (lnfgr (nlga-param b lnfg))
         (cosr (nlga-const b (car tables))) (sinr (nlga-const b (cdr tables)))
         (sposr (nlga-scalar b 1.0)) (snegr (nlga-scalar b -1.0)) (sclr (nlga-scalar b scl)) (oner (nlga-scalar b 1.0))
         (maskr (nlga-const b mask)) (x (nlga-embed b tok wter)))
    (dolist (g gblks) (setq x (nlga-block b x g heads kvh cosr sinr sposr snegr sclr maskr)))
    (let* ((xf (nlga-rmsnorm b x lnfgr)) (logits (nlga-linear b xf wter bhr)))
      (nlga-keep b logits oner) (nlga-seed-ce-idx b logits tgt)
      (nlga-finish-adam b lr 0.9 0.999 1.0e-8 1.0) (nlga-compile b))
    (let ((s 0)) (while (< s steps)
      (nlga-adam-update-t b (1+ s) (nl-llm-lr-warmup-cosine (1+ s) steps 20 lr 0.001))
      (nlga-step b) (setq s (1+ s))))
    (setq adam-st (nlga-adam-state b))   ; capture optimiser state for a complete resume
    (nlga-readback b) (nlga-free b))
  (nl-llm-ckpt-save ckpt (list :config (list :dim dim :heads heads :kv-heads kvh :ff ff :vocab vocab :nblocks nblocks :seq seq)
                               :step steps :wte wte :lnfg lnfg :bh bh :blocks blks :opt adam-st))
  (nl-llm-gpu-disable)                    ; stop the GPU entirely (simulate session end)
  (princ (format "saved checkpoint: %s (%d bytes)\n" (file-name-nondirectory ckpt) (nth 7 (file-attributes ckpt))))
  ;; ---- later: load the checkpoint, restart the GPU, generate from it ----
  (let* ((m (nl-llm-ckpt-load ckpt)) (cfg (plist-get m :config))
         (l-wte (plist-get m :wte)) (l-lnfg (plist-get m :lnfg)) (l-bh (plist-get m :bh)) (l-blks (plist-get m :blocks))
         (l-dim (plist-get cfg :dim)) (l-heads (plist-get cfg :heads)) (l-kvh (plist-get cfg :kv-heads))
         (l-vocab (plist-get cfg :vocab)) (l-seq (plist-get cfg :seq))
         (l-tables (nl-llm-gpu-rope-tables l-seq (/ l-dim l-heads)))
         (prompt (let ((l nil)) (dotimes (i plen) (push (aref ids i) l)) (nreverse l)))
         (orig (let ((l nil)) (dotimes (i l-seq) (push (aref ids i) l)) (nreverse l))))
    (nl-llm-gpu-enable)
    (let* ((ctx (nl-llm-gpu-decode-new l-wte l-blks l-lnfg l-bh l-heads l-kvh l-dim l-vocab l-seq l-tables))
           (gen (copy-sequence prompt)) (p 0))
      (while (< (length gen) l-seq)
        (let ((ld (nl-llm-gpu-decode-step ctx (nth p gen) p)))
          (when (>= (1+ p) plen) (setq gen (append gen (list (cg--argmax ld l-vocab)))))
          (setq p (1+ p))))
      (nl-llm-gpu-decode-free ctx) (nl-llm-gpu-disable)
      (let ((match (let ((mm 0) (i 0)) (while (< i l-seq) (when (= (nth i gen) (nth i orig)) (setq mm (1+ mm))) (setq i (1+ i))) mm)))
        (princ (format "reloaded step=%d config=%S\n" (plist-get m :step) cfg))
        (princ (format "prompt   : %S\n" (photon-bpe-decode bpe prompt)))
        (princ (format "generated: %S\n" (photon-bpe-decode bpe gen)))
        (princ (format "match    : %d/%d  %s\n" match l-seq (if (>= match (- l-seq 2)) "reproduced" "partial")))
        (princ (format "CHECKPOINT-GPU=%s\n" (if (>= match (- l-seq 2)) "PASS" "OK"))))))
  (delete-file ckpt))
;;; checkpoint-gpu.el ends here
