;;; spec-decode.el --- self-speculative decoding speedup with a trained MTP head  -*- lexical-binding: t; -*-
;; Trains a model on-device with an extra MTP look-ahead head H2 (predicting the
;; token two ahead), then decodes a prompt two ways on the CPU:
;;   plain greedy        -- one token per target forward
;;   self-speculative    -- draft with H2, verify with the main head (lossless)
;; and reports the mean tokens accepted per forward (the speedup) -- which is > 1
;; exactly when H2 has learned to look ahead.  The output is identical to plain
;; greedy by construction (checked here and pinned in test/spec-test.el).
;; Training is on the GPU; decode is CPU.  Skips (exit 0) without a Vulkan device.
;;   emacs -Q --batch -L lisp -L ../nelisp-photon/lisp -l examples/spec-decode.el
(add-to-list 'load-path (expand-file-name "lisp"))
(add-to-list 'load-path (expand-file-name "../nelisp-photon/lisp"))
(require 'cl-lib)
(require 'photon-tensor)
(require 'photon-bpe)
(require 'nl-llm-decode)
(require 'nl-llm-spec)
(require 'nl-llm-gpu)
(require 'nl-llm-gpu-ag)

(defun sp--t (shape seed sc) (let ((n 1)) (dolist (d shape) (setq n (* n d)))
  (photon-tensor shape (let ((v (make-vector n 0.0)) (i 0))
    (while (< i n) (aset v i (* sc 2.0 (- (/ (float (mod (+ (* (1+ i) 2654435761) (* (1+ seed) 40503)) 65536)) 65536.0) 0.5))) (setq i (1+ i))) v))))
(defun sp--ones (n) (photon-tensor (list n) (make-vector n 1.0)))
(defun sp--zeros (sh) (let ((n 1)) (dolist (d sh) (setq n (* n d))) (photon-tensor sh (make-vector n 0.0))))
(defun sp--idx (ids start seq) (photon-tensor (list seq) (let ((v (make-vector seq 0.0))) (dotimes (i seq) (aset v i (float (aref ids (+ start i))))) v)))

(unless (nl-llm-gpu-enable) (princ "NL-LLM-SPEC-DECODE SKIP (no GPU)\n") (kill-emacs 0))
(let* ((corpus (with-temp-buffer (insert-file-contents "data/corpus.txt") (buffer-string)))
       (bpe (photon-bpe-train (list corpus) 180))
       (ids (apply #'vector (photon-bpe-encode bpe corpus))) (ntok (length ids)) (vocab (photon-bpe-size bpe))
       (dim 64) (heads 4) (kvh 2) (ff 128) (nblocks 2) (seq 32)
       (steps 600) (warmup 40) (base-lr 0.006) (minlr 0.0006)
       (hd (/ dim heads)) (kvdim (* kvh hd)) (sc (/ 1.0 (sqrt (float dim)))) (span (- ntok seq 2))
       (mkblk (lambda (s0) (list :ln1g (sp--ones dim) :wq (sp--t (list dim dim) (+ s0 1) sc) :bq (sp--zeros (list dim))
                                 :wk (sp--t (list kvdim dim) (+ s0 2) sc) :bk (sp--zeros (list kvdim))
                                 :wv (sp--t (list kvdim dim) (+ s0 3) sc) :bv (sp--zeros (list kvdim))
                                 :wo (sp--t (list dim dim) (+ s0 4) sc) :bo (sp--zeros (list dim)) :ln2g (sp--ones dim)
                                 :wg (sp--t (list ff dim) (+ s0 5) sc) :bg (sp--zeros (list ff))
                                 :wu (sp--t (list ff dim) (+ s0 6) sc) :bu (sp--zeros (list ff))
                                 :wd (sp--t (list dim ff) (+ s0 7) sc) :bd (sp--zeros (list dim)))))
       (wte (sp--t (list vocab dim) 99 sc)) (bh (sp--zeros (list vocab))) (lnfg (sp--ones dim))
       (w2 (sp--t (list vocab dim) 77 sc)) (b2 (sp--zeros (list vocab)))   ; MTP look-ahead head
       (blks (let ((l nil) (n 0)) (while (< n nblocks) (push (funcall mkblk (* (1+ n) 1000)) l) (setq n (1+ n))) (nreverse l)))
       (tables (nl-llm-gpu-rope-tables seq hd)) (t0 (float-time)))
  (princ (format "training dim=%d blocks=%d seq=%d vocab=%d steps=%d (main head + MTP head)\n" dim nblocks seq vocab steps))
  (let* ((b (nlga-new))
         (wb (lambda (bt) (let ((o nil) (kv bt)) (while kv (push (car kv) o) (push (nlga-param b (cadr kv)) o) (setq kv (cddr kv))) (nreverse o))))
         (tok (nlga-const b (sp--idx ids 0 seq))) (tg1 (nlga-const b (sp--idx ids 1 seq))) (tg2 (nlga-const b (sp--idx ids 2 seq)))
         (wter (nlga-param b wte)) (bhr (nlga-param b bh)) (w2r (nlga-param b w2)) (b2r (nlga-param b b2))
         (gblks (mapcar wb blks)) (lnfgr (nlga-param b lnfg))
         (cosr (nlga-const b (car tables))) (sinr (nlga-const b (cdr tables)))
         (sposr (nlga-scalar b 1.0)) (snegr (nlga-scalar b -1.0)) (sclr (nlga-scalar b (/ 1.0 (sqrt (float hd))))) (oner (nlga-scalar b 1.0))
         (maskr (nlga-const b (let ((md (make-vector (* seq seq) 0.0)) (i 0)) (while (< i seq) (let ((j (1+ i))) (while (< j seq) (aset md (+ (* i seq) j) -1.0e30) (setq j (1+ j)))) (setq i (1+ i))) (photon-tensor (list seq seq) md))))
         (x (nlga-embed b tok wter)))
    (dolist (g gblks) (setq x (nlga-block b x g heads kvh cosr sinr sposr snegr sclr maskr)))
    (let* ((xf (nlga-rmsnorm b x lnfgr))
           (logits1 (nlga-linear b xf wter bhr))      ; main next-token head (tied)
           (logits2 (nlga-linear b xf w2r b2r)))      ; MTP two-ahead head
      (nlga-seed-ce-idx b logits1 tg1) (nlga-seed-ce-idx b logits2 tg2)
      (nlga-finish-adam b base-lr 0.9 0.999 1.0e-8 1.0) (nlga-compile b))
    (let ((s 0))
      (while (< s steps)
        (let ((start (% (* s 13) span)))
          (nlga-update tok (sp--idx ids start seq)) (nlga-update tg1 (sp--idx ids (1+ start) seq)) (nlga-update tg2 (sp--idx ids (+ start 2) seq))
          (nlga-adam-update-t b (1+ s) (nl-llm-lr-warmup-cosine (1+ s) steps warmup base-lr minlr))
          (nlga-step b))
        (setq s (1+ s))))
    (nlga-readback b) (nlga-free b))
  (nl-llm-gpu-disable)
  (princ (format "trained in %.0fs; decoding...\n" (- (float-time) t0)))
  (let* ((maxseq 96) (ngen 48) (start 200)
         (prompt (let ((p nil)) (dotimes (i 6) (push (aref ids (+ start i)) p)) (nreverse p)))
         (plain (nl-llm-greedy prompt ngen blks wte lnfg bh heads kvh dim vocab maxseq))
         (sr (nl-llm-spec-greedy prompt ngen blks wte lnfg bh w2 b2 heads kvh dim vocab maxseq))
         (spec (car sr)) (rounds (cdr sr)))
    (princ (format "prompt        : %S\n" (photon-bpe-decode bpe prompt)))
    (princ (format "plain greedy  : %S\n" (photon-bpe-decode bpe plain)))
    (princ (format "speculative   : %S\n" (photon-bpe-decode bpe spec)))
    (princ (format "lossless (spec == plain): %s\n" (if (equal spec plain) "YES" "NO!!")))
    (princ (format "speedup       : %d tokens / %d forwards = %.2fx tokens-per-forward\n"
                   ngen rounds (/ (float ngen) rounds))))
  (princ "NL-LLM-SPEC-DECODE=OK\n"))
;;; spec-decode.el ends here
