;;; spec-chain.el --- deep-tree (multi-MTP-head) chain speculative decode  -*- lexical-binding: t; -*-
;; Trains a model with several MTP look-ahead heads (head2..head4, predicting the
;; token 2/3/4 ahead), then chain-drafts a depth-D token chain and verifies the
;; whole chain in ONE GPU tree-verify forward, accepting the longest greedy match.
;; Shows the mean tokens-per-forward rising with draft depth -- all lossless
;; (== plain greedy).  Training on the GPU; decode uses GPU tree-verify.
;; Skips (exit 0) without a Vulkan device.
;;   emacs -Q --batch -L lisp -L ../nelisp-photon/lisp -l examples/spec-chain.el
(add-to-list 'load-path (expand-file-name "lisp"))
(add-to-list 'load-path (expand-file-name "../nelisp-photon/lisp"))
(require 'cl-lib)
(require 'photon-tensor)
(require 'photon-bpe)
(require 'nl-llm-decode)
(require 'nl-llm-spec)
(require 'nl-llm-gpu)
(require 'nl-llm-gpu-ag)
(require 'nl-llm-gpu-decode)

(defun pc--t (shape seed sc) (let ((n 1)) (dolist (d shape) (setq n (* n d)))
  (photon-tensor shape (let ((v (make-vector n 0.0)) (i 0))
    (while (< i n) (aset v i (* sc 2.0 (- (/ (float (mod (+ (* (1+ i) 2654435761) (* (1+ seed) 40503)) 65536)) 65536.0) 0.5))) (setq i (1+ i))) v))))
(defun pc--ones (n) (photon-tensor (list n) (make-vector n 1.0)))
(defun pc--zeros (sh) (let ((n 1)) (dolist (d sh) (setq n (* n d))) (photon-tensor sh (make-vector n 0.0))))
(defun pc--idx (ids start seq) (photon-tensor (list seq) (let ((v (make-vector seq 0.0))) (dotimes (i seq) (aset v i (float (aref ids (+ start i))))) v)))

(unless (nl-llm-gpu-enable) (princ "NL-LLM-SPEC-CHAIN-DEMO SKIP (no GPU)\n") (kill-emacs 0))
(let* ((corpus (with-temp-buffer (insert-file-contents "data/corpus.txt") (buffer-string)))
       (bpe (photon-bpe-train (list corpus) 180))
       (ids (apply #'vector (photon-bpe-encode bpe corpus))) (ntok (length ids)) (vocab (photon-bpe-size bpe))
       (dim 64) (heads 4) (kvh 2) (ff 128) (nblocks 2) (seq 32)
       (steps 600) (warmup 40) (base-lr 0.006) (minlr 0.0006)
       (hd (/ dim heads)) (kvdim (* kvh hd)) (sc (/ 1.0 (sqrt (float dim)))) (span (- ntok seq 5))
       (mkblk (lambda (s0) (list :ln1g (pc--ones dim) :wq (pc--t (list dim dim) (+ s0 1) sc) :bq (pc--zeros (list dim))
                                 :wk (pc--t (list kvdim dim) (+ s0 2) sc) :bk (pc--zeros (list kvdim))
                                 :wv (pc--t (list kvdim dim) (+ s0 3) sc) :bv (pc--zeros (list kvdim))
                                 :wo (pc--t (list dim dim) (+ s0 4) sc) :bo (pc--zeros (list dim)) :ln2g (pc--ones dim)
                                 :wg (pc--t (list ff dim) (+ s0 5) sc) :bg (pc--zeros (list ff))
                                 :wu (pc--t (list ff dim) (+ s0 6) sc) :bu (pc--zeros (list ff))
                                 :wd (pc--t (list dim ff) (+ s0 7) sc) :bd (pc--zeros (list dim)))))
       (wte (pc--t (list vocab dim) 99 sc)) (bh (pc--zeros (list vocab))) (lnfg (pc--ones dim))
       (w2 (pc--t (list vocab dim) 77 sc)) (b2 (pc--zeros (list vocab)))
       (w3 (pc--t (list vocab dim) 78 sc)) (b3 (pc--zeros (list vocab)))
       (w4 (pc--t (list vocab dim) 79 sc)) (b4 (pc--zeros (list vocab)))
       (blks (let ((l nil) (n 0)) (while (< n nblocks) (push (funcall mkblk (* (1+ n) 1000)) l) (setq n (1+ n))) (nreverse l)))
       (tables (nl-llm-gpu-rope-tables seq hd)) (t0 (float-time)))
  (princ (format "training dim=%d blocks=%d seq=%d vocab=%d steps=%d (head1 + MTP head2/3/4)\n" dim nblocks seq vocab steps))
  (let* ((b (nlga-new))
         (wb (lambda (bt) (let ((o nil) (kv bt)) (while kv (push (car kv) o) (push (nlga-param b (cadr kv)) o) (setq kv (cddr kv))) (nreverse o))))
         (tok (nlga-const b (pc--idx ids 0 seq)))
         (tg1 (nlga-const b (pc--idx ids 1 seq))) (tg2 (nlga-const b (pc--idx ids 2 seq)))
         (tg3 (nlga-const b (pc--idx ids 3 seq))) (tg4 (nlga-const b (pc--idx ids 4 seq)))
         (wter (nlga-param b wte)) (bhr (nlga-param b bh))
         (w2r (nlga-param b w2)) (b2r (nlga-param b b2)) (w3r (nlga-param b w3)) (b3r (nlga-param b b3)) (w4r (nlga-param b w4)) (b4r (nlga-param b b4))
         (gblks (mapcar wb blks)) (lnfgr (nlga-param b lnfg))
         (cosr (nlga-const b (car tables))) (sinr (nlga-const b (cdr tables)))
         (sposr (nlga-scalar b 1.0)) (snegr (nlga-scalar b -1.0)) (sclr (nlga-scalar b (/ 1.0 (sqrt (float hd))))) (oner (nlga-scalar b 1.0))
         (maskr (nlga-const b (let ((md (make-vector (* seq seq) 0.0)) (i 0)) (while (< i seq) (let ((j (1+ i))) (while (< j seq) (aset md (+ (* i seq) j) -1.0e30) (setq j (1+ j)))) (setq i (1+ i))) (photon-tensor (list seq seq) md))))
         (x (nlga-embed b tok wter)))
    (dolist (g gblks) (setq x (nlga-block b x g heads kvh cosr sinr sposr snegr sclr maskr)))
    (let* ((xf (nlga-rmsnorm b x lnfgr)))
      (nlga-seed-ce-idx b (nlga-linear b xf wter bhr) tg1)
      (nlga-seed-ce-idx b (nlga-linear b xf w2r b2r) tg2)
      (nlga-seed-ce-idx b (nlga-linear b xf w3r b3r) tg3)
      (nlga-seed-ce-idx b (nlga-linear b xf w4r b4r) tg4)
      (nlga-finish-adam b base-lr 0.9 0.999 1.0e-8 1.0) (nlga-compile b))
    (let ((s 0))
      (while (< s steps)
        (let ((start (% (* s 13) span)))
          (nlga-update tok (pc--idx ids start seq)) (nlga-update tg1 (pc--idx ids (1+ start) seq)) (nlga-update tg2 (pc--idx ids (+ start 2) seq))
          (nlga-update tg3 (pc--idx ids (+ start 3) seq)) (nlga-update tg4 (pc--idx ids (+ start 4) seq))
          (nlga-adam-update-t b (1+ s) (nl-llm-lr-warmup-cosine (1+ s) steps warmup base-lr minlr))
          (nlga-step b))
        (setq s (1+ s))))
    (nlga-readback b) (nlga-free b))
  (princ (format "trained in %.0fs; decoding (depth 2/3/4)...\n" (- (float-time) t0)))
  (let* ((maxseq 96) (ngen 40) (start 200) (maxdepth 8)
         (prompt (let ((p nil)) (dotimes (i 6) (push (aref ids (+ start i)) p)) (nreverse p)))
         (plain (nl-llm-greedy prompt ngen blks wte lnfg bh heads kvh dim vocab maxseq))
         (allh (list (cons w2 b2) (cons w3 b3) (cons w4 b4))))
    (dolist (depth '(2 3 4))
      (let* ((mtp (cl-subseq allh 0 (1- depth)))
             (cr (nl-llm-gpu-spec-chain-decode prompt ngen blks wte lnfg bh mtp heads kvh dim vocab maxseq tables maxdepth))
             (chain (car cr)) (forwards (cdr cr)))
        (princ (format "  depth %d : %.2f tok/fwd  (%d toks / %d verifies)  lossless=%s\n"
                       depth (/ (float ngen) forwards) ngen forwards (if (equal chain plain) "YES" "NO!!")))))
    (princ (format "prompt: %S\n  cont: %S\n" (photon-bpe-decode bpe prompt) (photon-bpe-decode bpe plain))))
  (nl-llm-gpu-disable)
  (princ "NL-LLM-SPEC-CHAIN-DEMO=OK\n"))
;;; spec-chain.el ends here
