;;; train-stacked-gpu.el --- train a multi-block model on-device  -*- lexical-binding: t; -*-
;; Trains a stacked N-block modern model (embedding + N x [RMSNorm + GQA/RoPE +
;; SwiGLU] + LM head) on a public-domain text window, fully on-device via the
;; resident-autograd builder: every weight stays resident on the GPU and the
;; whole forward + backward + SGD is one fused batch per step.  Prints the loss
;; curve and the steady-state per-step time.
;;   emacs -Q --batch -L lisp -L ../nelisp-photon/lisp -l examples/train-stacked-gpu.el
(add-to-list 'load-path (expand-file-name "lisp"))
(add-to-list 'load-path (expand-file-name "../nelisp-photon/lisp"))
(require 'cl-lib)
(require 'photon-tensor)
(require 'photon-bpe)
(require 'nl-llm-gpu)
(require 'nl-llm-gpu-ag)

(defun ts--t (shape seed sc) (let ((n 1)) (dolist (d shape) (setq n (* n d)))
  (photon-tensor shape (let ((v (make-vector n 0.0)) (i 0))
    (while (< i n) (aset v i (* sc 2.0 (- (/ (float (mod (+ (* (1+ i) 2654435761) (* (1+ seed) 40503)) 65536)) 65536.0) 0.5))) (setq i (1+ i))) v))))
(defun ts--ones (n) (photon-tensor (list n) (make-vector n 1.0)))
(defun ts--zeros (shape) (let ((n 1)) (dolist (d shape) (setq n (* n d))) (photon-tensor shape (make-vector n 0.0))))
(defun ts--ce (ld seq vocab tg) (let ((loss 0.0) (i 0))
  (while (< i seq) (let ((base (* i vocab)) (mx -1.0e30) (j 0))
    (while (< j vocab) (when (> (aref ld (+ base j)) mx) (setq mx (aref ld (+ base j)))) (setq j (1+ j)))
    (let ((s 0.0) (j2 0)) (while (< j2 vocab) (setq s (+ s (exp (- (aref ld (+ base j2)) mx)))) (setq j2 (1+ j2)))
      (setq loss (- loss (- (- (aref ld (+ base (aref tg i))) mx) (log s)))))) (setq i (1+ i))) (/ loss (float seq))))

(unless (nl-llm-gpu-enable)
  (princ "no GPU server / Vulkan device -- cannot run on-device demo\n") (kill-emacs 0))

(let* ((corpus (with-temp-buffer (insert-file-contents "data/corpus.txt") (buffer-string)))
       (bpe (photon-bpe-train (list corpus) 80))
       (ids (apply #'vector (photon-bpe-encode bpe corpus)))
       (vocab (photon-bpe-size bpe))
       (nblocks 2) (dim 64) (heads 4) (kvh 2) (ff 128) (seq 16) (steps 40) (lr 0.2)
       (hd (/ dim heads)) (kvdim (* kvh hd)) (sc (/ 1.0 (sqrt (float dim)))) (scl (/ 1.0 (sqrt (float hd))))
       (tokens (let ((v (make-vector seq 0))) (dotimes (i seq) (aset v i (aref ids i))) v))
       (targets (let ((v (make-vector seq 0))) (dotimes (i seq) (aset v i (aref ids (1+ i)))) v))
       (mkblk (lambda (s0)
                (list :ln1g (ts--ones dim) :wq (ts--t (list dim dim) (+ s0 1) sc) :bq (ts--zeros (list dim))
                      :wk (ts--t (list kvdim dim) (+ s0 2) sc) :bk (ts--zeros (list kvdim))
                      :wv (ts--t (list kvdim dim) (+ s0 3) sc) :bv (ts--zeros (list kvdim))
                      :wo (ts--t (list dim dim) (+ s0 4) sc) :bo (ts--zeros (list dim)) :ln2g (ts--ones dim)
                      :wg (ts--t (list ff dim) (+ s0 5) sc) :bg (ts--zeros (list ff))
                      :wu (ts--t (list ff dim) (+ s0 6) sc) :bu (ts--zeros (list ff))
                      :wd (ts--t (list dim ff) (+ s0 7) sc) :bd (ts--zeros (list dim)))))
       (wrap (lambda (b tn) (nlga-param b tn)))
       (tables (nl-llm-gpu-rope-tables seq hd))
       (oh-tok (let ((v (make-vector (* seq vocab) 0.0))) (dotimes (i seq) (aset v (+ (* i vocab) (aref tokens i)) 1.0)) (photon-tensor (list seq vocab) v)))
       (oh-tgt (let ((v (make-vector (* seq vocab) 0.0))) (dotimes (i seq) (aset v (+ (* i vocab) (aref targets i)) 1.0)) (photon-tensor (list seq vocab) v)))
       (mask (let ((md (make-vector (* seq seq) 0.0)) (i 0)) (while (< i seq) (let ((j (1+ i))) (while (< j seq) (aset md (+ (* i seq) j) -1.0e30) (setq j (1+ j)))) (setq i (1+ i))) (photon-tensor (list seq seq) md)))
       (b (nlga-new)))
  (cl-flet ((wp (tn) (nlga-param b tn)) (wb (bt) (let ((out nil) (kv bt)) (while kv (push (car kv) out) (push (nlga-param b (cadr kv)) out) (setq kv (cddr kv))) (nreverse out))))
    (let* ((oh (nlga-const b oh-tok)) (wter (wp (ts--t (list vocab dim) 99 sc)))
           (blks (let ((l nil) (n 0)) (while (< n nblocks) (push (wb (funcall mkblk (* (1+ n) 100))) l) (setq n (1+ n))) (nreverse l)))
           (lnfgr (wp (ts--ones dim))) (whr (wp (ts--t (list vocab dim) 9 sc))) (bhr (wp (ts--zeros (list vocab))))
           (cosr (nlga-const b (car tables))) (sinr (nlga-const b (cdr tables)))
           (sposr (nlga-scalar b 1.0)) (snegr (nlga-scalar b -1.0)) (sclr (nlga-scalar b scl)) (oner (nlga-scalar b 1.0))
           (maskr (nlga-const b mask)) (ohtgt (nlga-const b oh-tgt)) (lrr (nlga-scalar b lr))
           (logits (nlga-model b oh wter blks lnfgr whr bhr heads kvh cosr sinr sposr snegr sclr maskr))
           (lout (nlga-keep b logits oner)) (losses nil) (t0 nil) (tn nil))
      (nlga-seed-ce b logits ohtgt) (nlga-finish b lrr) (nlga-compile b)
      (princ (format "stacked model on-device: blocks=%d dim=%d heads=%d kv=%d ff=%d seq=%d vocab=%d\n"
                     nblocks dim heads kvh ff seq vocab))
      (let ((s 0))
        (while (< s steps)
          (when (= s 1) (setq t0 (float-time)))   ; time from step 1 (skip warm-up)
          (let ((l (ts--ce (nth lout (nlga-step b)) seq vocab targets)))
            (push l losses)
            (when (or (= (% s 5) 0) (= s (1- steps))) (princ (format "step %2d  loss=%.4f\n" s l))))
          (setq s (1+ s)))
        (setq tn (float-time)))
      (nlga-free b) (nl-llm-gpu-disable)
      (setq losses (nreverse losses))
      (princ (format "first=%.4f last=%.4f  per-step=%.1f ms (steps 1..%d)\n"
                     (car losses) (car (last losses)) (/ (* 1000.0 (- tn t0)) (1- steps)) (1- steps)))
      (princ (format "TRAIN-STACKED-GPU=%s\n" (if (< (car (last losses)) (car losses)) "PASS" "FAIL"))))))
;;; train-stacked-gpu.el ends here
