;;; train-full-gpu.el --- full recipe: corpus + clip + dropout + sampling  -*- lexical-binding: t; -*-
;; The whole on-device recipe in one run: train a weight-tied stacked model over
;; sliding windows of a public-domain corpus with Adam + warmup/cosine LR +
;; global-norm gradient clipping + dropout (mask refreshed each step), all
;; resident on the GPU; then generate with an O(len) KV-cache decode using both
;; greedy and high-temperature top-k sampling.  Dropout is train-only: the decode
;; forward omits it (inverted dropout keeps E[mask]=1, so no eval rescale).
;;   emacs -Q --batch -L lisp -L ../nelisp-photon/lisp -l examples/train-full-gpu.el
(add-to-list 'load-path (expand-file-name "lisp"))
(add-to-list 'load-path (expand-file-name "../nelisp-photon/lisp"))
(require 'cl-lib)
(require 'photon-tensor)
(require 'photon-bpe)
(require 'nl-llm-block)    ; nl-llm-sample, nl-llm-dropout-mask
(require 'nl-llm-decode)
(require 'nl-llm-gpu)
(require 'nl-llm-gpu-ag)

(defun tf--t (shape seed sc) (let ((n 1)) (dolist (d shape) (setq n (* n d)))
  (photon-tensor shape (let ((v (make-vector n 0.0)) (i 0))
    (while (< i n) (aset v i (* sc 2.0 (- (/ (float (mod (+ (* (1+ i) 2654435761) (* (1+ seed) 40503)) 65536)) 65536.0) 0.5))) (setq i (1+ i))) v))))
(defun tf--ones (n) (photon-tensor (list n) (make-vector n 1.0)))
(defun tf--zeros (sh) (let ((n 1)) (dolist (d sh) (setq n (* n d))) (photon-tensor sh (make-vector n 0.0))))
(defun tf--idx (ids start seq) (photon-tensor (list seq) (let ((v (make-vector seq 0.0))) (dotimes (i seq) (aset v i (float (aref ids (+ start i))))) v)))
(defun tf--ce (ld ids start seq vocab) (let ((loss 0.0) (i 0))
  (while (< i seq) (let ((base (* i vocab)) (mx -1.0e30) (j 0) (tg (aref ids (+ start i 1))))
    (while (< j vocab) (when (> (aref ld (+ base j)) mx) (setq mx (aref ld (+ base j)))) (setq j (1+ j)))
    (let ((s 0.0) (j2 0)) (while (< j2 vocab) (setq s (+ s (exp (- (aref ld (+ base j2)) mx)))) (setq j2 (1+ j2)))
      (setq loss (- loss (- (- (aref ld (+ base tg)) mx) (log s)))))) (setq i (1+ i))) (/ loss (float seq))))
(defun tf--argmax (data n) (let ((bi 0) (bv (aref data 0)) (j 1)) (while (< j n) (when (> (aref data j) bv) (setq bv (aref data j) bi j)) (setq j (1+ j))) bi))

(unless (nl-llm-gpu-enable)
  (princ "no GPU server / Vulkan device\n") (kill-emacs 0))

(let* ((corpus (with-temp-buffer (insert-file-contents "data/corpus.txt") (buffer-string)))
       (bpe (photon-bpe-train (list corpus) 96))
       (ids (apply #'vector (photon-bpe-encode bpe corpus))) (ntok (length ids)) (vocab (photon-bpe-size bpe))
       (nblocks 2) (dim 64) (heads 4) (kvh 2) (ff 128) (seq 32) (steps 600)
       (base-lr 0.008) (warmup 30) (minlr 0.0008) (clip 1.0) (drop-p 0.1) (plen 8) (ngen 24)
       (hd (/ dim heads)) (kvdim (* kvh hd)) (sc (/ 1.0 (sqrt (float dim)))) (scl (/ 1.0 (sqrt (float hd))))
       (span (- ntok seq 1))
       (mkblk (lambda (s0) (list :ln1g (tf--ones dim) :wq (tf--t (list dim dim) (+ s0 1) sc) :bq (tf--zeros (list dim))
                                 :wk (tf--t (list kvdim dim) (+ s0 2) sc) :bk (tf--zeros (list kvdim))
                                 :wv (tf--t (list kvdim dim) (+ s0 3) sc) :bv (tf--zeros (list kvdim))
                                 :wo (tf--t (list dim dim) (+ s0 4) sc) :bo (tf--zeros (list dim)) :ln2g (tf--ones dim)
                                 :wg (tf--t (list ff dim) (+ s0 5) sc) :bg (tf--zeros (list ff))
                                 :wu (tf--t (list ff dim) (+ s0 6) sc) :bu (tf--zeros (list ff))
                                 :wd (tf--t (list dim ff) (+ s0 7) sc) :bd (tf--zeros (list dim)))))
       (wte (tf--t (list vocab dim) 99 sc)) (bh (tf--zeros (list vocab))) (lnfg (tf--ones dim))
       (blks (let ((l nil) (n 0)) (while (< n nblocks) (push (funcall mkblk (* (1+ n) 100)) l) (setq n (1+ n))) (nreverse l)))
       (tables (nl-llm-gpu-rope-tables seq hd))
       (mask (let ((md (make-vector (* seq seq) 0.0)) (i 0)) (while (< i seq) (let ((j (1+ i))) (while (< j seq) (aset md (+ (* i seq) j) -1.0e30) (setq j (1+ j)))) (setq i (1+ i))) (photon-tensor (list seq seq) md)))
       (b (nlga-new)))
  (random "nl-llm-full-seed")
  ;; ---- train on-device: gather + tied + Adam + sched + clip + dropout ----
  (cl-flet ((wb (bt) (let ((o nil) (kv bt)) (while kv (push (car kv) o) (push (nlga-param b (cadr kv)) o) (setq kv (cddr kv))) (nreverse o))))
    (let* ((tok (nlga-const b (tf--idx ids 0 seq))) (tgt (nlga-const b (tf--idx ids 1 seq)))
           (wter (nlga-param b wte)) (bhr (nlga-param b bh)) (gblks (mapcar #'wb blks)) (lnfgr (nlga-param b lnfg))
           (cosr (nlga-const b (car tables))) (sinr (nlga-const b (cdr tables)))
           (sposr (nlga-scalar b 1.0)) (snegr (nlga-scalar b -1.0)) (sclr (nlga-scalar b scl)) (oner (nlga-scalar b 1.0))
           (maskr (nlga-const b mask))
           ;; dropout masks (refreshed each step): one after embedding, one per block
           (dmasks (let ((l nil) (k 0)) (while (<= k nblocks) (push (nlga-const b (nl-llm-dropout-mask (list seq dim) drop-p)) l) (setq k (1+ k))) (nreverse l)))
           (x (nlga-dropout b (nlga-embed b tok wter) (car dmasks))) (dm (cdr dmasks)) (recent nil) (t0 nil) (tn nil) (first-avg nil) (lout nil))
      (dolist (g gblks)
        (setq x (nlga-dropout b (nlga-block b x g heads kvh cosr sinr sposr snegr sclr maskr) (car dm)))
        (setq dm (cdr dm)))
      (let* ((xf (nlga-rmsnorm b x lnfgr)) (logits (nlga-linear b xf wter bhr)))
        (setq lout (nlga-keep b logits oner))
        (nlga-seed-ce-idx b logits tgt) (nlga-finish-adam b base-lr 0.9 0.999 1.0e-8 clip) (nlga-compile b))
      (princ (format "full recipe: blocks=%d dim=%d ff=%d seq=%d vocab=%d steps=%d clip=%.1f drop=%.2f (tied,Adam,cosine)\n"
                     nblocks dim ff seq vocab steps clip drop-p))
      (let ((s 0))
        (while (< s steps)
          (when (= s 1) (setq t0 (float-time)))
          (let ((start (% (* s 13) span)))
            (nlga-update tok (tf--idx ids start seq))
            (nlga-update tgt (tf--idx ids (1+ start) seq))
            (dolist (dmsk dmasks) (nlga-update dmsk (nl-llm-dropout-mask (list seq dim) drop-p)))
            (nlga-adam-update-t b (1+ s) (nl-llm-lr-warmup-cosine (1+ s) steps warmup base-lr minlr))
            (let ((l (tf--ce (nth lout (nlga-step b)) ids start seq vocab)))
              (push l recent) (when (> (length recent) 30) (setcdr (nthcdr 29 recent) nil))
              (when (= s 29) (setq first-avg (/ (apply #'+ recent) (length recent))))
              (when (or (= (% s 100) 0) (= s (1- steps)))
                (princ (format "step %3d  loss=%.4f (avg30=%.4f)\n" s l (/ (apply #'+ recent) (length recent)))))))
          (setq s (1+ s))))
      (setq tn (float-time))
      (nlga-readback b) (nlga-free b)
      (let ((last-avg (/ (apply #'+ recent) (length recent))))
        (princ (format "avg30 loss: first=%.4f last=%.4f  per-step=%.1f ms\n"
                       (or first-avg 0.0) last-avg (/ (* 1000.0 (- tn t0)) (1- steps)))))))
  (nl-llm-gpu-disable)
  ;; ---- generate via KV-cache decode (no dropout) ----
  (let* ((maxlen (+ plen ngen))
         (prompt (let ((l nil)) (dotimes (i plen) (push (aref ids i) l)) (nreverse l))))
    (cl-flet ((generate (pick)
                (let ((caches (mapcar (lambda (_) (nl-llm-dcache-new maxlen dim heads kvh)) blks))
                      (gen (copy-sequence prompt)) (p 0))
                  (while (< (length gen) maxlen)
                    (let ((ld (nl-llm-decode-step (nth p gen) blks caches wte lnfg bh dim)))
                      (when (>= (1+ p) plen) (setq gen (append gen (list (funcall pick ld vocab)))))
                      (setq p (1+ p))))
                  gen)))
      (let ((greedy (generate (lambda (d v) (tf--argmax d v)))))
        (random "nl-llm-full-gen-seed")
        (let ((sampled (generate (lambda (d v) (nl-llm-sample d 0 v 1.0 40)))))
          (princ (format "prompt        : %S\n" (photon-bpe-decode bpe prompt)))
          (princ (format "greedy        : %S\n" (photon-bpe-decode bpe greedy)))
          (princ (format "sampled(T1.0) : %S\n" (photon-bpe-decode bpe sampled)))
          (princ "TRAIN-FULL-GPU=OK\n"))))))
;;; train-full-gpu.el ends here
