;;; train-big-gpu.el --- a real(er) training run with checkpoint + resume  -*- lexical-binding: t; -*-
;; Capstone run exercising the whole stack at scale: a weight-tied 4-block model
;; (dim 128, GQA) trained over a corpus on-device with Adam + warmup/cosine LR +
;; gradient clipping + dropout; checkpointed mid-run; the GPU is then stopped, the
;; checkpoint reloaded (weights + Adam state + step), and training RESUMES
;; seamlessly; finally several prompts are batch-generated with sampling.
;;   emacs -Q --batch -L lisp -L ../nelisp-photon/lisp -l examples/train-big-gpu.el
(add-to-list 'load-path (expand-file-name "lisp"))
(add-to-list 'load-path (expand-file-name "../nelisp-photon/lisp"))
(require 'cl-lib)
(require 'photon-tensor)
(require 'photon-bpe)
(require 'nl-llm-block)     ; nl-llm-sample, nl-llm-dropout-mask
(require 'nl-llm-ckpt)
(require 'nl-llm-gpu)
(require 'nl-llm-gpu-ag)
(require 'nl-llm-gpu-decode)

(defun bg--t (shape seed sc) (let ((n 1)) (dolist (d shape) (setq n (* n d)))
  (photon-tensor shape (let ((v (make-vector n 0.0)) (i 0))
    (while (< i n) (aset v i (* sc 2.0 (- (/ (float (mod (+ (* (1+ i) 2654435761) (* (1+ seed) 40503)) 65536)) 65536.0) 0.5))) (setq i (1+ i))) v))))
(defun bg--ones (n) (photon-tensor (list n) (make-vector n 1.0)))
(defun bg--zeros (sh) (let ((n 1)) (dolist (d sh) (setq n (* n d))) (photon-tensor sh (make-vector n 0.0))))
(defun bg--idx (ids start seq) (photon-tensor (list seq) (let ((v (make-vector seq 0.0))) (dotimes (i seq) (aset v i (float (aref ids (+ start i))))) v)))
(defun bg--ce (ld ids start seq vocab) (let ((loss 0.0) (i 0))
  (while (< i seq) (let ((base (* i vocab)) (mx -1.0e30) (j 0) (tg (aref ids (+ start i 1))))
    (while (< j vocab) (when (> (aref ld (+ base j)) mx) (setq mx (aref ld (+ base j)))) (setq j (1+ j)))
    (let ((s 0.0) (j2 0)) (while (< j2 vocab) (setq s (+ s (exp (- (aref ld (+ base j2)) mx)))) (setq j2 (1+ j2)))
      (setq loss (- loss (- (- (aref ld (+ base tg)) mx) (log s)))))) (setq i (1+ i))) (/ loss (float seq))))

;; train STEPS windows; mutates the weight tensors via readback; returns (:opt :last)
(defun bg--train (ids cfg tables mask wte blocks lnfg bh steps t0 total warmup base-lr minlr clip drop-p restore-opt)
  (let* ((dim (plist-get cfg :dim)) (heads (plist-get cfg :heads)) (kvh (plist-get cfg :kv-heads))
         (seq (plist-get cfg :seq)) (vocab (plist-get cfg :vocab)) (span (plist-get cfg :span))
         (scl (/ 1.0 (sqrt (float (/ dim heads)))))
         (b (nlga-new))
         (wb (lambda (bt) (let ((o nil) (kv bt)) (while kv (push (car kv) o) (push (nlga-param b (cadr kv)) o) (setq kv (cddr kv))) (nreverse o))))
         (tok (nlga-const b (bg--idx ids 0 seq))) (tgt (nlga-const b (bg--idx ids 1 seq)))
         (wter (nlga-param b wte)) (bhr (nlga-param b bh)) (gblks (mapcar wb blocks)) (lnfgr (nlga-param b lnfg))
         (cosr (nlga-const b (car tables))) (sinr (nlga-const b (cdr tables)))
         (sposr (nlga-scalar b 1.0)) (snegr (nlga-scalar b -1.0)) (sclr (nlga-scalar b scl)) (oner (nlga-scalar b 1.0))
         (maskr (nlga-const b mask))
         (dmasks (let ((l nil) (k 0)) (while (<= k (length blocks)) (push (nlga-const b (nl-llm-dropout-mask (list seq dim) drop-p)) l) (setq k (1+ k))) (nreverse l)))
         (x (nlga-dropout b (nlga-embed b tok wter) (car dmasks))) (dm (cdr dmasks)) (lout nil) (recent nil))
    (dolist (g gblks) (setq x (nlga-dropout b (nlga-block b x g heads kvh cosr sinr sposr snegr sclr maskr) (car dm))) (setq dm (cdr dm)))
    (let* ((xf (nlga-rmsnorm b x lnfgr)) (logits (nlga-linear b xf wter bhr)))
      (setq lout (nlga-keep b logits oner))
      (nlga-seed-ce-idx b logits tgt) (nlga-finish-adam b base-lr 0.9 0.999 1.0e-8 clip) (nlga-compile b))
    (when restore-opt (nlga-adam-restore b restore-opt))
    (let ((s 0))
      (while (< s steps)
        (let ((start (% (* (+ t0 s) 13) span)) (gt (+ t0 s 1)))
          (nlga-update tok (bg--idx ids start seq))
          (nlga-update tgt (bg--idx ids (1+ start) seq))
          (dolist (dmsk dmasks) (nlga-update dmsk (nl-llm-dropout-mask (list seq dim) drop-p)))
          (nlga-adam-update-t b gt (nl-llm-lr-warmup-cosine gt total warmup base-lr minlr))
          (let ((l (bg--ce (nth lout (nlga-step b)) ids start seq vocab)))
            (push l recent) (when (> (length recent) 40) (setcdr (nthcdr 39 recent) nil))
            (when (= (% gt 100) 0) (princ (format "  step %4d  loss=%.4f (avg40=%.4f)\n" gt l (/ (apply #'+ recent) (length recent)))))))
        (setq s (1+ s))))
    (let ((opt (nlga-adam-state b)) (last (/ (apply #'+ recent) (length recent))))
      (nlga-readback b) (nlga-free b)
      (list :opt opt :last last))))

(unless (nl-llm-gpu-enable) (princ "no GPU\n") (kill-emacs 0))
(let* ((corpus (with-temp-buffer (insert-file-contents "data/corpus.txt") (buffer-string)))
       (bpe (photon-bpe-train (list corpus) 200))
       (ids (apply #'vector (photon-bpe-encode bpe corpus))) (ntok (length ids)) (vocab (photon-bpe-size bpe))
       (dim 128) (heads 8) (kvh 4) (ff 512) (nblocks 4) (seq 48)
       (n1 400) (n2 400) (total (+ n1 n2)) (warmup 40) (base-lr 0.006) (minlr 0.0006) (clip 1.0) (drop-p 0.1)
       (hd (/ dim heads)) (kvdim (* kvh hd)) (sc (/ 1.0 (sqrt (float dim)))) (span (- ntok seq 1))
       (cfg (list :dim dim :heads heads :kv-heads kvh :ff ff :seq seq :vocab vocab :nblocks nblocks :span span))
       (mkblk (lambda (s0) (list :ln1g (bg--ones dim) :wq (bg--t (list dim dim) (+ s0 1) sc) :bq (bg--zeros (list dim))
                                 :wk (bg--t (list kvdim dim) (+ s0 2) sc) :bk (bg--zeros (list kvdim))
                                 :wv (bg--t (list kvdim dim) (+ s0 3) sc) :bv (bg--zeros (list kvdim))
                                 :wo (bg--t (list dim dim) (+ s0 4) sc) :bo (bg--zeros (list dim)) :ln2g (bg--ones dim)
                                 :wg (bg--t (list ff dim) (+ s0 5) sc) :bg (bg--zeros (list ff))
                                 :wu (bg--t (list ff dim) (+ s0 6) sc) :bu (bg--zeros (list ff))
                                 :wd (bg--t (list dim ff) (+ s0 7) sc) :bd (bg--zeros (list dim)))))
       (wte (bg--t (list vocab dim) 99 sc)) (bh (bg--zeros (list vocab))) (lnfg (bg--ones dim))
       (blks (let ((l nil) (n 0)) (while (< n nblocks) (push (funcall mkblk (* (1+ n) 1000)) l) (setq n (1+ n))) (nreverse l)))
       (tables (nl-llm-gpu-rope-tables seq hd))
       (mask (let ((md (make-vector (* seq seq) 0.0)) (i 0)) (while (< i seq) (let ((j (1+ i))) (while (< j seq) (aset md (+ (* i seq) j) -1.0e30) (setq j (1+ j)))) (setq i (1+ i))) (photon-tensor (list seq seq) md)))
       (ckpt (make-temp-file "nl-llm-big" nil ".sexp")) (t0 (float-time)))
  (random "nl-llm-big-seed")
  (princ (format "BIG RUN: dim=%d heads=%d kv=%d ff=%d blocks=%d seq=%d vocab=%d tokens=%d  total=%d steps (clip,dropout,cosine,tied)\n"
                 dim heads kvh ff nblocks seq vocab ntok total))
  ;; ---- phase 1 ----
  (princ "phase 1 (fresh):\n")
  (let ((r1 (bg--train ids cfg tables mask wte blks lnfg bh n1 0 total warmup base-lr minlr clip drop-p nil)))
    (nl-llm-ckpt-save ckpt (list :config cfg :step n1 :wte wte :lnfg lnfg :bh bh :blocks blks :opt (plist-get r1 :opt)))
    (nl-llm-gpu-disable)                         ; stop the GPU: simulate end of a session
    (princ (format "  -> checkpoint at step %d (%.1f MB), GPU stopped\n" n1 (/ (nth 7 (file-attributes ckpt)) 1048576.0))))
  ;; ---- resume: reload checkpoint, restart GPU, continue ----
  (princ "phase 2 (resumed from checkpoint):\n")
  (nl-llm-gpu-enable)
  (let* ((m (nl-llm-ckpt-load ckpt)) (l-wte (plist-get m :wte)) (l-lnfg (plist-get m :lnfg)) (l-bh (plist-get m :bh))
         (l-blks (plist-get m :blocks)) (l-opt (plist-get m :opt))
         (r2 (bg--train ids cfg tables mask l-wte l-blks l-lnfg l-bh n2 n1 total warmup base-lr minlr clip drop-p l-opt)))
    (nl-llm-ckpt-save ckpt (list :config cfg :step total :wte l-wte :lnfg l-lnfg :bh l-bh :blocks l-blks :opt (plist-get r2 :opt)))
    (princ (format "  -> final loss avg40=%.4f, %.0fs elapsed\n" (plist-get r2 :last) (- (float-time) t0)))
    ;; ---- batch generation from the trained model ----
    (let* ((bsz 4) (plen 6) (ngen 18) (maxlen (+ plen ngen))
           (gtab (nl-llm-gpu-rope-tables maxlen hd))
           (starts (vector 0 200 600 1200))
           (gens (let ((l nil)) (dotimes (s bsz) (push (let ((p nil)) (dotimes (i plen) (push (aref ids (+ (aref starts s) i)) p)) (nreverse p)) l)) (nreverse l)))
           (gens (apply #'vector gens))
           (ctx (nl-llm-gpu-decode-batch-new l-wte l-blks l-lnfg l-bh heads kvh dim vocab maxlen bsz gtab)))
      (random "nl-llm-big-gen")
      (let ((p 0))
        (while (< p (1- maxlen))
          (let ((row (make-vector bsz 0))) (dotimes (s bsz) (aset row s (nth p (aref gens s))))
            (let ((logits (nl-llm-gpu-decode-batch-step ctx row p)))
              (when (>= (1+ p) plen)
                (dotimes (s bsz)
                  (let ((nxt (nl-llm-sample logits (* s vocab) vocab 0.8 30)))
                    (aset gens s (append (aref gens s) (list nxt))))))))
          (setq p (1+ p))))
      (nl-llm-gpu-decode-free ctx) (nl-llm-gpu-disable)
      (princ "batch sampled generations (T0.8, top-k30):\n")
      (dotimes (s bsz) (princ (format "  [%d] %S\n" s (photon-bpe-decode bpe (aref gens s)))))))
  (delete-file ckpt)
  (princ "TRAIN-BIG-GPU=OK\n"))
;;; train-big-gpu.el ends here
