;;; train-modern.el --- train a modern (RMSNorm/RoPE/SwiGLU) block directly  -*- lexical-binding: t; -*-
;; Trains a modern transformer block built entirely from nl-llm autograd ops
;; (RMSNorm + RoPE single-head attention + SwiGLU) on public-domain text, and
;; shows the loss decreasing -- i.e. the modern block is directly trainable
;; (not via the GPT baseline).  CPU path.
;;   emacs -Q --batch -L lisp -L ../nelisp-photon/lisp -l examples/train-modern.el
(add-to-list 'load-path (expand-file-name "lisp"))
(add-to-list 'load-path (expand-file-name "../nelisp-photon/lisp"))
(require 'cl-lib)
(require 'photon-tensor)
(require 'photon-bpe)
(require 'photon-autograd)
(require 'nl-llm-autograd)

(defun tm--p (shape seed scale)
  (let ((n 1)) (dolist (d shape) (setq n (* n d)))
    (photon-autograd-const
     (photon-tensor-from-list
      shape
      (mapcar (lambda (i)
                (* scale 2.0
                   (- (/ (float (mod (+ (* (1+ i) 2654435761) (* (1+ seed) 40503)) 65536))
                         65536.0) 0.5)))
              (number-sequence 0 (1- n)))))))
(defun tm--ones (n) (photon-autograd-const (photon-tensor-create (list n) 1.0)))
(defun tm--zeros (n) (photon-autograd-const (photon-tensor-create (list n) 0.0)))

(let* ((corpus (with-temp-buffer (insert-file-contents "data/corpus.txt") (buffer-string)))
       (bpe (photon-bpe-train (list corpus) 100))
       (ids (apply #'vector (photon-bpe-encode bpe corpus)))
       (ntok (length ids)) (vocab (photon-bpe-size bpe))
       (dim 16) (ff 32) (seq 12) (steps 30) (lr 0.3) (heads 1)
       (sc (/ 1.0 (sqrt (float dim))))
       (wte (tm--p (list vocab dim) 1 sc))
       (ln1g (tm--ones dim))
       (Wq (tm--p (list dim dim) 2 sc)) (bq (tm--zeros dim))
       (Wk (tm--p (list dim dim) 3 sc)) (bk (tm--zeros dim))
       (Wv (tm--p (list dim dim) 4 sc)) (bv (tm--zeros dim))
       (Wo (tm--p (list dim dim) 5 sc)) (bo (tm--zeros dim))
       (ln2g (tm--ones dim))
       (Wg (tm--p (list ff dim) 6 sc)) (bg (tm--zeros ff))
       (Wu (tm--p (list ff dim) 7 sc)) (bu (tm--zeros ff))
       (Wd (tm--p (list dim ff) 8 sc)) (bd (tm--zeros dim))
       (lnfg (tm--ones dim))
       (Wh (tm--p (list vocab dim) 9 sc)) (bh (tm--zeros vocab))
       (params (list wte ln1g Wq bq Wk bk Wv bv Wo bo ln2g
                     Wg bg Wu bu Wd bd lnfg Wh bh))
       (mask (let ((md (make-vector (* seq seq) 0.0)) (i 0))
               (while (< i seq)
                 (let ((j (1+ i)))
                   (while (< j seq) (aset md (+ (* i seq) j) -1.0e30) (setq j (1+ j))))
                 (setq i (1+ i)))
               (photon-autograd-const (photon-tensor (list seq seq) md))))
       (losses nil))
  (cl-flet ((forward (toks targets)
              (photon-autograd-reset-tape)
              (let* ((x (photon-autograd-embedding wte toks dim))
                     (a (nl-llm-ag-rmsnorm x ln1g))
                     (q (nl-llm-ag-rope (photon-autograd-linear a Wq bq) heads))
                     (k (nl-llm-ag-rope (photon-autograd-linear a Wk bk) heads))
                     (v (photon-autograd-linear a Wv bv))
                     (s (photon-autograd-scale
                         (photon-autograd-matmul q (photon-autograd-transpose k)) sc))
                     (p (photon-autograd-softmax-rows (photon-autograd-add s mask)))
                     (ctx (photon-autograd-matmul p v))
                     (x1 (photon-autograd-add x (photon-autograd-linear ctx Wo bo)))
                     (b (nl-llm-ag-rmsnorm x1 ln2g))
                     (mout (nl-llm-ag-swiglu b Wg bg Wu bu Wd bd))
                     (x2 (photon-autograd-add x1 mout))
                     (xf (nl-llm-ag-rmsnorm x2 lnfg))
                     (logits (photon-autograd-linear xf Wh bh)))
                (photon-autograd-softmax-ce logits targets)))
            (window (start)
              (let ((toks nil) (tgts (make-vector seq 0)) (j 0))
                (while (< j seq)
                  (push (aref ids (+ start j)) toks)
                  (aset tgts j (aref ids (+ start j 1)))
                  (setq j (1+ j)))
                (cons (nreverse toks) tgts)))
            (lval (l) (aref (photon-tensor-data (pav-value l)) 0)))
    (princ (format "modern block: dim=%d ff=%d seq=%d heads=%d vocab=%d (RMSNorm+RoPE+SwiGLU)\n"
                   dim ff seq heads vocab))
    (let ((span (- ntok seq 1)) (step 0))
      (while (< step steps)
        (let* ((start (% (* step 7) span)) (w (window start))
               (l (forward (car w) (cdr w))) (loss (lval l)))
          (push loss losses)
          (photon-autograd-zero-grad params)
          (photon-autograd-backward l)
          (photon-autograd-sgd params lr)
          (when (or (= (% step 5) 0) (= step (1- steps)))
            (princ (format "step %2d  loss=%.4f\n" step loss))))
        (setq step (1+ step))))
    (setq losses (nreverse losses))
    (let* ((first5 (/ (apply #'+ (cl-subseq losses 0 5)) 5.0))
           (last5 (/ (apply #'+ (last losses 5)) 5.0)))
      (princ (format "mean loss: first5=%.4f last5=%.4f\n" first5 last5))
      (princ (format "TRAIN-MODERN=%s\n" (if (< last5 first5) "PASS" "FAIL")))
      (kill-emacs (if (< last5 first5) 0 1)))))
;;; train-modern.el ends here
