;;; train-open.el --- train a tiny transformer on fully-open text  -*- lexical-binding: t; -*-
;; End-to-end training demo: BPE-tokenize a public-domain corpus, build a tiny
;; 1-layer transformer with photon-autograd, run several SGD steps over text
;; windows, and show the loss decreasing.  CPU path (no GPU needed).
;;   emacs -Q --batch -L lisp -L ../nelisp-photon/lisp -l examples/train-open.el
(add-to-list 'load-path (expand-file-name "lisp"))
(add-to-list 'load-path (expand-file-name "../nelisp-photon/lisp"))
(require 'cl-lib)
(require 'photon-tensor)
(require 'photon-bpe)
(require 'photon-autograd)

(defun to--p (shape seed scale)
  (let ((n 1)) (dolist (d shape) (setq n (* n d)))
    (photon-autograd-const
     (photon-tensor-from-list
      shape
      (mapcar (lambda (i)
                (* scale 2.0
                   (- (/ (float (mod (+ (* (1+ i) 2654435761) (* (1+ seed) 40503)) 65536))
                         65536.0) 0.5)))
              (number-sequence 0 (1- n)))))))
(defun to--ones (n) (photon-autograd-const (photon-tensor-create (list n) 1.0)))
(defun to--zeros (n) (photon-autograd-const (photon-tensor-create (list n) 0.0)))

(let* ((corpus (with-temp-buffer (insert-file-contents "data/corpus.txt") (buffer-string)))
       (bpe (photon-bpe-train (list corpus) 100))
       (ids (apply #'vector (photon-bpe-encode bpe corpus)))
       (ntok (length ids))
       (vocab (photon-bpe-size bpe))
       (dim 16) (ff 32) (seq 12) (steps 30) (lr 0.3)
       (sc (/ 1.0 (sqrt (float dim))))
       (wte (to--p (list vocab dim) 1 sc))
       (ln1g (to--ones dim)) (ln1b (to--zeros dim))
       (Wq (to--p (list dim dim) 2 sc)) (bq (to--zeros dim))
       (Wk (to--p (list dim dim) 3 sc)) (bk (to--zeros dim))
       (Wv (to--p (list dim dim) 4 sc)) (bv (to--zeros dim))
       (Wo (to--p (list dim dim) 5 sc)) (bo (to--zeros dim))
       (ln2g (to--ones dim)) (ln2b (to--zeros dim))
       (W1 (to--p (list ff dim) 6 sc)) (b1 (to--zeros ff))
       (W2 (to--p (list dim ff) 7 sc)) (b2 (to--zeros dim))
       (lnfg (to--ones dim)) (lnfb (to--zeros dim))
       (Wh (to--p (list vocab dim) 8 sc)) (bh (to--zeros vocab))
       (params (list wte ln1g ln1b Wq bq Wk bk Wv bv Wo bo
                     ln2g ln2b W1 b1 W2 b2 lnfg lnfb Wh bh))
       (mask (let ((md (make-vector (* seq seq) 0.0)) (i 0))
               (while (< i seq)
                 (let ((j (1+ i)))
                   (while (< j seq) (aset md (+ (* i seq) j) -1.0e30) (setq j (1+ j))))
                 (setq i (1+ i)))
               (photon-autograd-const (photon-tensor (list seq seq) md))))
       (losses nil))
  (cl-flet ((forward (toks targets)
              (photon-autograd-reset-tape)
              (let* ((x (photon-autograd-embedding wte toks dim))
                     (a (photon-autograd-layernorm-rows x ln1g ln1b))
                     (q (photon-autograd-linear a Wq bq))
                     (k (photon-autograd-linear a Wk bk))
                     (v (photon-autograd-linear a Wv bv))
                     (s (photon-autograd-scale
                         (photon-autograd-matmul q (photon-autograd-transpose k)) sc))
                     (p (photon-autograd-softmax-rows (photon-autograd-add s mask)))
                     (ctx (photon-autograd-matmul p v))
                     (x1 (photon-autograd-add x (photon-autograd-linear ctx Wo bo)))
                     (c (photon-autograd-layernorm-rows x1 ln2g ln2b))
                     (h (photon-autograd-gelu (photon-autograd-linear c W1 b1)))
                     (x2 (photon-autograd-add x1 (photon-autograd-linear h W2 b2)))
                     (xf (photon-autograd-layernorm-rows x2 lnfg lnfb))
                     (logits (photon-autograd-linear xf Wh bh)))
                (photon-autograd-softmax-ce logits targets)))
            (window (start)
              (let ((toks nil) (tgts (make-vector seq 0)) (j 0))
                (while (< j seq)
                  (push (aref ids (+ start j)) toks)
                  (aset tgts j (aref ids (+ start j 1)))
                  (setq j (1+ j)))
                (cons (nreverse toks) tgts)))
            (lval (l) (aref (photon-tensor-data (pav-value l)) 0)))
    (princ (format "corpus chars=%d tokens=%d vocab=%d  model dim=%d ff=%d seq=%d\n"
                   (length corpus) ntok vocab dim ff seq))
    (let ((span (- ntok seq 1)) (step 0))
      (while (< step steps)
        (let* ((start (% (* step 7) span)) (w (window start))
               (l (forward (car w) (cdr w))) (loss (lval l)))
          (push loss losses)
          (photon-autograd-zero-grad params)
          (photon-autograd-backward l)
          (photon-autograd-sgd params lr)
          (when (or (= (% step 5) 0) (= step (1- steps)))
            (princ (format "step %2d  loss=%.4f\n" step loss))))
        (setq step (1+ step))))
    (setq losses (nreverse losses))
    (let* ((first5 (/ (apply #'+ (cl-subseq losses 0 5)) 5.0))
           (last5 (/ (apply #'+ (last losses 5)) 5.0)))
      (princ (format "mean loss: first5=%.4f last5=%.4f\n" first5 last5))
      (princ (format "TRAIN-OPEN=%s\n" (if (< last5 first5) "PASS" "FAIL")))
      (kill-emacs (if (< last5 first5) 0 1)))))
;;; train-open.el ends here
