#!/usr/bin/env python3
"""Emit sampled rows of an exported weight table as a parity fixture.

Doc 08 Phase 2c.  The Elisp reader in lisp/nl-llm-weights.el has to unpack int8
lanes, pick the right per-row scale, and decode f32 from bytes.  Each of those
can be wrong in a way that still produces numbers, so the fixture carries, per
sampled row, the lanes as integers AND the dequantized values, and the Elisp
suite compares both: integers catch a mis-indexed unpack, floats catch a wrong
scale or a broken f32 decode.

The dequantized values are computed in float64, not float32, on purpose.
int8 * f32_scale can need more than 24 mantissa bits, so a float32 product
would differ from Emacs's float64 arithmetic on the same inputs and the
comparison would have to carry a tolerance -- which is exactly the slack a real
indexing bug hides in.  In float64 both sides are bit-identical.  (The GPU will
multiply in f32; that is Phase 2d's business, not the reader's.)

Usage:
    PYTHONPATH=build/donor/pylibs python3 tools/qwen-weights-rows.py \\
        TABLE_FILE OUT.eld
"""

import struct
import sys

import numpy as np

MAGIC = b"nl-llm-wts-v1" + b"\0" * 3

# (role, layer, row) triples worth sampling: both ends of the layer stack, every
# role, first/last/middle rows, and rows whose width is not a multiple of four
# would be interesting if any existed (none do here -- all widths are).
SAMPLES = [
    (":wte", -1, 0), (":wte", -1, 1), (":wte", -1, 151935),
    (":wq", 0, 0), (":wq", 0, 2047), (":wq", 27, 1024),
    (":wk", 0, 0), (":wv", 13, 511), (":wo", 27, 0),
    (":wg", 0, 3071), (":wu", 13, 0), (":wd", 27, 1023),
    (":ln1g", 0, 0), (":ln2g", 27, 0), (":lnf", -1, 0),
    (":q-norm", 0, 0), (":k-norm", 27, 0),
]


def read_table(path):
    with open(path, "rb") as fh:
        if fh.read(16) != MAGIC:
            raise SystemExit(f"{path}: bad magic")
        (hlen,) = struct.unpack("<I", fh.read(4))
        text = fh.read(hlen).decode("utf-8")
    payload_at = 16 + 4 + hlen

    entries = {}
    for chunk in text.split("(:name ")[1:]:
        body = chunk.rsplit(")", 1)[0] if chunk.endswith(")") else chunk
        fields = {"name": body.split('"')[1],
                  "role": body.split(":role ", 1)[1].split()[0],
                  "kind": body.split(':kind "', 1)[1].split('"', 1)[0],
                  "shape": [int(v) for v in body.split(":shape (", 1)[1]
                            .split(")", 1)[0].split()]}
        for key in ("offset", "nbytes", "words", "scale-offset", "layer"):
            fields[key] = int(body.split(f":{key} ", 1)[1].split()[0].rstrip(")"))
        entries[(fields["role"], fields["layer"])] = fields
    return payload_at, entries


def main(table, out_path):
    payload_at, entries = read_table(table)
    blob = np.memmap(table, dtype=np.uint8, mode="r")

    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write(";; -*- lisp-data -*-  AUTO-GENERATED by "
                 "tools/qwen-weights-rows.py -- do not edit.\n")
        fh.write(";; Per sample: (:role R :layer L :row I :kind K :cols N\n")
        fh.write(";;              :scale S :lanes (...) :values (...))\n")
        fh.write(";; :values are float64 products of the int8 lane and the f32\n")
        fh.write(";; scale, so Emacs can compare them exactly.\n(\n")
        n = 0
        for role, layer, row in SAMPLES:
            e = entries.get((role, layer))
            if e is None:
                raise SystemExit(f"table has no {role} at layer {layer}")
            shape = e["shape"]
            rows = shape[0]
            cols = shape[1] if len(shape) > 1 else shape[0]
            if e["kind"] == "f32":
                # A rank-1 tensor is one row; a rank-2 one is indexed.
                base = payload_at + e["offset"]
                if len(shape) > 1:
                    base += 4 * cols * row
                vals = np.frombuffer(
                    bytes(blob[base:base + 4 * cols]), dtype=np.float32)
                lanes = []
                scale = 1.0
                vals64 = vals.astype(np.float64)
            else:
                if row >= rows:
                    raise SystemExit(f"{role}[{layer}] row {row} >= {rows}")
                stride = 4 * e["words"]
                base = payload_at + e["offset"] + row * stride
                lanes = np.frombuffer(bytes(blob[base:base + stride]),
                                      dtype=np.int8)[:cols]
                sbase = payload_at + e["scale-offset"] + 4 * row
                scale = float(np.frombuffer(bytes(blob[sbase:sbase + 4]),
                                            dtype=np.float32)[0])
                vals64 = lanes.astype(np.float64) * np.float64(scale)
            fh.write(f" (:role {role} :layer {layer} :row {row}"
                     f' :kind "{e["kind"]}" :cols {cols}\n')
            fh.write(f"  :scale {scale!r}\n")
            fh.write("  :lanes (" + " ".join(str(int(v)) for v in lanes) + ")\n")
            fh.write("  :values (" + " ".join(repr(float(v)) for v in vals64)
                     + "))\n")
            n += 1
        fh.write(")\n")
    print(f"wrote {out_path}: {n} sampled rows")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    main(sys.argv[1], sys.argv[2])
