#!/usr/bin/env python3
"""Reference forward over an imported weight table, as a parity fixture.

Doc 08 Phase 2c, Verification check 4: "Run the donor under a reference
implementation with a fixed prompt, dump per-layer hidden states, and compare
the Elisp forward layer by layer.  Compare the FIRST diverging layer, not just
the logits -- a single transposed weight or a wrong head_dim shows up as a
specific layer, whereas the logits only say 'wrong'."

This reference reads the SAME int8 table the Elisp side reads and dequantizes
it the same way, so a difference cannot be blamed on quantization: it isolates
the forward arithmetic.  Comparing against the original bf16 safetensors would
conflate the two.

The architecture is Qwen3's, written out rather than imported: RMSNorm without
mean subtraction, QK-norm per head before the rotation, half-split (rotate_half)
RoPE, grouped-query attention with a head width independent of dim/heads, and a
SwiGLU feed-forward.  Each of those was a place the Elisp side was wrong once.

Usage:
    PYTHONPATH=build/donor/pylibs python3 tools/qwen-forward-ref.py \\
        TABLE_FILE OUT.eld [TOKENS...] [--layers N]
"""

import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from nlwts import Table  # noqa: E402

DEFAULT_TOKENS = [14990, 1879]   # "hello world" under the donor's tokenizer
DEFAULT_LAYERS = 2


def rmsnorm(x, gain, eps):
    """x * rsqrt(mean(x^2) + eps) * gain, over the last axis."""
    ms = np.mean(x * x, axis=-1, keepdims=True)
    return x / np.sqrt(ms + eps) * gain


def rope_half(v, positions, base):
    """Half-split RoPE over (seq, heads, hd), the rotate_half convention.

    cos/sin are built from inv_freq = base ** -(2i/hd) for i < hd/2 and then
    duplicated, so element i and element i + hd/2 share an angle -- which is
    what makes the pairing half-split rather than adjacent.
    """
    hd = v.shape[-1]
    half = hd // 2
    inv = base ** (-np.arange(0, half, dtype=np.float64) * 2.0 / hd)
    ang = positions[:, None] * inv[None, :]          # (seq, half)
    cos = np.concatenate([np.cos(ang), np.cos(ang)], axis=-1)[:, None, :]
    sin = np.concatenate([np.sin(ang), np.sin(ang)], axis=-1)[:, None, :]
    rot = np.concatenate([-v[..., half:], v[..., :half]], axis=-1)
    return v * cos + rot * sin


def attend(q, k, v, heads, kv_heads, hd):
    """Causal GQA over (seq, heads, hd) and (seq, kv_heads, hd)."""
    seq = q.shape[0]
    grp = heads // kv_heads
    scale = 1.0 / np.sqrt(hd)
    ctx = np.zeros((seq, heads, hd), dtype=np.float64)
    for h in range(heads):
        kh = h // grp
        scores = q[:, h, :] @ k[:, kh, :].T * scale          # (seq, seq)
        mask = np.triu(np.ones((seq, seq), dtype=bool), 1)
        scores = np.where(mask, -np.inf, scores)
        scores = scores - scores.max(axis=-1, keepdims=True)
        w = np.exp(scores)
        w = w / w.sum(axis=-1, keepdims=True)
        ctx[:, h, :] = w @ v[:, kh, :]
    return ctx


def main(table_path, out_path, tokens, nlayers):
    tb = Table(table_path)
    cfg = tb.config
    dim, heads = cfg["dim"], cfg["heads"]
    kv_heads, hd = cfg["kv-heads"], cfg["head-dim"]
    eps, base = cfg["rms-eps"], cfg["rope-base"]
    seq = len(tokens)
    positions = np.arange(seq, dtype=np.float64)

    x = tb.rows(":wte", tokens)                      # (seq, dim)
    states = [x.copy()]

    for ly in range(nlayers):
        a = rmsnorm(x, tb.f32(":ln1g", ly), eps)
        q = (a @ tb.dequant(":wq", ly).T).reshape(seq, heads, hd)
        k = (a @ tb.dequant(":wk", ly).T).reshape(seq, kv_heads, hd)
        v = (a @ tb.dequant(":wv", ly).T).reshape(seq, kv_heads, hd)
        q = rmsnorm(q, tb.f32(":q-norm", ly), eps)
        k = rmsnorm(k, tb.f32(":k-norm", ly), eps)
        q = rope_half(q, positions, base)
        k = rope_half(k, positions, base)
        ctx = attend(q, k, v, heads, kv_heads, hd).reshape(seq, heads * hd)
        x1 = x + ctx @ tb.dequant(":wo", ly).T
        b = rmsnorm(x1, tb.f32(":ln2g", ly), eps)
        g = b @ tb.dequant(":wg", ly).T
        u = b @ tb.dequant(":wu", ly).T
        h = (g / (1.0 + np.exp(-g))) * u
        x = x1 + h @ tb.dequant(":wd", ly).T
        states.append(x.copy())
        print(f"  layer {ly}: rms {np.sqrt(np.mean(x * x)):.4f} "
              f"max|h| {np.abs(x).max():.4f}")

    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write(";; -*- lisp-data -*-  AUTO-GENERATED by "
                 "tools/qwen-forward-ref.py -- do not edit.\n")
        fh.write(";; Per-layer hidden states of the SAME int8 table the Elisp\n")
        fh.write(";; forward reads, dequantized the same way, in float64.\n")
        fh.write(f"(:tokens ({' '.join(str(t) for t in tokens)})\n")
        fh.write(f" :layers {nlayers} :dim {dim} :seq {seq}\n")
        fh.write(" :states (\n")
        for i, s in enumerate(states):
            flat = s.reshape(-1)
            fh.write(f"  ;; {'embedding' if i == 0 else f'after layer {i - 1}'}\n")
            fh.write("  (" + " ".join(repr(float(v)) for v in flat) + ")\n")
        fh.write(" ))\n")
    print(f"wrote {out_path}: {len(states)} states, {seq} x {dim} each")


if __name__ == "__main__":
    args = sys.argv[1:]
    layers = DEFAULT_LAYERS
    if "--layers" in args:
        i = args.index("--layers")
        layers = int(args[i + 1])
        del args[i:i + 2]
    if len(args) < 2:
        raise SystemExit(__doc__)
    toks = [int(a) for a in args[2:]] or DEFAULT_TOKENS
    main(args[0], args[1], toks, layers)
