#!/usr/bin/env python3
"""Generate token-id parity fixtures from the authoritative tokenizer.

Doc 08 Phase 1, Verification check 1.  The fixtures are produced by the
HuggingFace `tokenizers' library reading the donor's own `tokenizer.json', so
they are ground truth -- the Elisp implementation is compared against the donor,
not against a second guess written by the same author.

Two outputs:

  OUT.eld       small hand-picked cases, text stored as Unicode code points
  OUT-bulk.eld  whole-file id sequences for real corpora, pinned to a digest

Case text is emitted as code points rather than as an Elisp string literal: the
corpus deliberately contains control characters, lone whitespace runs and
unusual codepoints, and escaping those through a string literal is exactly where
a fixture generator would introduce the mismatch it is supposed to detect.

Usage:
    PYTHONPATH=build/donor/pylibs python3 tools/qwen-tokenizer-fixtures.py \
        build/donor/qwen3-0.6b/tokenizer.json test/fixtures/qwen-tokenizer.eld
"""

import hashlib
import os
import sys

from tokenizers import Tokenizer

CASES = [
    # --- plain ASCII and the contraction alternative -----------------------
    "hello world",
    "Hello",
    "it's",
    "IT'S",
    "It'S",
    "they're we've I'm you'll he'd don't",
    "'s at the start",
    # --- digits split one at a time in this tokenizer ----------------------
    "1",
    "42",
    "2026-09-19",
    "3.14159",
    "1234567890",
    # --- whitespace: the hard part of the pre-tokenizer regex --------------
    " leading",
    "trailing ",
    "two  spaces",
    "three   spaces   here",
    "\ttab",
    "a\tb",
    "line1\nline2",
    "line1\r\nline2",
    "\n",
    "\n\n",
    "  \n\n  ",
    "end with newline\n",
    "   ",
    " ",
    "a   \n   b",
    "word \n word",
    # --- punctuation runs --------------------------------------------------
    "!!!",
    "a!!!b",
    " ...",
    "(paren)",
    "a,b;c:d",
    "-> => <-",
    # --- Japanese ----------------------------------------------------------
    "こんにちは",
    "電気管理技術者です。",
    "月次点検は月初に集中します。",
    "電気保安管理事務所",
    "全角　スペース",
    "カタカナとひらがなと漢字",
    "日本語とEnglishの混在テキスト",
    "絶縁抵抗は0.1MΩ以上",
    # --- NFC normalisation: decomposed input must fold ---------------------
    "が",            # ka + combining dakuten -> ga
    "é",            # e + combining acute -> e-acute
    "ｶﾞ",            # halfwidth ka + halfwidth dakuten
    # --- Unicode whitespace and number categories --------------------------
    "nbsp here",
    "ideographic　space",
    "thin space",
    "²³",            # superscript two, three (category No)
    "½",                  # vulgar fraction one half (No)
    "一二三",      # CJK numerals (category Lo, not N)
    "٣٤",            # Arabic-Indic digits (Nd)
    "ⅠⅡ",            # Roman numeral one, two (Nl)
    # --- emoji and astral plane -------------------------------------------
    "\U0001f600",
    "a\U0001f600b",
    "\U0001f468‍\U0001f4bb",
    # --- Elisp source ------------------------------------------------------
    "(defun foo (x) (+ x 1))",
    ";;; nl-llm.el --- thing  -*- lexical-binding: t; -*-",
    "(let ((xs '(1 2 3))) (nreverse xs))",
    "(require 'photon-tensor)\n(provide 'nl-llm-arch)\n",
    "#+begin_src elisp\n(message \"hi\")\n#+end_src",
    # --- added / special tokens --------------------------------------------
    "<|endoftext|>",
    "<|im_start|>user\nhi<|im_end|>\n",
    "text <|endoftext|> more",
    "<think>",
    # --- degenerate --------------------------------------------------------
    "",
    "a",
    "\x00",
    "\x7f",
    "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    "\u0000\u0001\u0002",
]

BULK = [
    # Repo-relative files, so the fixture stays reproducible from a clone.
    # Chosen to cover what the model is actually fed: English open-data prose,
    # Elisp source, org markup with tables, and Japanese technical text.
    "data/corpus.txt",
    "lisp/nl-llm-arch.el",
    "test/fixtures/corpus-org.org",
    "test/fixtures/corpus-ja.txt",
]


def write_cases(tok, out_path):
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write(";; -*- lisp-data -*-  AUTO-GENERATED by "
                 "tools/qwen-tokenizer-fixtures.py -- do not edit.\n")
        fh.write(";; Ground truth from the HuggingFace `tokenizers' library.\n")
        fh.write(";; Each entry is (CODEPOINTS . IDS); text is code points so no\n")
        fh.write(";; string escaping sits between the oracle and the test.\n(\n")
        total = 0
        for text in CASES:
            ids = tok.encode(text, add_special_tokens=False).ids
            if text and tok.decode(ids, skip_special_tokens=False) != text:
                # Expected where NFC folds the input; recorded so the Elisp side
                # is not blamed for a difference the reference also has.
                fh.write(f" ;; note: decode(encode) != input for {text!r}\n")
            cps = " ".join(str(ord(c)) for c in text)
            fh.write(f" (({cps}) . ({' '.join(str(i) for i in ids)}))\n")
            total += len(ids)
        fh.write(")\n")
    print(f"wrote {out_path}: {len(CASES)} cases, {total} ids")


def write_bulk(tok, repo, out_path):
    """Emit whole-file id sequences, each pinned to a digest of its text.

    The digest is what stops a stale fixture from silently passing after the
    source file changes: the Elisp side recomputes it and refuses to compare
    against ids that were generated from different text.
    """
    total = 0
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write(";; -*- lisp-data -*-  AUTO-GENERATED by "
                 "tools/qwen-tokenizer-fixtures.py -- do not edit.\n")
        fh.write(";; Entries are (RELATIVE-PATH SHA256-OF-UTF8-TEXT (IDS...)).\n(\n")
        for rel in BULK:
            path = os.path.join(repo, rel)
            if not os.path.exists(path):
                print(f"  skip missing {rel}")
                continue
            with open(path, "r", encoding="utf-8", newline="") as src:
                text = src.read()
            digest = hashlib.sha256(text.encode("utf-8")).hexdigest()
            ids = tok.encode(text, add_special_tokens=False).ids
            fh.write(f' ("{rel}" "{digest}"\n  (')
            fh.write(" ".join(str(i) for i in ids))
            fh.write("))\n")
            total += len(ids)
            print(f"  {rel}: {len(text)} chars -> {len(ids)} ids")
        fh.write(")\n")
    print(f"wrote {out_path}: {total} ids")


CAT_STRIDE = 211
CAT_DENSE = 0x3000
WHITE_SPACE = [(0x09, 0x0D), (0x20, 0x20), (0x85, 0x85), (0xA0, 0xA0),
               (0x1680, 0x1680), (0x2000, 0x200A), (0x2028, 0x2029),
               (0x202F, 0x202F), (0x205F, 0x205F), (0x3000, 0x3000)]


def write_cats(tok, out_path):
    """Emit the reference pre-tokenizer's letter/number verdict for a sample.

    The exporter probes every code point and stores ranges; this samples the
    same question independently, so the test exercises the whole probe ->
    ranges -> binary -> Elisp binary search path against the authority instead
    of trusting that a few hundred ranges decode back to what was probed.

    Dense below U+3000 (Latin through CJK punctuation, where nearly all real
    text lives and where a boundary error would matter), strided above.
    """
    pre = tok.pre_tokenizer
    ws = set()
    for lo, hi in WHITE_SPACE:
        ws.update(range(lo, hi + 1))
    points = set(range(CAT_DENSE))
    points.update(range(CAT_DENSE, 0x110000, CAT_STRIDE))
    for text in CASES:
        points.update(ord(c) for c in text)
    points = sorted(cp for cp in points if not 0xD800 <= cp <= 0xDFFF)

    counts = [0, 0, 0]
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write(";; -*- lisp-data -*-  AUTO-GENERATED by "
                 "tools/qwen-tokenizer-fixtures.py -- do not edit.\n")
        fh.write(";; Flat (CODEPOINT CLASS ...) where CLASS is 0=other,\n")
        fh.write(";; 1=letter, 2=number, per the reference pre-tokenizer.\n(\n")
        for cp in points:
            ch = chr(cp)
            if len(pre.pre_tokenize_str("a" + ch)) == 1:
                cls = 1
            elif cp not in ws and len(pre.pre_tokenize_str(ch + ch)) == 2:
                cls = 2
            else:
                cls = 0
            counts[cls] += 1
            fh.write(f" {cp} {cls}\n")
        fh.write(")\n")
    print(f"wrote {out_path}: {len(points)} code points "
          f"({counts[1]} letter, {counts[2]} number, {counts[0]} other)")


def main(tokenizer_json, out_path):
    tok = Tokenizer.from_file(tokenizer_json)
    # A post-processor that injected ids would make these fixtures describe the
    # chat template rather than the tokenizer; refuse instead of absorbing it.
    if tok.encode("x").ids != tok.encode("x", add_special_tokens=False).ids:
        raise SystemExit("post-processor adds ids; regenerate with it disabled")

    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    write_cases(tok, out_path)
    base, ext = os.path.splitext(out_path)
    # Derived from this script's own location (tools/), so bulk paths resolve
    # however the tool is invoked.
    repo = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    write_bulk(tok, repo, base + "-bulk" + ext)
    write_cats(tok, base + "-cats" + ext)


if __name__ == "__main__":
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    main(sys.argv[1], sys.argv[2])
